Repository eclipse-iceoryx/iceoryx, pull requests merged in 2020-09, with the labels that each got.

#265 Iox #238 iceperf qnx
  iceoryx_examples/iceperf/CMakeLists.txt
Labels: bugfix

#189 iox-#186 Add first cxx::forward_list implementation to utils
  .gitignore
  iceoryx_utils/README.md
  iceoryx_utils/include/iceoryx_utils/cxx/forward_list.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/forward_list.inl
  iceoryx_utils/test/moduletests/test_cxx_forward_list.cpp
Labels: enhancement

#262 Iox #217 gcov reports on iceoryx
  .github/workflows/build_test_cov.yml
  CONTRIBUTING.md
  README.md
  iceoryx_meta/CMakeLists.txt
  tools/gcov/gcovr_html.conf
  tools/gcov/gcovr_sonarqube.conf
  tools/gcov/lcov_generate.sh
  tools/iceoryx_build_test.sh
  tools/run_all_tests.sh
Labels: test

#272 iox-#271: Fix name clash
  .codecov.yml
  iceoryx_posh/source/roudi/roudi_process.cpp
Labels: bugfix

#274 iox-#273 re-enable warnings
  iceoryx_dds/test/mocks/google_mocks.hpp
  iceoryx_dds/test/moduletests/test_channel.cpp
  iceoryx_dds/test/moduletests/test_generic_dds_gateway.cpp
  iceoryx_dds/test/stubs/stubbed_dds_gateway_generic.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_utils/cmake/IceoryxPlatformDetection.cmake
  iceoryx_utils/include/iceoryx_utils/cxx/forward_list.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/forward_list.inl
  iceoryx_utils/test/moduletests/test_cxx_forward_list.cpp
Labels: bugfix

#253 Iox #208 additional functionality for cxx string
  iceoryx_utils/doc/fixedString.adoc
  iceoryx_utils/include/iceoryx_utils/cxx/string.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/string.inl
  iceoryx_utils/include/iceoryx_utils/internal/cxx/string_internal.hpp
  iceoryx_utils/test/CMakeLists.txt
  iceoryx_utils/test/moduletests/test_cxx_string.cpp
Labels: enhancement

#281 Iox #25 add new pubsub ports to roudi
  doc/installation-guide.md
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/iceoryx_port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/iceoryx_port_pool.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  tools/iceoryx_build_test.sh
Labels: refactoring

#290 iox-#289 fix SOFI ring buffer indexing
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.inl
Labels: bugfix

#300 Iox #25 cleanup posh runtime error handling
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: refactoring

#307 Iox #25 add cxx type traits
  CONTRIBUTING.md
  iceoryx_utils/include/iceoryx_utils/cxx/function_ref.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/type_traits.hpp
  iceoryx_utils/test/moduletests/test_cxx_type_traits.cpp
Labels: enhancement, refactoring

#292 Iox #25 implement unique publisher detection for new building blocks
  iceoryx_meta/CMakeLists.txt
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/iceoryx_posh_deployment.cmake
  iceoryx_posh/cmake/iceoryx_posh_deployment.hpp.in
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/iceoryx_port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data_base.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.inl
  iceoryx_posh/source/roudi/iceoryx_port_pool.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  tools/iceoryx_build_test.sh
Labels: refactoring
