Repository eclipse-iceoryx/iceoryx, pull requests merged in 2020-12, with the labels that each got.

#403 iox-#14 chunk header design with custom header
  iceoryx_posh/doc/chunk_header.md
Labels: documentation

#405 Iox #349 rename runnable to node
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/include/iceoryx_binding_c/node.h
  iceoryx_binding_c/include/iceoryx_binding_c/publisher.h
  iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h
  iceoryx_binding_c/source/c_node.cpp
  iceoryx_binding_c/test/integrationtests/test_node.cpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/node_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/node_property.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/introspection_types.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/node.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/node.cpp
  iceoryx_posh/source/runtime/node_data.cpp
  iceoryx_posh/source/runtime/node_property.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_shm.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: refactoring

#410 iox-#356 Add proposal for iceoryx developer meetup
  CONTRIBUTING.md
  GOVERNANCE.md
  README.md
Labels: documentation

#400 iox-#141 enable sanizier(-fsanitize=address)
  .github/workflows/build-test.yml
  .github/workflows/sanitize.yml
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_dds/CMakeLists.txt
  iceoryx_examples/benchmark_optional_and_expected/CMakeLists.txt
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery_on_c/CMakeLists.txt
  iceoryx_examples/iceperf/CMakeLists.txt
  iceoryx_examples/singleprocess/CMakeLists.txt
  iceoryx_examples/waitset/CMakeLists.txt
  iceoryx_examples/waitset_on_c/CMakeLists.txt
  iceoryx_meta/CMakeLists.txt
  iceoryx_meta/sanitizer_blacklist/asan_compile_time.txt
  iceoryx_meta/sanitizer_blacklist/asan_runtime.txt
  iceoryx_meta/sanitizer_blacklist/lsan_runtime.txt
  iceoryx_posh/CMakeLists.txt
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/cmake/IceoryxPlatform.cmake
  iceoryx_utils/test/moduletests/test_cxx_unique_ptr.cpp
  tools/iceoryx_build_test.sh
  tools/introspection/CMakeLists.txt
  tools/run_all_tests.sh
Labels: tooling

#417 Iox #91 Clean up todo's in RouDi classes
  GOVERNANCE.md
  iceoryx_dds/include/iceoryx_dds/dds/dds_config.hpp
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_generic.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi_environment/roudi_environment.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_components.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_provider.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser_config_file_option.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/include/iceoryx_posh/version/compatibility_check_level.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_main.cpp
  iceoryx_posh/source/roudi/iceoryx_roudi_components.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/roudi/memory/roudi_memory_manager.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser_config_file_option.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/roudi_environment/roudi_environment.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_compatability_check_level.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/thread.hpp
  iceoryx_utils/platform/linux/include/iceoryx_utils/platform/pthread.hpp
  iceoryx_utils/platform/mac/include/iceoryx_utils/platform/pthread.hpp
  iceoryx_utils/platform/qnx/include/iceoryx_utils/platform/pthread.hpp
  iceoryx_utils/platform/win/include/iceoryx_utils/platform/pthread.hpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_utils/source/posix_wrapper/thread.cpp
  iceoryx_utils/test/moduletests/test_posix_thread.cpp
  iceoryx_utils/testutils/mocks/logger_mock.hpp
Labels: refactoring

#421 Iox #394 create multi publisher example
  doc/getting-started.md
  iceoryx_examples/README.md
  iceoryx_examples/ice_multi_publisher/CMakeLists.txt
  iceoryx_examples/ice_multi_publisher/README.md
  iceoryx_examples/ice_multi_publisher/ice_multi_publisher.cpp
  iceoryx_examples/ice_multi_publisher/ice_resubscriber.cpp
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_examples/ice_multi_publisher/topic_data.hpp
  iceoryx_meta/CMakeLists.txt
  tools/iceoryx_build_test.sh
Labels: example

#430 Iox #381 remove leading slash from processname
  iceoryx_binding_c/test/moduletests/test_node.cpp
  iceoryx_binding_c/test/moduletests/test_runtime.cpp
  iceoryx_dds/source/dds2iceoryx_app/main.cpp
  iceoryx_dds/source/iceoryx2dds_app/main.cpp
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery/iox_publisher_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped_modern.cpp
  iceoryx_examples/icedelivery_on_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_on_c/ice_c_subscriber.c
  iceoryx_examples/iceperf/iceperf_hardy.cpp
  iceoryx_examples/iceperf/iceperf_laurel.cpp
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset/ice_waitset_sync.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/introspection_types.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/integrationtests/service_discovery/test_roudi_findservice.cpp
  iceoryx_posh/test/integrationtests/service_discovery/test_roudi_service_discovery.hpp
  iceoryx_posh/test/integrationtests/test_interface_port_stack_blowup.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_mq_interface.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/ipc_channel.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/message_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_utils/source/posix_wrapper/message_queue.cpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_utils/test/moduletests/test_ipc_channel.cpp
Labels: refactoring

#442 Iox #252 Move new API files
  GOVERNANCE.md
  iceoryx_dds/include/iceoryx_dds/gateway/dds_to_iox.hpp
  iceoryx_dds/include/iceoryx_dds/gateway/iox_to_dds.hpp
  iceoryx_dds/test/mocks/google_mocks.hpp
  iceoryx_examples/ice_multi_publisher/ice_multi_publisher.cpp
  iceoryx_examples/ice_multi_publisher/ice_resubscriber.cpp
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_examples/icedelivery/iox_publisher_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped_modern.cpp
  iceoryx_examples/iceperf/iceoryx.hpp
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset/ice_waitset_sync.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/sample.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/typed_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/typed_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/popo/base_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/base_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/sample.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/typed_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/typed_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp
  iceoryx_posh/test/mocks/publisher_mock.hpp
  iceoryx_posh/test/mocks/subscriber_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_typed_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_typed_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_subscriber.cpp
  iceoryx_utils/platform/win/include/iceoryx_utils/platform/mman.hpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp
  tools/introspection/include/iceoryx_introspection/introspection_app.hpp
Labels: refactoring

#429 iox-#427 Add on demand function loader for system function mocks
  iceoryx_utils/testutils/mocks/mocks.hpp
  iceoryx_utils/testutils/mocks/mqueue_mock.cpp
  iceoryx_utils/testutils/mocks/time_mock.cpp
Labels: bugfix

#434 Iox #431 iox::relative_ptr takes invalid state when constructed/assigned from iox::RelativePointer
  iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_ptr.hpp
  iceoryx_utils/test/moduletests/test_relative_pointer.cpp
Labels: bugfix

#450 iox-#204 making mac semaphore shm compatible
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/cmake/idlpp-cxx-generate.cmake.in
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_utils/platform/mac/include/iceoryx_utils/platform/semaphore.hpp
  iceoryx_utils/platform/mac/source/semaphore.cpp
  iceoryx_utils/source/posix_wrapper/mutex.cpp
Labels: bugfix

#460 Iox #337 create periodic task
  .gitignore
  CONTRIBUTING.md
  README.md
  doc/website/getting-started/installation.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery/iox_publisher_typed.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_publisher_with_history.cpp
  iceoryx_examples/icedelivery/iox_subscriber_typed.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber_with_history.cpp
  iceoryx_examples/icedelivery_on_c/README.md
  iceoryx_examples/icedelivery_on_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_on_c/ice_c_subscriber.c
  iceoryx_examples/icedelivery_on_c/topic_data.h
  iceoryx_meta/tests.cmake
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.inl
  iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp
  iceoryx_utils/platform/mac/source/semaphore.cpp
  iceoryx_utils/source/posix_wrapper/semaphore.cpp
  iceoryx_utils/test/moduletests/test_concurrent_periodic_task.cpp
  tools/docker/README.md
  tools/iceoryx_build_test.sh
Labels: refactoring
