Repository eclipse-iceoryx/iceoryx, pull requests merged in 2020-08, with the labels that each got.

#202 iox-#25 Remove deprecated semaphore methods in ChunkQueuePopper
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_variable_data.hpp
  iceoryx_posh/include/iceoryx_posh/popo/condition.hpp
  iceoryx_posh/include/iceoryx_posh/popo/guard_condition.hpp
  iceoryx_posh/source/popo/building_blocks/chunk_queue_popper.cpp
  iceoryx_posh/source/popo/building_blocks/chunk_queue_pusher.cpp
  iceoryx_posh/source/popo/condition.cpp
  iceoryx_posh/source/popo/guard_condition.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
Labels: refactoring

#219 Iox #25 template config via properties
  .gitignore
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/publisher_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp
  iceoryx_posh/source/popo/ports/publisher_port_roudi.cpp
  iceoryx_posh/source/popo/ports/subscriber_port_single_producer.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
Labels: refactoring

#225 Iox #25 add locking policy to chunk queue
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/locking_policy.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/publisher_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_data.hpp
  iceoryx_posh/source/popo/building_blocks/locking_policy.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: enhancement

#199 iox-#198 Quality level proposal
  CONTRIBUTING.md
  PLANNED_FEATURES.md
  README.md
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/iceperf/CMakeLists.txt
  iceoryx_examples/singleprocess/CMakeLists.txt
  iceoryx_meta/CMakeLists.txt
Labels: documentation

#233 Iox #25 Integrate MPMC queue in VariantQueue
  iceoryx_utils/include/iceoryx_utils/cxx/variant_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/variant_queue.inl
  iceoryx_utils/test/moduletests/test_cxx_variant_queue.cpp
Labels: enhancement

#232 Iox #25 building block ports cleanups
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/application_port.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/interface_port.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/source/popo/gateway_generic.cpp
  iceoryx_posh/source/popo/ports/application_port.cpp
  iceoryx_posh/source/popo/ports/interface_port.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi_multi_process.cpp
  iceoryx_posh/test/integrationtests/service_discovery/test_roudi_findservice.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: refactoring

#239 Iox #25 queue harmonization
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp
  iceoryx_posh/source/popo/delivery_fifo.cpp
  iceoryx_posh/source/popo/ports/subscriber_port_user.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/variant_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/fifo.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/fifo.inl
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.inl
  iceoryx_utils/include/iceoryx_utils/internal/cxx/variant_queue.inl
  iceoryx_utils/test/moduletests/test_concurrent_sofi.cpp
Labels: refactoring

#203 iox-#198 add swe doxygen example
  CONTRIBUTING.md
  doc/aspice_swe3_4/example/Doxyfile
  doc/aspice_swe3_4/example/iceoryx_component/include/example_component/example_component.hpp
  doc/aspice_swe3_4/example/iceoryx_component/include/example_component/example_derived_class.hpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_component/example_base_class.cpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_component/example_base_class.hpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_component/example_base_class.inl
  doc/aspice_swe3_4/example/iceoryx_component/test/moduletests/test_example_base_class.cpp
  doc/aspice_swe3_4/swe_docu_guidelines.md
Labels: documentation

#247 Iox #238 extension of iceperf
  doc/usage-guide.md
  iceoryx_examples/icecrystal/Readme.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/iceperf/CMakeLists.txt
  iceoryx_examples/iceperf/README.md
  iceoryx_examples/iceperf/base.cpp
  iceoryx_examples/iceperf/base.hpp
  iceoryx_examples/iceperf/iceoryx.cpp
  iceoryx_examples/iceperf/iceoryx.hpp
  iceoryx_examples/iceperf/iceperf_hardy.cpp
  iceoryx_examples/iceperf/iceperf_laurel.cpp
  iceoryx_examples/iceperf/mq.cpp
  iceoryx_examples/iceperf/mq.hpp
  iceoryx_examples/iceperf/topic_data.hpp
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_examples/iceperf/uds.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
Labels: example

#231 iox-229: version check for RouDi and apps
  CONTRIBUTING.md
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/iceoryx_versions.hpp.in
  iceoryx_posh/cmake/iceoryxversions.cmake
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_multi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/include/iceoryx_posh/version/compatibility_check_level.hpp
  iceoryx_posh/include/iceoryx_posh/version/version_info.hpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_multi_process.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/source/version/version_info.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_version_info.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/helplets.hpp
Labels: enhancement

#259 Iox #25 add integration test pubsub port user
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp
  iceoryx_posh/source/popo/ports/subscriber_port_user.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
Labels: test

#258 Iox #25 Introduce condition variable handling in RouDi and do a bit of housekeeping
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi_environment/roudi_environment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/runnable_property.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_components.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_config.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_config.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/roudi_environment/roudi_environment.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/source/runtime/runnable_property.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_shm.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: enhancement, refactoring
