Repository eclipse-iceoryx/iceoryx, pull requests merged in 2020-05, with the labels that each got.

#82 Iox #78 Minor RouDi config adaptions
  doc/usage-guide.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_posh/cmake/install_help_and_config.cmake
  iceoryx_posh/etc/iceoryx/roudi_config_example.toml
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_main.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser_config_file_option.cpp
  iceoryx_utils/testutils/roudi_gtest.hpp
Labels: refactoring

#99 Remove direct use of fundamental datatypes
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser_config_file_option.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/access_control.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/argv_inspection.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/message_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/timespec.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp
  iceoryx_utils/platform/linux/include/iceoryx_utils/platform/types.hpp
  iceoryx_utils/platform/linux/include/iceoryx_utils/platform/unistd.hpp
  iceoryx_utils/platform/linux/source/unistd.cpp
  iceoryx_utils/source/log/ac3log_shim/simplelogger.cpp
  iceoryx_utils/source/posix_wrapper/access_control.cpp
  iceoryx_utils/source/posix_wrapper/argv_inspection.cpp
  iceoryx_utils/source/posix_wrapper/message_queue.cpp
  iceoryx_utils/source/posix_wrapper/posix_access_rights.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_utils/source/posix_wrapper/timer.cpp
  iceoryx_utils/source/posix_wrapper/timespec.cpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
  tools/introspection/source/introspection_app.cpp
Labels: MISRA

#106 Add iceoryx usage table
  CONTRIBUTING.md
  README.md
Labels: documentation

#111 iox-#110 increase PROCESS_WAITING_FOR_ROUDI_TIMEOUT to 60s
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
Labels: bugfix

#103 Iox #76 remove const cast wherever possible
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp
  iceoryx_posh/source/mepoo/chunk_header.cpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/optional.inl
  iceoryx_utils/include/iceoryx_utils/internal/cxx/vector.inl
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/allocator.hpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/allocator.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_utils/test/moduletests/test_allocator.cpp
Labels: CERT, MISRA

#114 iox-#113 cleanup shared memory at restart after an anomaly
  iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp
Labels: bugfix

#69 Iox #32 implement posix timer and introduced timing test
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp
  iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp
  iceoryx_posh/source/roudi/roudi_multi_process.cpp
  iceoryx_posh/test/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/internal/cxx/convert.inl
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp
  iceoryx_utils/platform/mac/include/iceoryx_utils/platform/time.hpp
  iceoryx_utils/platform/mac/source/semaphore.cpp
  iceoryx_utils/platform/mac/source/time.cpp
  iceoryx_utils/source/posix_wrapper/timer.cpp
  iceoryx_utils/test/CMakeLists.txt
  iceoryx_utils/test/moduletests/test_posix_timer.cpp
  iceoryx_utils/test/moduletests/test_semaphore_module.cpp
  iceoryx_utils/testutils/timing_test.hpp
Labels: enhancement

#116 Iox #88 remove simplelogger calls
  iceoryx_posh/cmake/iceoryx_versions.hpp.in
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_multi_process.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
  iceoryx_posh/source/popo/sender_port.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi_multi_process.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_utils/source/error_handling/error_handling.cpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#102 Iox #25 communication setup with chunk building blocks integration test
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/source/popo/building_blocks/chunk_queue_popper.cpp
  iceoryx_posh/source/popo/building_blocks/chunk_queue_pusher.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/expected.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl
  iceoryx_utils/test/moduletests/test_cxx_expected.cpp
Labels: test
