Repository eclipse-iceoryx/iceoryx, pull requests merged in 2020-11, with the labels that each got.

#323 Iox #322 roudi segfault introspection mempool
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  tools/introspection/source/introspection_app.cpp
Labels: bugfix

#145 Iox #115 add sofi stresstests
  iceoryx_utils/test/CMakeLists.txt
  iceoryx_utils/test/stresstests/test_stress_sofi.cpp
Labels: test

#339 iox-#338: Add copyright header
  iceoryx_posh/cmake/iceoryx_poshConfig.cmake
  iceoryx_posh/cmake/iceoryx_posh_deployment.cmake
  iceoryx_posh/cmake/iceoryxversions.cmake
  iceoryx_posh/cmake/install_help_and_config.cmake
  iceoryx_posh/test/integrationtests/service_discovery/test_roudi_service_discovery.hpp
  iceoryx_utils/cmake/IceoryxPackageHelper.cmake
  iceoryx_utils/cmake/IceoryxPlatformDetection.cmake
  iceoryx_utils/cmake/iceoryx_utilsConfig.cmake
  iceoryx_utils/cmake/iceoryx_utils_testingConfig.cmake
  iceoryx_utils/source/cxx/helplets.cpp
  tools/introspection/cmake/iceoryx_introspectionConfig.cmake
Labels: bugfix

#335 iox #252 example applications using new api
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery/iox_publisher_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped_modern.cpp
  iceoryx_examples/icedelivery/topic_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/base_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/base_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/sample.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/typed_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/typed_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/untyped_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/untyped_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/base_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/base_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/sample.hpp
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/typed_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/typed_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/untyped_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/modern_api/untyped_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.inl
  iceoryx_posh/source/roudi/iceoryx_port_pool.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/test/mocks/publisher_mock.hpp
  iceoryx_posh/test/mocks/subscriber_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_typed_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_subscriber.cpp
Labels: enhancement

#362 iox-#354 simplelogger ... gone for good
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/ac3log/simplelogger.hpp
  iceoryx_utils/source/log/ac3log_shim/simplelogger.cpp
  iceoryx_utils/source/log/logmanager.cpp
Labels: refactoring

#343 Iox #313 document error handling
  CONTRIBUTING.md
  doc/conceptual-guide.md
  doc/error-handling.md
Labels: documentation

#352 Iox #340 simplify expected optionals
  iceoryx_examples/icedelivery/iox_publisher_untyped_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_typed_modern.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped_modern.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/expected.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/optional.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/unique_ptr.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl
  iceoryx_utils/include/iceoryx_utils/internal/cxx/unique_ptr.inl
  iceoryx_utils/test/moduletests/test_cxx_expected.cpp
Labels: enhancement

#367 iox-#366 update maintainer list
  README.md
Labels: documentation

#361 iox-#260 CString100 ... gone for good
  iceoryx_examples/iceperf/mq.hpp
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/runnable_data.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/introspection_types.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/runnable.hpp
  iceoryx_posh/include/iceoryx_posh/version/version_info.hpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/source/runtime/runnable.cpp
  iceoryx_posh/source/runtime/runnable_data.cpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_posh_receiverport.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_shm.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/convert.hpp
  iceoryx_utils/include/iceoryx_utils/fixed_string/string100.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/message_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
Labels: refactoring

#364 Iox#216 lockfree queue preliminary simplification refactoring
  iceoryx_utils/include/iceoryx_utils/concurrent/lockfree_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/lockfree_queue/index_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/lockfree_queue/index_queue.inl
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/lockfree_queue/lockfree_queue.inl
  iceoryx_utils/test/moduletests/test_index_queue.cpp
  iceoryx_utils/test/moduletests/test_index_queue_unique_index.cpp
Labels: refactoring

#333 Iox #324 roudi improve app shutdown
  .gitignore
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/roudi_environment/roudi_environment.cpp
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/README.md
  iceoryx_utils/include/iceoryx_utils/cxx/smart_c.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/locked_loffli.hpp
  iceoryx_utils/platform/win/include/iceoryx_utils/platform/signal.hpp
  iceoryx_utils/source/concurrent/locked_loffli.cpp
  iceoryx_utils/test/moduletests/test_concurrent_loffli.cpp
Labels: bugfix

#379 Iox #374 fix strncpy usage
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/string.inl
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/semaphore.hpp
  iceoryx_utils/source/posix_wrapper/message_queue.cpp
  iceoryx_utils/source/posix_wrapper/semaphore.cpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_utils/test/moduletests/test_ipc_channel.cpp
Labels: bugfix

#224 Iox #221 apply cxx list
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
Labels: enhancement
