Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-12, with the labels that each got.

#980 Make `string::capacity()` static
  CHANGELOG.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
Labels: enhancement

#990 Iox #471 restructure scripts
  .github/workflows/build-test.yml
  CHANGELOG.md
  CONTRIBUTING.md
  QUALITY_DECLARATION.md
  doc/design/README.md
  tools/axivion/axivion_config.json
  tools/axivion/wait_for_pipeline.py
  tools/ci/build-test-macos-with-sanitizers.sh
  tools/ci/build-test-macos.sh
  tools/ci/build-test-ubuntu-with-gcc54.sh
  tools/ci/build-test-ubuntu-with-sanitizers.sh
  tools/ci/build-test-ubuntu.sh
  tools/ci/build-ubuntu-with-latest-clang-gcc.sh
  tools/ci/coverage-and-docs.sh
  tools/ci/run-clang-tidy.sh
  tools/ci/run-integration-test.sh
  tools/docker/Dockerfile
  tools/docker/bind_iceoryx_docker.sh
  tools/docker/run_iceoryx_docker.sh
  tools/git-hooks/Readme.md
  tools/git-hooks/pre-commit
  tools/iceoryx_build_test.sh
  tools/run_tests.sh
  tools/scripts/add_test_users.sh
  tools/scripts/check_formatting.sh
  tools/scripts/generate_plantuml_svg.sh
  tools/scripts/iceoryx_release.sh
  tools/scripts/lcov_generate.sh
  tools/scripts/list_stl_dependencies.sh
  tools/website/export-docu-to-website.sh
Labels: documentation, tooling

#917 iox-#415 Rename variable and test case name in `ServiceRegistry_test` and fix bug in `ServiceDescription` c'tor
  CHANGELOG.md
  CONTRIBUTING.md
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/popo/client_options.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: refactoring
