Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-02, with the labels that each got.

#520 iox #350 cleanup enable event signature
  iceoryx_binding_c/include/iceoryx_binding_c/internal/cpp2c_subscriber.hpp
  iceoryx_binding_c/source/c_wait_set.cpp
  iceoryx_binding_c/source/cpp2c_subscriber.cpp
  iceoryx_binding_c/test/moduletests/test_event_info.cpp
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_sync.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/event_attorney.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/trigger.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/user_trigger.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/include/iceoryx_posh/popo/base_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/event_attorney.hpp
  iceoryx_posh/include/iceoryx_posh/popo/event_info.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger_handle.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/user_trigger.hpp
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/source/popo/trigger.cpp
  iceoryx_posh/source/popo/trigger_handle.cpp
  iceoryx_posh/source/popo/user_trigger.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/test/mocks/wait_set_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_trigger_handle.cpp
  iceoryx_posh/test/moduletests/test_popo_user_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/vector.inl
  iceoryx_utils/test/moduletests/test_cxx_vector.cpp
Labels: refactoring

#526 iox-#525 updated documentation to state requirements
  CONTRIBUTING.md
  doc/website/getting-started/installation.md
  iceoryx_dds/README.md
Labels: documentation

#501 Iox #190 fixed point types for duration internal representation
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp
  iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp
  iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp
  iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl
  iceoryx_utils/source/posix_wrapper/timer.cpp
  iceoryx_utils/source/units/duration.cpp
  iceoryx_utils/test/moduletests/test_cxx_deadline_timer.cpp
  iceoryx_utils/test/moduletests/test_ipc_channel.cpp
  iceoryx_utils/test/moduletests/test_posix_timer.cpp
  iceoryx_utils/test/moduletests/test_semaphore_module.cpp
  iceoryx_utils/test/moduletests/test_unit_duration.cpp
  iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark.hpp
  tools/introspection/source/introspection_app.cpp
Labels: bugfix, refactoring

#534 iox-#533 Add Installation guide after building.
  doc/website/getting-started/installation.md
Labels: documentation

#535 Iox #381 Switch from message queue to UNIX domain sockets
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/node_property.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/iceoryx_roudi_components.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_mq_interface.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/test/moduletests/test_ipc_channel.cpp
  iceoryx_utils/test/moduletests/test_unix_domain_sockets.cpp
Labels: refactoring

#532 Iox #349 introduce node in C API
  iceoryx_binding_c/include/iceoryx_binding_c/publisher.h
  iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h
  iceoryx_binding_c/source/c_publisher.cpp
  iceoryx_binding_c/source/c_subscriber.cpp
  iceoryx_examples/icedelivery_on_c/README.md
  iceoryx_examples/icedelivery_on_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_on_c/ice_c_subscriber.c
  iceoryx_examples/iceperf/iceoryx_c.cpp
  iceoryx_examples/waitset_on_c/README.md
  iceoryx_examples/waitset_on_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_on_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_on_c/ice_c_waitset_individual.c
  iceoryx_examples/waitset_on_c/ice_c_waitset_publisher.c
Labels: enhancement

#541 iox-#136 Rename examples from '*_on_c' to '*_in_c'
  doc/website/getting-started/examples/basic-examples.md
  doc/website/getting-started/examples/intermediate-examples.md
  doc/website/getting-started/overview.md
  iceoryx_binding_c/README.md
  iceoryx_examples/README.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery_in_c/CMakeLists.txt
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icedelivery_in_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
  iceoryx_examples/icedelivery_in_c/sleep_for.h
  iceoryx_examples/icedelivery_in_c/topic_data.h
  iceoryx_examples/waitset_in_c/CMakeLists.txt
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_publisher.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_sync.c
  iceoryx_examples/waitset_in_c/sleep_for.h
  iceoryx_examples/waitset_in_c/topic_data.h
  iceoryx_meta/CMakeLists.txt
  tools/iceoryx_build_test.sh
Labels: documentation

#523 Iox #404 Fix verbose output and introduce CmdLineArgs_t struct
  iceoryx_examples/iceperf/roudi_main_static_config.cpp
  iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser_config_file_option.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_config_toml_file_provider.hpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_main.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser_config_file_option.cpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
  iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp
  iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser_config_file_option.cpp
Labels: bugfix, refactoring

#546 iox-#536 refactored creation/getter method names in units::Duration
  iceoryx_binding_c/source/c_wait_set.cpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp
  iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp
  iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp
  iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl
  iceoryx_utils/source/posix_wrapper/timer.cpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_utils/test/moduletests/test_cxx_deadline_timer.cpp
  iceoryx_utils/test/moduletests/test_posix_timer.cpp
  iceoryx_utils/test/moduletests/test_semaphore_module.cpp
  iceoryx_utils/test/moduletests/test_unit_duration.cpp
  iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark.hpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#545 Iox #484 improve posix mutex test
  iceoryx_utils/test/moduletests/test_posix_mutex.cpp
Labels: test

#544 Iox #483 Copyright Header Contributing.md
  CONTRIBUTING.md
Labels: documentation

#553 Iox #542 resource leak fix
  iceoryx_utils/include/iceoryx_utils/cxx/generic_raii.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_utils/source/cxx/generic_raii.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_utils/test/moduletests/test_cxx_generic_raii.cpp
Labels: bugfix

#538 Iox #381 Rename and refactor message queue interface classes
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_creator.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_message.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_message.inl
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_components.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/iceoryx_roudi_components.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/source/runtime/ipc_interface_creator.cpp
  iceoryx_posh/source/runtime/ipc_interface_user.cpp
  iceoryx_posh/source/runtime/ipc_message.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_mq_interface.cpp
  iceoryx_posh/test/moduletests/test_mq_message.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_utils/test/moduletests/test_unix_domain_sockets.cpp
  iceoryx_utils/testutils/mocks/mqueue_mock.cpp
  iceoryx_utils/testutils/mocks/mqueue_mock.hpp
Labels: refactoring

#547 Iox #521 best practice for testing
  CONTRIBUTING.md
  doc/website/advanced/best-practice-for-testing.md
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_utils/test/moduletests/test_unit_duration.cpp
Labels: documentation

#530 Iox #496 improve coverage and refactor ServiceDescription moduletests
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
Labels: test

#552 Iox #408 transition to 1 0 cpp api
  doc/website/getting-started/overview.md
  iceoryx_binding_c/include/iceoryx_binding_c/enums.h
  iceoryx_binding_c/source/c_publisher.cpp
  iceoryx_binding_c/source/cpp2c_subscriber.cpp
  iceoryx_binding_c/test/moduletests/test_event_info.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_dds/include/iceoryx_dds/internal/gateway/dds_to_iox.inl
  iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl
  iceoryx_dds/test/mocks/google_mocks.hpp
  iceoryx_examples/ice_multi_publisher/README.md
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_examples/icedelivery/iox_publisher_typed.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_publisher_with_history.cpp
  iceoryx_examples/icedelivery/iox_subscriber_typed.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber_with_history.cpp
  iceoryx_examples/iceperf/iceoryx.cpp
  iceoryx_examples/iceperf/iceoryx_c.cpp
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/publisher_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/sample_deleter.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/sample_deleter.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/typed_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/typed_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/popo/base_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/base_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/typed_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/typed_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp
  iceoryx_posh/source/popo/ports/publisher_port_user.cpp
  iceoryx_posh/test/mocks/publisher_mock.hpp
  iceoryx_posh/test/mocks/subscriber_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_typed_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_typed_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_subscriber.cpp
Labels: refactoring

#550 Iox #381 Fix flooding the command line and resource leak
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
Labels: bugfix

#561 Iox #408 rename publisher and subscriber
  .github/PULL_REQUEST_TEMPLATE.md
  doc/design/chunk_header.md
  doc/website/getting-started/overview.md
  iceoryx_examples/ice_multi_publisher/README.md
  iceoryx_examples/ice_multi_publisher/ice_multi_publisher.cpp
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery/iox_publisher.cpp
  iceoryx_examples/icedelivery/iox_publisher_with_history.cpp
  iceoryx_examples/icedelivery/iox_subscriber.cpp
  iceoryx_examples/icedelivery/iox_subscriber_with_history.cpp
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset/ice_waitset_sync.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/popo/typed_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/typed_subscriber.hpp
  iceoryx_posh/test/mocks/publisher_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_subscriber.cpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#513 Iox #496 improve coverage for posh runtime
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime_node.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime_single_process.cpp
Labels: test

#565 Iox #542 sigaction abstraction
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/signal_handler.hpp
  iceoryx_utils/source/posix_wrapper/signal_handler.cpp
  iceoryx_utils/test/moduletests/test_posix_signal_handler.cpp
Labels: enhancement

#572 iox-#570 fixed variant move ctor and assignment behavior
  iceoryx_utils/include/iceoryx_utils/internal/cxx/variant.inl
  iceoryx_utils/test/moduletests/test_cxx_variant.cpp
Labels: bugfix

#573 Iox #571 replace timespec by duration in semaphore
  iceoryx_posh/source/popo/building_blocks/condition_variable_waiter.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.inl
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/semaphore.hpp
  iceoryx_utils/source/posix_wrapper/semaphore.cpp
  iceoryx_utils/test/moduletests/test_semaphore_module.cpp
Labels: refactoring

#567 iox-#542 use the signal handler everywhere
  iceoryx_dds/source/dds2iceoryx_app/main.cpp
  iceoryx_dds/source/iceoryx2dds_app/main.cpp
  iceoryx_examples/ice_multi_publisher/ice_multi_publisher.cpp
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_examples/icedelivery/iox_publisher.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_publisher_with_history.cpp
  iceoryx_examples/icedelivery/iox_subscriber.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber_with_history.cpp
  iceoryx_examples/icedelivery_in_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset/ice_waitset_sync.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_publisher.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_sync.c
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/signal_handler.hpp
  iceoryx_utils/source/posix_wrapper/signal_handler.cpp
  iceoryx_utils/test/moduletests/test_posix_signal_handler.cpp
Labels: refactoring

#527 Iox #454 enhancing coverage for class roudi and port manager in roudi folder
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
Labels: test

#557 Iox #542 use creation pattern for posix wrapper
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_pointer.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_pointer.inl
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp
  iceoryx_posh/source/roudi/memory/default_roudi_memory.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
  iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp
  iceoryx_utils/include/iceoryx_utils/internal/design_pattern/creation.inl
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_utils/platform/win/include/iceoryx_utils/platform/mman.hpp
  iceoryx_utils/platform/win/include/iceoryx_utils/platform/platform_correction.hpp
  iceoryx_utils/source/posix_wrapper/message_queue.cpp
  iceoryx_utils/source/posix_wrapper/semaphore.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_utils/test/moduletests/test_shared_memory.cpp
  iceoryx_utils/test/moduletests/test_shared_memory_object.cpp
  iceoryx_utils/test/moduletests/test_smart_c_module.cpp
Labels: refactoring

#554 Iox #542 Invalidate `rhs` if an `expected` is moved
  doc/design/error-handling.md
  iceoryx_dds/include/iceoryx_dds/dds/data_reader.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/channel.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_generic.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_pointer.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_provider.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_config_file_provider.hpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_typed_mempool.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/expected.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/method_callback.hpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/ipc_channel.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/semaphore.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp
  iceoryx_utils/test/moduletests/test_cxx_expected.cpp
  iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp
Labels: bugfix

#582 iox-#542 creation pattern detailed doxygen docu
  iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp
Labels: documentation

#559 Iox #521 improve codecov
  .codecov.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-test.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/sanitize.yml
  doc/website/advanced/installation-guide-for-contributors.md
  iceoryx_meta/build_options.cmake
  iceoryx_meta/tests.cmake
  iceoryx_posh/test/moduletests/test_compatibility_check_level.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_monitoringmode_logstream.cpp
  iceoryx_utils/CMakeLists.txt
  tools/add_test_users.sh
  tools/gcov/lcov_generate.sh
  tools/iceoryx_build_test.sh
  tools/run_tests.sh
Labels: tooling
