Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-07, with the labels that each got.

#874 iox-#743 Add graphic showing polling alternatives to docu
  doc/website/getting-started/overview.md
  doc/website/images/avoid-polling.svg
Labels: documentation

#863 Iox #27 client port implementation and test part 2
  doc/design/diagrams/request_response/client_and_server_service_discovery.puml
  doc/design/diagrams/request_response/client_and_server_service_discovery.svg
  doc/design/diagrams/request_response/client_port.puml
  doc/design/diagrams/request_response/client_port.svg
  doc/design/diagrams/request_response/client_state_machine.puml
  doc/design/diagrams/request_response/client_state_machine.svg
  doc/design/request_response_communication.md
  iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logger.hpp
  iceoryx_hoofs/source/error_handling/error_handling.cpp
  iceoryx_hoofs/source/log/logger.cpp
  iceoryx_hoofs/test/moduletests/test_logger.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.inl
  iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.hpp
  iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.inl
  iceoryx_posh/include/iceoryx_posh/internal/log/posh_logging.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_user.hpp
  iceoryx_posh/source/log/posh_logging.cpp
  iceoryx_posh/source/popo/ports/client_port_data.cpp
  iceoryx_posh/source/popo/ports/client_port_roudi.cpp
  iceoryx_posh/source/popo/ports/client_port_user.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
Labels: enhancement, test

#882 iox-#529 Remove define private public from test_objectpool
  iceoryx_hoofs/include/iceoryx_hoofs/internal/objectpool/objectpool.hpp
  iceoryx_hoofs/test/moduletests/test_objectpool.cpp
Labels: refactoring
