Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-05, with the labels that each got.

#766 iox-#765 list stl dependencies with bash script
  tools/list_stl_dependencies.sh
Labels: tooling

#772 iox-#33 add installation guide for Windows
  doc/website/getting-started/installation.md
Labels: documentation

#758 Iox #409 axivion analysis on CI
  .github/workflows/axivion.yml
  CONTRIBUTING.md
  tools/axivion/axivion_config.json
  tools/axivion/trigger_pipeline.py
  tools/axivion/wait_for_pipeline.py
Labels: Axivion, tooling

#773 iox-#425 Update and align quality levels with ROS quality levels
  CONTRIBUTING.md
  README.md
Labels: documentation

#787 Iox #590 plantuml in design documentation
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/design/README.md
  doc/design/diagrams/puml_github_workflow.puml
  doc/design/diagrams/puml_github_workflow.svg
  tools/generate_plantuml_svg.sh
Labels: tooling

#767 Iox #260 refactor std converter methods to cxx converter
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/integrationtests/service_discovery/test_roudi_findservice.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/convert.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/convert.inl
  iceoryx_utils/include/iceoryx_utils/log/logstream.hpp
  iceoryx_utils/test/moduletests/test_cxx_convert.cpp
  iceoryx_utils/test/moduletests/test_logstream.cpp
  iceoryx_utils/test/moduletests/test_semaphore_module.cpp
  iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark.hpp
  iceoryx_utils/testing/timing_test.cpp
Labels: refactoring

#792 iox-#791 do not build cpptoml examples
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
Labels: bugfix

#783 Iox #350 listener design document
  doc/design/draft/eventdriven-callbacks.md
  doc/design/listener.md
Labels: documentation

#643 Iox #583 clean up doxygen in dds
  iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_reader.hpp
  iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_writer.hpp
  iceoryx_dds/include/iceoryx_dds/dds/data_reader.hpp
  iceoryx_dds/include/iceoryx_dds/dds/data_writer.hpp
  iceoryx_dds/include/iceoryx_dds/gateway/dds_to_iox.hpp
  iceoryx_dds/include/iceoryx_dds/gateway/iox_to_dds.hpp
Labels: documentation

#802 iox-#736 Use clang-10 in Github CI Sanitize workflow
  .github/workflows/sanitize.yml
Labels: bugfix

#797 iox-#33 posix mutex support in windows
  .clang-tidy
  .github/workflows/build-test.yml
  iceoryx_examples/waitset/ice_waitset_basic.cpp
  iceoryx_hoofs/cmake/IceoryxPlatform.cmake
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/win/source/pthread.cpp
  iceoryx_hoofs/platform/win/source/semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
  iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp
  iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
Labels: enhancement

#804 iox-#654 stop flooding output if there is an outdated socket
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
Labels: bugfix

#807 Iox #805 enhance posix call
  cmake/googletest/CMakeLists.txt
  iceoryx_examples/iceperf/mq.cpp
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/source/posix_wrapper/message_queue.cpp
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
  iceoryx_hoofs/source/posix_wrapper/semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp
  iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
Labels: enhancement, refactoring

#809 Iox #33 implement signal handler for windows 10
  .github/workflows/build-test.yml
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/signal.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/win32_errorHandling.hpp
  iceoryx_hoofs/platform/win/source/mman.cpp
  iceoryx_hoofs/platform/win/source/pthread.cpp
  iceoryx_hoofs/platform/win/source/semaphore.cpp
  iceoryx_hoofs/platform/win/source/signal.cpp
  iceoryx_hoofs/platform/win/source/time.cpp
  iceoryx_hoofs/platform/win/source/unistd.cpp
  iceoryx_hoofs/platform/win/source/win32_errorHandling.cpp
Labels: enhancement

#769 iox-#768 Backport: Add missing template parameter for user-header to typed C++ API
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
Labels: bugfix

#806 backport of iox-#654, iox-#791, iox-#802 and iox-#808 to release branch
  .github/workflows/sanitize.yml
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/base_relative_pointer.hpp
  iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/pointer_repository.hpp
  iceoryx_utils/source/posix_wrapper/file_lock.cpp
  iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
Labels: bugfix

#799 iox-#486 Add git commit hooks
  .clang-format
  CONTRIBUTING.md
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.hpp
  doc/website/advanced/installation-guide-for-contributors.md
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  tools/git-hooks/Readme.md
  tools/git-hooks/commit-msg
  tools/git-hooks/pre-commit
  tools/git-hooks/prepare-commit-msg
Labels: tooling

#810 Iox #33 relative pointer & posix threads for windows
  .github/workflows/build-test.yml
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/win/source/pthread.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
Labels: enhancement

#514 Iox #496 improve coverage and refactor moduletests for mepoo componenet
  iceoryx_posh/test/moduletests/test_mepoo_config.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_chunk.cpp
Labels: test

#822 iox-#821 Fix incremental builds with script
  cmake/googletest/0001-remove-werror-from-build-flags.patch
  cmake/googletest/CMakeLists.txt
  iceoryx_dds/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/cpptoml.cmake.in
Labels: bugfix

#826 iox-#825 update ROS setup in Github CI
  .github/workflows/integrationtest.yml
Labels: bugfix

#827 [Backport release-1.0] iox-#825 update ROS setup in Github CI
  .github/workflows/integrationtest.yml
Labels: bugfix
