Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-03, with the labels that each got.

#589 iox-#14 rename test_mepoo_handler.cpp to test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
Labels: refactoring

#578 iox-#549 Add requirement for 64-bit system and warning on 32-bit systems
  doc/website/getting-started/installation.md
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/helplets.hpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: documentation

#592 iox-#591 Added void_t to type_traits
  iceoryx_utils/include/iceoryx_utils/cxx/type_traits.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl
  iceoryx_utils/test/moduletests/test_cxx_type_traits.cpp
Labels: bugfix

#586 Iox #349 add subscriber process to introspection
  iceoryx_examples/icecrystal/Readme.md
  tools/introspection/source/introspection_app.cpp
Labels: enhancement

#580 Iox #408 transition to 1 0 c api
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/include/iceoryx_binding_c/chunk.h
  iceoryx_binding_c/include/iceoryx_binding_c/enums.h
  iceoryx_binding_c/include/iceoryx_binding_c/publisher.h
  iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h
  iceoryx_binding_c/source/c_chunk.cpp
  iceoryx_binding_c/source/c_publisher.cpp
  iceoryx_binding_c/source/c_subscriber.cpp
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_dds/include/iceoryx_dds/internal/gateway/dds_to_iox.inl
  iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icedelivery_in_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
  iceoryx_examples/iceperf/iceoryx.cpp
  iceoryx_examples/iceperf/iceoryx_c.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_publisher.c
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/popo/untyped_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp
  iceoryx_posh/source/popo/ports/subscriber_port_user.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/mocks/subscriber_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_subscriber.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: refactoring

#584 Iox #408 offer and subscribe on create
  iceoryx_binding_c/include/iceoryx_binding_c/publisher.h
  iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h
  iceoryx_binding_c/source/c_publisher.cpp
  iceoryx_binding_c/source/c_subscriber.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_examples/ice_multi_publisher/README.md
  iceoryx_examples/ice_multi_publisher/ice_multi_publisher.cpp
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery/iox_publisher.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_publisher_with_options.cpp
  iceoryx_examples/icedelivery/iox_subscriber.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber_with_options.cpp
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icedelivery_in_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
  iceoryx_examples/iceperf/iceoryx.cpp
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_publisher.c
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp
  iceoryx_posh/source/popo/ports/publisher_port_data.cpp
  iceoryx_posh/source/popo/ports/publisher_port_roudi.cpp
  iceoryx_posh/source/popo/ports/subscriber_port_data.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
Labels: enhancement

#564 Iox #454 enhance cmd line parser tests
  iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp
  iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser_config_file_option.cpp
Labels: test

#595 Iox #350 rename active call set into listener
  iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/event_listener.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/event_notifier.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/event_variable_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl
  iceoryx_posh/include/iceoryx_posh/popo/event_attorney.hpp
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/source/popo/building_blocks/event_listener.cpp
  iceoryx_posh/source/popo/building_blocks/event_notifier.cpp
  iceoryx_posh/source/popo/listener.cpp
  iceoryx_posh/test/moduletests/test_popo_event_variable.cpp
  iceoryx_posh/test/moduletests/test_popo_listener.cpp
Labels: refactoring

#602 iox-#599 check callables of-expected and then or else
  iceoryx_utils/include/iceoryx_utils/cxx/function_ref.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/type_traits.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl
  iceoryx_utils/test/moduletests/test_cxx_expected.cpp
  iceoryx_utils/test/moduletests/test_cxx_type_traits.cpp
Labels: bugfix

#540 Initial Integrationtest Framework
  .codecov.yml
  .github/workflows/integrationtest.yml
  .gitignore
  README.md
  iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
  iceoryx_examples/icedelivery/iox_publisher.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_publisher_with_options.cpp
  iceoryx_examples/icedelivery/iox_subscriber.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber_with_options.cpp
  iceoryx_examples/icedelivery_in_c/CMakeLists.txt
  iceoryx_examples/icedelivery_in_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
  iceoryx_examples/iceperf/mq.hpp
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_examples/waitset_in_c/CMakeLists.txt
  iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_publisher.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_sync.c
  iceoryx_integrationtest/CMakeLists.txt
  iceoryx_integrationtest/Readme.md
  iceoryx_integrationtest/iceoryx_integrationtest/test_callback_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_icedelivery_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_icedelivery_in_c_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_multi_publisher_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_roudi_startup_shutdown.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_singleprocess_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_in_c_example.py
  iceoryx_integrationtest/package.xml
  iceoryx_utils/cmake/IceoryxPlatform.cmake
  tools/gcov/lcov_generate.sh
Labels: test

#597 Iox #495 bugfix gcc 5 compatibility
  cmake/cpptoml/CMakeLists.txt
  cmake/cyclonedds/CMakeLists.txt
  cmake/googletest/CMakeLists.txt
  doc/website/getting-started/installation.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_meta/build_options.cmake
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl
  iceoryx_utils/source/cxx/deadline_timer.cpp
  tools/iceoryx_build_test.sh
Labels: refactoring

#516 iox-#496 improvre coverage for class port_pool in roudi folder
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
Labels: test

#587 Iox #454 create test file for iceoryx roudi and roudi app
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
Labels: test

#610 iox-#609 Add generic QNX 7.0 toolchain files
  doc/website/getting-started/installation.md
  tools/toolchains/qnx/qnx_sdp70_aarch64le.cmake
  tools/toolchains/qnx/qnx_sdp70_common.cmake
  tools/toolchains/qnx/qnx_sdp70_x86_64.cmake
Labels: tooling

#598 Iox #404 Extend timeout registration info and send termination request on destruction
  iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_creator.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/process.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/source/runtime/ipc_interface_creator.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
  iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.inl
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_utils/test/moduletests/test_ipc_channel.cpp
Labels: bugfix

#629 Iox #14 refactor chunk settings into struct
  iceoryx_binding_c/test/moduletests/test_event_info.cpp
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_dds/test/mocks/chunk_mock_dds.hpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_settings.hpp
  iceoryx_posh/source/mepoo/chunk_header.cpp
  iceoryx_posh/source/mepoo/chunk_settings.cpp
  iceoryx_posh/source/mepoo/memory_manager.cpp
  iceoryx_posh/test/mocks/chunk_mock.hpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_chunk.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_pointer.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/expected.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/helplets.hpp
  iceoryx_utils/test/moduletests/test_cxx_helplets.cpp
Labels: refactoring

#608 Iox #495 add gcc 5.4 and latest clang ci job
  .codecov.yml
  .github/workflows/build-test.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/experimental_build.yml
  doc/aspice_swe3_4/example/iceoryx_component/include/example_component.hpp
  doc/aspice_swe3_4/example/iceoryx_component/include/example_module/example_derived_class.hpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.cpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.hpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.inl
  doc/aspice_swe3_4/example/iceoryx_component/test/moduletests/test_example_base_class.cpp
  iceoryx_utils/test/moduletests/test_posix_mutex.cpp
  tools/iceoryx_build_test.sh
  tools/run_tests.sh
Labels: tooling

#642 Iox #622 toml parser exceptions will crash roudi
  iceoryx_dds/source/dds2iceoryx_app/main.cpp
  iceoryx_dds/source/iceoryx2dds_app/main.cpp
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_config_file_provider.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/roudi/application/roudi_main.cpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
  iceoryx_posh/test/CMakeLists.txt
  iceoryx_posh/test/input/popo_toml_gateway_error_incomplete_configuration.toml
  iceoryx_posh/test/input/roudi_config_error_invalid_version.toml
  iceoryx_posh/test/input/roudi_config_error_max_mempools_exceeded.toml
  iceoryx_posh/test/input/roudi_config_error_max_segments_exceeded.toml
  iceoryx_posh/test/input/roudi_config_error_mempool_without_chunk_count.toml
  iceoryx_posh/test/input/roudi_config_error_mempool_without_chunk_size.toml
  iceoryx_posh/test/input/roudi_config_error_no_general.toml
  iceoryx_posh/test/input/roudi_config_error_no_segments.toml
  iceoryx_posh/test/input/roudi_config_error_segment_without_mempool.toml
  iceoryx_posh/test/input/toml_parser_exception.toml
  iceoryx_posh/test/moduletests/test_input_path.hpp.in
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_roudi_config_toml_file_provider.cpp
Labels: bugfix

#631 Iox #482 Add example overview to website
  CONTRIBUTING.md
  doc/website/.pages
  doc/website/getting-started/examples/.pages
  doc/website/getting-started/examples/advanced-examples.md
  doc/website/getting-started/examples/basic-examples.md
  doc/website/getting-started/examples/callbacks.md
  doc/website/getting-started/examples/callbacks_in_c.md
  doc/website/getting-started/examples/icecrystal.md
  doc/website/getting-started/examples/icecubetray.md
  doc/website/getting-started/examples/icedelivery.md
  doc/website/getting-started/examples/icedelivery_in_c.md
  doc/website/getting-started/examples/iceensemble.md
  doc/website/getting-started/examples/icehello.md
  doc/website/getting-started/examples/iceoptions.md
  doc/website/getting-started/examples/iceperf.md
  doc/website/getting-started/examples/index.md
  doc/website/getting-started/examples/intermediate-examples.md
  doc/website/getting-started/examples/singleprocess.md
  doc/website/getting-started/examples/waitset.md
  doc/website/getting-started/examples/waitset_in_c.md
  iceoryx_examples/README.md
  mkdocs.yml
  tools/export-docu-to-website.sh
Labels: documentation

#627 iox-#625 removed hint for qnx since we are using /tmp/
  doc/website/getting-started/installation.md
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/file_lock.hpp
Labels: documentation

#639 Iox #623 use 8 byte type for chunk management pointer and add tests
  iceoryx_posh/include/iceoryx_posh/internal/popo/used_chunk_list.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/used_chunk_list.inl
  iceoryx_posh/test/moduletests/test_popo_listener.cpp
  iceoryx_posh/test/moduletests/test_popo_used_chunk_list.cpp
Labels: bugfix, technical debt, test

#651 iox-#650 generate the test_input_path.hpp file in the build folder
  iceoryx_posh/test/CMakeLists.txt
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_roudi_config_toml_file_provider.cpp
Labels: technical debt

#641 Iox #350 refactor has triggered in user trigger
  .clang-tidy
  iceoryx_binding_c/include/iceoryx_binding_c/types.h
  iceoryx_binding_c/include/iceoryx_binding_c/user_trigger.h
  iceoryx_binding_c/source/c_user_trigger.cpp
  iceoryx_binding_c/test/moduletests/test_user_trigger.cpp
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks_in_c/README.md
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_sync.cpp
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_examples/waitset_in_c/ice_c_waitset_sync.c
  iceoryx_posh/include/iceoryx_posh/internal/popo/trigger.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/include/iceoryx_posh/popo/trigger.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger_handle.hpp
  iceoryx_posh/include/iceoryx_posh/popo/user_trigger.hpp
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/source/popo/trigger.cpp
  iceoryx_posh/source/popo/trigger_handle.cpp
  iceoryx_posh/source/popo/user_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_trigger_handle.cpp
  iceoryx_posh/test/moduletests/test_popo_user_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
Labels: refactoring

#635 Iox #14 custom header for typed api
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/sample.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/sample.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
  iceoryx_posh/test/mocks/chunk_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_publisher.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber.cpp
  iceoryx_utils/include/iceoryx_utils/cxx/type_traits.hpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
  iceoryx_utils/test/moduletests/test_cxx_type_traits.cpp
  tools/introspection/source/introspection_app.cpp
Labels: enhancement

#630 Iox #482 rework installation manuals
  CONTRIBUTING.md
  doc/conceptual-guide.md
  doc/website/advanced/configuration-guide.md
  doc/website/advanced/installation-guide-for-contributors.md
  doc/website/advanced/usage-guide.md
  doc/website/getting-started/installation.md
  doc/website/getting-started/overview.md
  iceoryx_posh/cmake/iceoryx_posh_deployment.cmake
  mkdocs.yml
  tools/export-docu-to-website.sh
  tools/toolchains/qnx/qnx_sdp70_common.cmake
Labels: documentation

#662 Iox #653 fix roudi crash when replying to dead app
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/package.xml
  iceoryx_posh/source/roudi/process.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
Labels: bugfix
