Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-08, with the labels that each got.

#872 Iox #736 remove idlpp-cxx dependency from dds gateway
  .github/workflows/build-test.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/experimental_build.yml
  .github/workflows/sanitize.yml
  CHANGELOG.md
  NOTICE.md
  cmake/cyclonedds/CMakeLists.txt
  cmake/cyclonedds/cyclonedds-cxx.cmake.in
  cmake/cyclonedds/cyclonedds.cmake.in
  cmake/cyclonedds/idlpp-cxx.cmake.in
  doc/3rd_party_licenses/idlpp-cxx/LICENSE
  doc/website/getting-started/installation.md
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/README.md
  iceoryx_dds/cmake/idlpp-cxx-generate.cmake.in
  iceoryx_dds/examples/docker/publisher_node.entrypoint
  iceoryx_dds/examples/docker/simple_internode_communication.yml
  iceoryx_dds/examples/docker/subscriber_node.entrypoint
  iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_reader.hpp
  iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_writer.hpp
  iceoryx_dds/source/iceoryx_dds/dds/cyclone_data_writer.cpp
  iceoryx_dds/test/moduletests/test_cyclone_data_reader.cpp
  iceoryx_posh/CMakeLists.txt
  tools/docker/Dockerfile
Labels: bugfix

#883 iox-#529 Remove define private from mepoo test
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
Labels: technical debt

#888 Add clang format ci job
  .github/workflows/build-test.yml
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/test/moduletests/test_static_storage.cpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/source/capro/service_description.cpp
  tools/check_formatting.sh
Labels: tooling

#893 iox-#887 Fix improperly formatted test_posh_mepoo.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
Labels: refactoring

#579 iox-#496 enhancing coverage for gateway Base and toml gateway config parser class for folder gateway
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
Labels: test

#892 Consolidate jobs in one workflow
  .github/workflows/build-test.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/experimental_build.yml
  .github/workflows/integrationtest.yml
  .github/workflows/sanitize.yml
  tools/ci/build-test-macos-with-sanitizers.sh
  tools/ci/build-test-macos.sh
  tools/ci/build-test-ubuntu-with-gcc54.sh
  tools/ci/build-test-ubuntu-with-latest-clang.sh
  tools/ci/build-test-ubuntu-with-sanitizers.sh
  tools/ci/build-test-ubuntu.sh
  tools/ci/build-test-windows.ps1
  tools/ci/coverage-and-docs.sh
  tools/ci/run-integration-test.sh
Labels: refactoring, tooling

#904 iox-#903 timed{send,receive} supported in mac os
  CHANGELOG.md
  iceoryx_hoofs/platform/mac/source/socket.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
Labels: enhancement

#909 iox-#905 libcxx support for clang
  CHANGELOG.md
  cmake/cyclonedds/CMakeLists.txt
  cmake/googletest/CMakeLists.txt
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp
  tools/iceoryx_build_test.sh
Labels: bugfix

#860 Iox #415 Make `ServiceRegistry` aware of complete `ServiceDescription`
  CHANGELOG.md
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_roudi_findservice.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: refactoring

#901 iox-#900 Gateway creates services with correct interface
  CHANGELOG.md
  cmake/cyclonedds/CMakeLists.txt
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/examples/docker/publisher_node.entrypoint
  iceoryx_dds/examples/docker/subscriber_node.entrypoint
  iceoryx_dds/source/gateway/main.cpp
  iceoryx_dds/source/iceoryx2dds_app/main.cpp
  iceoryx_dds/source/iceoryx_dds/dds/cyclone_data_reader.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/watch_dog.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_base.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/source/gateway/gateway_base.cpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/popo/ports/interface_port.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
  iceoryx_posh/test/mocks/gateway_base_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_interface_port.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  tools/ci/build-test-macos-with-sanitizers.sh
  tools/ci/build-test-macos.sh
Labels: bugfix
