Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-06, with the labels that each got.

#784 Iox #415 Add design decision document for service discovery
  doc/design/diagrams/service-discovery/overview-alternative-b.puml
  doc/design/diagrams/service-discovery/overview-alternative-b.svg
  doc/design/diagrams/service-discovery/overview-alternative-d.puml
  doc/design/diagrams/service-discovery/overview-alternative-d.svg
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-b.puml
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-b.svg
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-d.puml
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-d.svg
  doc/design/service-discovery.md
  doc/website/getting-started/overview.md
  iceoryx_examples/callbacks/README.md
Labels: documentation

#473 Iox #391 static memory alternative for std function
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl
  iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_type_traits.cpp
  iceoryx_hoofs/test/moduletests/test_static_storage.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl
Labels: enhancement

#840 Iox #449 prepare posh runtime for mock
  CONTRIBUTING.md
  doc/aspice_swe3_4/example/iceoryx_component/include/example_module/example_derived_class.hpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.hpp
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.inl
  doc/aspice_swe3_4/swe_docu_guidelines.md
  iceoryx_examples/iceperf/iceperf_leader.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/mutex.hpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime_single_process.hpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/source/runtime/posh_runtime_single_process.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/testing/roudi_environment/runtime_test_interface.cpp
  tools/iceoryx_build_test.sh
Labels: technical debt, test

#845 Iox #449 create posh runtime mock
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/testing/roudi_environment/runtime_test_interface.cpp
Labels: test

#843 Iox #842 cleanup memory provider and memory block
  iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_collection_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_segment_manager_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/port_pool_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/generic_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_provider.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp
  iceoryx_posh/source/roudi/memory/memory_block.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp
  iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp
  iceoryx_posh/source/roudi/memory/port_pool_memory_block.cpp
  iceoryx_posh/test/mocks/roudi_memory_block_mock.hpp
  iceoryx_posh/test/moduletests/test_roudi_generic_memory_block.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
Labels: technical debt

#849 iox-#743 Fix spelling mistakes in docu, adjust waitset examples
  doc/website/getting-started/installation.md
  iceoryx_examples/waitset/CMakeLists.txt
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_timer_driven_execution.cpp
  iceoryx_examples/waitset_in_c/CMakeLists.txt
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_examples/waitset_in_c/ice_c_waitset_timer_driven_execution.c
  iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_in_c_example.py
Labels: documentation

#852 Iox #415 Refactor Service Description Part1: Remove integers values
  iceoryx_binding_c/include/iceoryx_binding_c/service_description.h
  iceoryx_binding_c/source/cpp2c_service_description_translation.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_service_description_translation.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_posh/cmake/iceoryx_posh_deployment.cmake
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/popo/ports/interface_port_data.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/integrationtests/test_roudi_findservice.cpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_capro_message.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
Labels: refactoring

#850 Iox #828 port changelog from release branch and add release helper script
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  VERSION
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/package.xml
  iceoryx_dds/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/package.xml
  iceoryx_integrationtest/package.xml
  iceoryx_meta/CMakeLists.txt
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/package.xml
  tools/iceoryx_release.sh
  tools/introspection/CMakeLists.txt
Labels: documentation, tooling

#853 Iox #415 Refactor Service Description Part2: Remove c'tor with two args
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_roudi_findservice.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
Labels: refactoring

#862 iox-#777 Set CMAKE_INSTALL_RPATH only when shared library is built
  iceoryx_meta/CMakeLists.txt
Labels: bugfix

#819 Iox #27 request response design document
  doc/design/diagrams/puml_github_workflow.puml
  doc/design/diagrams/puml_github_workflow.svg
  doc/design/diagrams/request_response/client_and_server_options.puml
  doc/design/diagrams/request_response/client_and_server_options.svg
  doc/design/diagrams/request_response/client_port.puml
  doc/design/diagrams/request_response/client_port.svg
  doc/design/diagrams/request_response/overview_class.puml
  doc/design/diagrams/request_response/overview_class.svg
  doc/design/diagrams/request_response/request_response_header.puml
  doc/design/diagrams/request_response/request_response_header.svg
  doc/design/diagrams/request_response/server_port.puml
  doc/design/diagrams/request_response/server_port.svg
  doc/design/diagrams/request_response/typed_api.puml
  doc/design/diagrams/request_response/typed_api.svg
  doc/design/diagrams/request_response/untyped_api.puml
  doc/design/diagrams/request_response/untyped_api.svg
  doc/design/diagrams/service-discovery/overview-alternative-b.svg
  doc/design/diagrams/service-discovery/overview-alternative-d.svg
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-b.svg
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-d.svg
  doc/design/request_response_communication.md
  tools/generate_plantuml_svg.sh
Labels: documentation

#858 Iox #27 client port implementation and test part 1
  doc/design/diagrams/request_response/client_and_server_options.puml
  doc/design/diagrams/request_response/client_and_server_options.svg
  doc/design/diagrams/request_response/request_response_header.puml
  doc/design/diagrams/request_response/request_response_header.svg
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_server_port_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp
  iceoryx_posh/include/iceoryx_posh/popo/client_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/port_queue_policies.hpp
  iceoryx_posh/include/iceoryx_posh/popo/rpc_header.hpp
  iceoryx_posh/source/mepoo/chunk_header.cpp
  iceoryx_posh/source/popo/client_options.cpp
  iceoryx_posh/source/popo/ports/client_port_data.cpp
  iceoryx_posh/source/popo/ports/client_port_user.cpp
  iceoryx_posh/source/popo/rpc_header.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_popo_client_options.cpp
  iceoryx_posh/test/moduletests/test_popo_rpc_header.cpp
Labels: feature request

#864 Iox #415 Add generic constructor to `cxx::variant`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
Labels: enhancement

#866 iox-#865 Common puml file for common settings
  doc/design/README.md
  doc/design/diagrams/puml_github_workflow.puml
  doc/design/diagrams/request_response/client_and_server_options.puml
  doc/design/diagrams/request_response/client_and_server_options.svg
  doc/design/diagrams/request_response/client_port.puml
  doc/design/diagrams/request_response/client_port.svg
  doc/design/diagrams/request_response/overview_class.puml
  doc/design/diagrams/request_response/overview_class.svg
  doc/design/diagrams/request_response/request_response_header.puml
  doc/design/diagrams/request_response/request_response_header.svg
  doc/design/diagrams/request_response/server_port.puml
  doc/design/diagrams/request_response/server_port.svg
  doc/design/diagrams/request_response/typed_api.puml
  doc/design/diagrams/request_response/typed_api.svg
  doc/design/diagrams/request_response/untyped_api.puml
  doc/design/diagrams/request_response/untyped_api.svg
  doc/design/diagrams/service-discovery/overview-alternative-b.svg
  doc/design/diagrams/service-discovery/overview-alternative-d.svg
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-b.svg
  doc/design/diagrams/service-discovery/sequence-diagram-alternative-d.svg
  doc/iceoryx-plantuml-config.puml
  tools/generate_plantuml_svg.sh
Labels: documentation

#854 Iox #415 Refactor Service Description Part3: Restrict wildcard usage to searching only
  CHANGELOG.md
  iceoryx_dds/test/moduletests/test_iox_to_dds.cpp
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/popo/ports/interface_port_data.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_roudi_findservice.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: refactoring
