Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-01, with the labels that each got.

#416 iox-#285 add more codecov parser options
  .codecov.yml
  .github/workflows/build-test.yml
  .github/workflows/coverage_scan.yml
  CONTRIBUTING.md
  README.md
Labels: tooling

#342 iox-#240 addedintegration test for posh runtime
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/integrationtests/service_discovery/test_roudi_findservice.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
Labels: test

#476 Iox #467 move iceoryx into iceoryx eclipse org
  CONTRIBUTING.md
  GOVERNANCE.md
  NOTICE.md
  README.md
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/website/FAQ.md
  doc/website/getting-started/installation.md
  iceoryx_binding_c/include/iceoryx_binding_c/types.h
  tools/docker/README.md
Labels: documentation

#461 iox-#459 enable UndefinedBehaviorSanitizer for iceoryx
  .github/workflows/sanitize.yml
  README.md
  doc/website/getting-started/installation.md
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_utils/cmake/IceoryxPlatform.cmake
  tools/run_all_tests.sh
Labels: tooling

#481 Iox #136 First step towards a iceoryx.io website
  .gitignore
  README.md
  doc/aspice_swe3_4/CMakeLists.txt
  doc/conceptual-guide.md
  doc/design/error-handling.md
  doc/website/.pages
  doc/website/API-cheatsheet.md
  doc/website/FAQ.md
  doc/website/advanced/iceoryx_utils.md
  doc/website/advanced/installation-guide-for-contributors.md
  doc/website/advanced/usage-guide.md
  doc/website/api-references.md
  doc/website/for-developers/iceoryx_utils.md
  doc/website/getting-started/.pages
  doc/website/getting-started/examples.md
  doc/website/getting-started/examples/.pages
  doc/website/getting-started/examples/advanced-examples.md
  doc/website/getting-started/examples/basic-examples.md
  doc/website/getting-started/examples/intermediate-examples.md
  doc/website/getting-started/installation.md
  doc/website/getting-started/overview.md
  doc/website/index.md
  doc/website/introduction.md
  iceoryx_examples/README.md
  iceoryx_examples/icecrystal/Readme.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery_on_c/README.md
  iceoryx_examples/iceperf/README.md
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset_on_c/README.md
  iceoryx_utils/README.md
  mkdocs.yml
  tools/export-docu-to-website.sh
Labels: documentation

#466 Iox #163 add -Wconversion flag to strict build in productive code
  iceoryx_dds/source/dds2iceoryx_app/main.cpp
  iceoryx_dds/source/iceoryx2dds_app/main.cpp
  iceoryx_examples/icedelivery/iox_publisher_typed.cpp
  iceoryx_examples/icedelivery_on_c/sleep_for.h
  iceoryx_examples/iceperf/base.cpp
  iceoryx_examples/iceperf/base.hpp
  iceoryx_examples/iceperf/iceperf_laurel.cpp
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_examples/waitset_on_c/sleep_for.h
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/fixed_size_container.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/test/moduletests/test_fixed_size_container.cpp
  iceoryx_utils/cmake/IceoryxPlatform.cmake
  iceoryx_utils/include/iceoryx_utils/cxx/convert.hpp
  iceoryx_utils/include/iceoryx_utils/cxx/helplets.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/lockfree_queue/cyclic_index.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/lockfree_queue/cyclic_index.inl
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/trigger_queue.hpp
  iceoryx_utils/include/iceoryx_utils/internal/cxx/convert.inl
  iceoryx_utils/include/iceoryx_utils/internal/objectpool/objectpool.hpp
  iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/thread.hpp
  iceoryx_utils/platform/mac/include/iceoryx_utils/platform/signal.hpp
  iceoryx_utils/platform/mac/source/semaphore.cpp
  iceoryx_utils/source/posix_wrapper/message_queue.cpp
  iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_utils/source/posix_wrapper/system_configuration.cpp
  iceoryx_utils/source/posix_wrapper/thread.cpp
  iceoryx_utils/source/posix_wrapper/timer.cpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#469 Iox #285 iceoryx shared lib and debian package
  .github/workflows/build-test.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/sanitize.yml
  .gitignore
  cmake/package/package.cmake
  doc/conceptual-guide.md
  doc/website/advanced/installation-guide-for-contributors.md
  doc/website/advanced/usage-guide.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/cmake/idlpp-cxx-generate.cmake.in
  iceoryx_examples/iceperf/CMakeLists.txt
  iceoryx_examples/iceperf/roudi_main_static_config.cpp
  iceoryx_examples/singleprocess/CMakeLists.txt
  iceoryx_meta/CMakeLists.txt
  iceoryx_meta/build_options.cmake
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/install_help_and_config.cmake
  iceoryx_utils/CMakeLists.txt
  tools/iceoryx_build_test.sh
Labels: tooling

#487 iox-#454 improve coverage of class roudi memory provider, memory block and memory manager
  iceoryx_posh/test/moduletests/test_roudi_memory_block.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
Labels: test

#485 iox-#454 add new unit test for iceoryxRoudiMemoryManager class and up…
  iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/roudi_memory_interface.hpp
  iceoryx_posh/source/roudi/memory/iceoryx_roudi_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
Labels: test

#463 iox-#454 Added testcases for RoudiProcess class
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
Labels: test

#499 Iox #497 static build docu gcov
  CONTRIBUTING.md
  doc/website/advanced/installation-guide-for-contributors.md
  tools/iceoryx_build_test.sh
Labels: documentation

#510 Iox #509 build iceoryx static lib as default
  .github/workflows/build-test.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/sanitize.yml
  doc/website/advanced/installation-guide-for-contributors.md
  iceoryx_meta/build_options.cmake
  tools/iceoryx_build_test.sh
Labels: bugfix

#512 Iox #495 compile iceoryx on gcc 5
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
Labels: bugfix

#490 Iox #489 replace introspection threads with periodic task
  iceoryx_binding_c/source/c_user_trigger.cpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/popo/user_trigger.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/popo/user_trigger.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp
  iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.inl
  iceoryx_utils/test/moduletests/test_concurrent_periodic_task.cpp
Labels: refactoring

#492 Iox #454 improve coverage unit test mempool collection and mempool segment class
  iceoryx_posh/test/moduletests/test_roudi_iceoyx_roudi_memory_manager.cpp
Labels: test

#479 Iox #337 deprecate posix timer
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/message_queue_interface.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/cxx/deadline_timer.hpp
  iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp
  iceoryx_utils/source/cxx/deadline_timer.cpp
  iceoryx_utils/source/posix_wrapper/timer.cpp
  iceoryx_utils/test/moduletests/test_cxx_deadline_timer.cpp
  iceoryx_utils/test/moduletests/test_posix_mutex.cpp
  iceoryx_utils/test/moduletests/test_posix_timer.cpp
Labels: enhancement

#508 iox-#350 event based callbacks - design proposal
  doc/design/README.md
  doc/design/_template.md
  doc/design/draft/eventdriven-callbacks.md
Labels: documentation

#519 Iox #349 add nodename to pub sub options
  doc/website/getting-started/installation.md
  iceoryx_examples/ice_multi_publisher/ice_multi_publisher.cpp
  iceoryx_examples/ice_multi_publisher/ice_subscriber.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/introspection_types.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/popo/ports/application_port_data.cpp
  iceoryx_posh/source/popo/ports/base_port.cpp
  iceoryx_posh/source/popo/ports/base_port_data.cpp
  iceoryx_posh/source/popo/ports/client_port_data.cpp
  iceoryx_posh/source/popo/ports/interface_port_data.cpp
  iceoryx_posh/source/popo/ports/publisher_port_data.cpp
  iceoryx_posh/source/popo/ports/server_port_data.cpp
  iceoryx_posh/source/popo/ports/subscriber_port_data.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/mocks/publisher_mock.hpp
  iceoryx_posh/test/mocks/subscriber_mock.hpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp
  tools/introspection/source/introspection_app.cpp
Labels: enhancement

#500 Iox #498 remove unreachable code
  .github/workflows/build-test.yml
  .github/workflows/colcon.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/sanitize.yml
  iceoryx_binding_c/README.md
  iceoryx_posh/source/roudi/roudi_process.cpp
  iceoryx_utils/source/posix_wrapper/access_control.cpp
  iceoryx_utils/test/moduletests/test_file_reader.cpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#531 Iox #494 set MacOS Mojave in GitHub CI
  .github/workflows/build-test.yml
  .github/workflows/colcon.yml
  .github/workflows/coverage_doc.yml
  .github/workflows/sanitize.yml
Labels: tooling
