Repository eclipse-iceoryx/iceoryx, pull requests merged in 2021-11, with the labels that each got.

#928 iox-#926 Replace relocatable pointer implementation
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relocatable_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relocatable_pointer.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relocatable_ptr.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relocatable_ptr.inl
  iceoryx_hoofs/test/moduletests/test_relocatable_ptr.cpp
Labels: enhancement, technical debt

#958 iox-#960 Fix format string issues
  tools/introspection/source/introspection_app.cpp
Labels: bugfix

#957 iox-#961 Use Multi-Arch compliant install destinations
  CHANGELOG.md
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
Labels: tooling

#955 iox-#965-msvc2015-fix
  CHANGELOG.md
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/unistd.hpp
  iceoryx_hoofs/platform/win/source/socket.cpp
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/source/roudi/service_registry.cpp
Labels: bugfix

#969 iox-#968: Fix typos in goals/non-goals section
  CHANGELOG.md
  doc/goals-non-goals.md
Labels: documentation
