Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-05, with the labels that each got.

#1353 iox-#1352 ADLINK is now ZettaScale Technology
  README.md
Labels: documentation

#1356 Iox #208 add comparison between string and char
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  tools/scripts/ice_env.sh
Labels: enhancement

#1363 iox-#1362 Clarify documentation of optionals
  doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
Labels: documentation

#1366 iox-#1364 Add dep for idlc command to iceoryx_dds
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dds/CMakeLists.txt
Labels: bugfix

#1360 iox-#208 add append for char and std::string
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string_internal.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
Labels: enhancement

#1376 iox-#337 remove posix timer
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/timer.hpp
  iceoryx_hoofs/source/posix_wrapper/timer.cpp
  iceoryx_hoofs/test/moduletests/test_posix_timer.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/timing_test.hpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
Labels: refactoring

#1357 iox-#1287 setting rpath for all iceoryx targets
  .github/workflows/build-test.yml
  doc/aspice_swe3_4/example/iceoryx_component/CMakeLists.txt
  doc/website/getting-started/installation.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/test/CMakeLists.txt
  iceoryx_binding_c/test/moduletests/test_client.cpp
  iceoryx_binding_c/test/moduletests/test_runtime.cpp
  iceoryx_binding_c/test/moduletests/test_server.cpp
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/test/CMakeLists.txt
  iceoryx_examples/callbacks/CMakeLists.txt
  iceoryx_examples/callbacks_in_c/CMakeLists.txt
  iceoryx_examples/complexdata/CMakeLists.txt
  iceoryx_examples/ice_access_control/CMakeLists.txt
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery_in_c/CMakeLists.txt
  iceoryx_examples/icediscovery/CMakeLists.txt
  iceoryx_examples/icediscovery_in_c/CMakeLists.txt
  iceoryx_examples/icehello/CMakeLists.txt
  iceoryx_examples/iceoptions/CMakeLists.txt
  iceoryx_examples/iceperf/CMakeLists.txt
  iceoryx_examples/request_response/CMakeLists.txt
  iceoryx_examples/request_response_in_c/CMakeLists.txt
  iceoryx_examples/singleprocess/CMakeLists.txt
  iceoryx_examples/user_header/CMakeLists.txt
  iceoryx_examples/waitset/CMakeLists.txt
  iceoryx_examples/waitset_in_c/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
  iceoryx_hoofs/cmake/IceoryxPlatform.cmake
  iceoryx_hoofs/platform/CMakeLists.txt
  iceoryx_hoofs/platform/LICENSE
  iceoryx_hoofs/test/CMakeLists.txt
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/CMakeLists.txt
  iceoryx_hoofs/testing/CMakeLists.txt
  iceoryx_meta/CMakeLists.txt
  iceoryx_meta/build_options.cmake
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/test/CMakeLists.txt
  tools/ci/build-test-windows.ps1
  tools/ci/cmake-linter.sh
  tools/introspection/CMakeLists.txt
Labels: tooling
