Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-04, with the labels that each got.

#1310 Fix warning when building with CMake 3.23.
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
Labels: bugfix

#1312 Iox #1311 increase version to 2.0.1
  VERSION
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  doc/website/release-notes/iceoryx-v2-0-1.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/package.xml
  iceoryx_dds/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/package.xml
  iceoryx_integrationtest/package.xml
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber_impl.hpp
  iceoryx_posh/package.xml
  tools/introspection/CMakeLists.txt
Labels: documentation

#1309 iox-#1072 replace FAIL and SUCCEED with GTEST_FAIL and GTEST_SUCCEED
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_hoofs/test/moduletests/test_relocatable_ptr.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_options.cpp
  iceoryx_posh/test/moduletests/test_popo_server_options.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_options.cpp
Labels: technical debt

#1319 Iox #208 add clear method to string
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
Labels: enhancement

#1325 iox-#1323 Remove cpptoml patch and directly add missing include for release_2.0
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-2.md
  iceoryx_dds/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
Labels: bugfix

#1326 Iox #1323 remove cpptoml patch and fix cmake 3.23 warning for release 1.0
  CHANGELOG.md
  iceoryx_posh/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
Labels: bugfix

#1328 Iox #1323 Remove cpptoml patch and directly add missing include
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-2.md
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_dds/cmake/cpptoml/COLCON_IGNORE
  iceoryx_dds/cmake/cpptoml/cpptoml.cmake.in
  iceoryx_posh/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
Labels: bugfix

#1314 iox-#1099 add test for error handler mock
  iceoryx_hoofs/test/CMakeLists.txt
  iceoryx_hoofs/test/mocktests/test_error_handler_mock.cpp
  iceoryx_hoofs/test/mocktests/test_hoofs_mock.cpp
  iceoryx_meta/tests.cmake
  tools/ci/build-test-windows.ps1
Labels: test

#1219 iox-#1295 Rework `icediscovery` example
  iceoryx_examples/icediscovery/CMakeLists.txt
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery/include/discovery_blocking.hpp
  iceoryx_examples/icediscovery/iox_find_service.cpp
  iceoryx_examples/icediscovery/iox_offer_service.cpp
  iceoryx_examples/icediscovery_in_c/README.md
  iceoryx_examples/icediscovery_in_c/iox_c_find_service.c
  iceoryx_examples/icediscovery_in_c/iox_c_offer_service.c
  iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_in_c_example.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_monitoring.py
Labels: documentation

#1253 iox-#1252 Check QNX and C++ STL system headers against whitelist
  .github/workflows/build-test.yml
  CONTRIBUTING.md
  doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.hpp
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/cyclic_index.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/timer.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/semaphore.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger.hpp
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  tools/scripts/list_stl_dependencies.sh
  tools/scripts/used-headers.txt
Labels: tooling

#1316 Iox #1311 fix cmake 3.23.0 warnings master
  cmake/cyclonedds/CMakeLists.txt
  cmake/googletest/CMakeLists.txt
  tools/iceoryx_build_test.sh
Labels: bugfix

#1339 Fix FreeBSD CI build
  .github/workflows/build-test.yml
  .github/workflows/changelog.yml
  .github/workflows/lint_master.yml
  .github/workflows/lint_pull_request.yml
  .github/workflows/nightly.yml
  .github/workflows/release_build_publish.yml
  doc/website/release-notes/iceoryx-unreleased.md
Labels: bugfix
