Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-12, with the labels that each got.

#1810 iox-1394 fix AUTOSAR violations in variant_internal
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
Labels: AUTOSAR, globex

#1809 Iox 1781 fix ci warnings
  .github/workflows/lint_pull_request.yml
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/resizeable_lockfree_queue.inl
Labels: tooling

#1728 Iox #1394 fix axivion violation for expected hpp inl
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl
Labels: AUTOSAR

#1806 iox-#1394-fix-axivion-violation-for-vector
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
Labels: AUTOSAR

#1807 iox-#1394-fix-axivion-violation-for-uninitialized_array
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
Labels: AUTOSAR

#1797 iox-#1394-fix-axivion-violation-for-helplets
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/helplets.inl
Labels: AUTOSAR

#1825 iox-#1823 Fix double move in emplace
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
Labels: bugfix

#1827 iox-#1826 Use default roudi config file
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
Labels: bugfix

#1832 iox-#1394 Replace back-tick with single quote in hoofs
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/creation.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_common.hpp
Labels: Axivion

#1787 iox-1756 use iceoryx logger instead of output streams
  CONTRIBUTING.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/list.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/adaptive_wait.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/convert.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/list.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/memory/include/iox/unique_ptr.hpp
  iceoryx_hoofs/source/cxx/requires.cpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/allocator.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/source/posix_wrapper/signal_handler.cpp
  iceoryx_hoofs/source/posix_wrapper/system_configuration.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/source/units/duration.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_serialization.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
  iceoryx_hoofs/test/moduletests/test_logging.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_rights.cpp
  iceoryx_hoofs/test/moduletests/test_posix_allocator.cpp
  iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  iceoryx_hoofs/test/moduletests/test_posix_signal_handler.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_hoofs/test/moduletests/test_unit_duration.cpp
  iceoryx_hoofs/test/moduletests/test_unix_domain_sockets.cpp
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark.hpp
  iceoryx_hoofs/test/stresstests/sofi/test_stress_sofi.cpp
  iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/testing_logger.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/watch_dog.hpp
  iceoryx_hoofs/testing/testing_logger.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
Labels: refactoring
