Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-03, with the labels that each got.

#1180 iox-#743 improve contributing md
  CONTRIBUTING.md
Labels: documentation

#1181 iox-#743 Update integration test readme
  iceoryx_integrationtest/Readme.md
Labels: documentation

#1195 iox-#1192 clamp history request
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
Labels: bugfix

#1190 iox-#743 Validate complexdata example
  iceoryx_examples/complexdata/README.md
Labels: documentation

#1199 iox-#743 Validation of ice_access_control example
  iceoryx_examples/ice_access_control/CMakeLists.txt
  iceoryx_examples/ice_access_control/README.md
  iceoryx_examples/ice_access_control/roudi_main_static_segments.cpp
Labels: documentation

#1212 iox-#743 Make example table and navi consistent
  doc/website/examples/.pages
  doc/website/examples/request_response.md
  doc/website/examples/request_response_in_c.md
  iceoryx_examples/README.md
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response_in_c/README.md
Labels: documentation

#1191 iox-#734 Update hoofs readme for v2.0 release
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/design_pattern/action.hpp
  iceoryx_posh/test/moduletests/test_popo_client.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_client.cpp
Labels: documentation

#1015 iox-#743 Add QoS policy article
  doc/website/concepts/best-practice-for-testing.md
  doc/website/concepts/qos-policies.md
  iceoryx_examples/iceoptions/README.md
Labels: documentation

#1217 iox-#1216 enable unlock file functionality in windows platform
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/platform/win/source/file.cpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  tools/scripts/clang_tidy_check.sh
Labels: bugfix

#1210 iox-#743 Validation of icedelivery example
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery/iox_publisher.cpp
Labels: documentation

#1214 iox-#743 Validation of icedelivery_in_c example
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icedelivery_in_c/ice_c_publisher.c
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
Labels: documentation

#1224 iox-#1223 Fix dds gateway failure
  cmake/cyclonedds/cyclonedds-cxx.cmake.in
  cmake/cyclonedds/cyclonedds.cmake.in
  doc/website/release-notes/iceoryx-v2-0-0.md
Labels: bugfix

#1222 iox-#743 review docker example
  iceoryx_examples/icedocker/README.md
Labels: documentation

#1211 iox-#743 Rework and rename conceptual guide
  README.md
  doc/conceptual-guide.md
  doc/shared-memory-communication.md
  doc/website/advanced/configuration-guide.md
  doc/website/getting-started/overview.md
  doc/website/images/memory-segment-visualization.svg
  doc/website/images/shared-memory-mapping.svg
Labels: documentation

#1229 iox-#1218 Remove potential dangerous usage of storage in binding C tests
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_wait_set.cpp
Labels: technical debt

#1189 iox-#1194 Install includes to include/${PROJECT_NAME}
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_posh/CMakeLists.txt
Labels: enhancement

#1227 iox-#743 Add hint to iceperf example that it is only running on linux…
  iceoryx_examples/iceperf/README.md
Labels: documentation

#1228 iox-#743 Validation of waitset example
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset/ice_waitset_timer_driven_execution.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
Labels: documentation

#1242 iox-#743 Validation of iceoption example
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/iceoptions/iox_publisher_with_options.cpp
  iceoryx_examples/iceoptions/iox_subscriber_with_options.cpp
Labels: documentation, bugfix

#1240 iox-#1239 Fix string compiler warning
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
Labels: bugfix

#1235 iox-#743 Validation of request-response example
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response/client_cxx_waitset.cpp
Labels: documentation

#1245 iox-#743 example fixes
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_examples/callbacks_in_c/README.md
  iceoryx_examples/callbacks_in_c/ice_c_callbacks_subscriber.c
  iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
  iceoryx_examples/icediscovery_in_c/README.md
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/request_response_in_c/README.md
  iceoryx_examples/request_response_in_c/client_c_waitset.c
Labels: documentation, example

#1241 iox-#743 Validation of icehello example
  iceoryx_examples/icehello/README.md
Labels: documentation

#1234 iox-#743 review single process example
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
Labels: documentation

#1247 iox-#743 Validation of Best Practice for Testing
  doc/website/concepts/best-practice-for-testing.md
Labels: documentation

#1258 iox-#743 Validation of "How optional and error values are returned in iceoryx"
  doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md
Labels: documentation

#1263 iox-#743 Validation of "How optional and error values are returned in iceoryx"
  doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md
Labels: documentation

#1262 iox-#743 Validation of "Installation guide for contributors"
  doc/website/advanced/installation-guide-for-contributors.md
Labels: documentation

#1266 Iox #1264 threadsafe handle translator for windows
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/handle_translator.hpp
  iceoryx_hoofs/platform/win/source/handle_translator.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  tools/ci/build-test-windows.ps1
Labels: bugfix

#1251 iox-#743 Update planned features
  PLANNED_FEATURES.md
Labels: documentation

#1268 iox-#743 Validation of "Overview"
  doc/website/getting-started/overview.md
Labels: documentation

#1267 Iox #743 update goals non goals.md
  doc/goals-non-goals.md
Labels: documentation

#1272 iox-#1271 Make semaphore/mutex creation threadsafe in windows platform
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/ipc_handle_manager.hpp
  iceoryx_hoofs/platform/win/source/ipc_handle_manager.cpp
  iceoryx_hoofs/platform/win/source/pthread.cpp
  iceoryx_hoofs/platform/win/source/semaphore.cpp
  iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp
Labels: bugfix

#1273 iox-#743 Update top level README.md
  README.md
Labels: documentation

#1276 iox-#743 Validation of "What is iceoryx"
  doc/website/getting-started/what-is-iceoryx.md
Labels: documentation

#1250 iox-#1249 Fix tests on QNX
  iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/platform_settings.hpp
  iceoryx_hoofs/test/moduletests/test_concurrent_smart_lock.cpp
  iceoryx_hoofs/test/moduletests/test_semaphore_module.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime_single_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp
Labels: bugfix

#1254 iox-#743 Set all documentation links to `v2.0.0`
  CONTRIBUTING.md
  NOTICE.md
  QUALITY_DECLARATION.md
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/design/README.md
  doc/shared-memory-communication.md
  doc/website/.pages
  doc/website/FAQ.md
  doc/website/advanced/configuration-guide.md
  doc/website/advanced/installation-guide-for-contributors.md
  doc/website/concepts/architecture.md
  doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md
  doc/website/examples/icediscovery_in_c.md
  doc/website/getting-started/installation.md
  doc/website/getting-started/overview.md
  doc/website/overrides/partials/footer.html
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks_in_c/README.md
  iceoryx_examples/complexdata/README.md
  iceoryx_examples/ice_access_control/README.md
  iceoryx_examples/icecrystal/Readme.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery_in_c/README.md
  iceoryx_examples/icedocker/README.md
  iceoryx_examples/iceensemble/README.md
  iceoryx_examples/icehello/README.md
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/iceperf/README.md
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response_in_c/README.md
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/user_header/README.md
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_hoofs/README.md
Labels: documentation

#1255 iox-#743 Set documentation links to `latest`/`master`
  QUALITY_DECLARATION.md
  iceoryx_examples/complexdata/README.md
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/request_response/README.md
Labels: documentation

#1282 iox-#743 Review configuration guide
  doc/website/advanced/configuration-guide.md
Labels: documentation

#1289 iox-#743 Fixes to make docs exportable (`v2.x`)
  doc/website/.pages
  doc/website/getting-started/overview.md
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-0.md
Labels: documentation

#1290 iox-#743 Fixes to make docs exportable (`master`)
  doc/website/.pages
  doc/website/getting-started/overview.md
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-0.md
Labels: documentation

#1288 iox-#743 Add links to new asciinema recordings (`v2.x`)
  iceoryx_examples/icecrystal/Readme.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery_in_c/README.md
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response_in_c/README.md
Labels: documentation

#1296 iox-#1295 Fix request response example
  iceoryx_examples/request_response/CMakeLists.txt
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response/server_cxx_untyped.cpp
Labels: example

#1297 Iox #1294 markdown link verification script
  .github/workflows/build-test.yml
  CONTRIBUTING.md
  QUALITY_DECLARATION.md
  README.md
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/design/README.md
  doc/design/draft/service-discovery.md
  doc/design/listener.md
  doc/shared-memory-communication.md
  doc/website/FAQ.md
  doc/website/advanced/configuration-guide.md
  doc/website/advanced/installation-guide-for-contributors.md
  doc/website/concepts/architecture.md
  doc/website/concepts/best-practice-for-testing.md
  doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md
  doc/website/concepts/qos-policies.md
  doc/website/getting-started/installation.md
  doc/website/getting-started/overview.md
  doc/website/getting-started/what-is-iceoryx.md
  doc/website/release-notes/iceoryx-unreleased.md
  doc/website/release-notes/iceoryx-v1-0-0.md
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks_in_c/README.md
  iceoryx_examples/complexdata/README.md
  iceoryx_examples/ice_access_control/README.md
  iceoryx_examples/icecrystal/Readme.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery_in_c/README.md
  iceoryx_examples/icedocker/README.md
  iceoryx_examples/iceensemble/README.md
  iceoryx_examples/icehello/README.md
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/iceperf/README.md
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response_in_c/README.md
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/user_header/README.md
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_hoofs/README.md
  tools/ci/markdown-link-verificator.sh
Labels: documentation, technical debt
