Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-01, with the labels that each got.

#993 iox-#992 Add templated from/into free functions for conversions
  CHANGELOG.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/helplets.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_type_traits.cpp
Labels: enhancement

#1008 Iox #989 handle deserialization errors for publisher and subscriber options
  CHANGELOG.md
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp
  iceoryx_posh/source/popo/publisher_options.cpp
  iceoryx_posh/source/popo/subscriber_options.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_options.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_options.cpp
Labels: bugfix

#1011 Iox #1010 unique id class
  CHANGELOG.md
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_id.hpp
  iceoryx_hoofs/source/cxx/unique_id.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_unique_id.cpp
Labels: enhancement

#991 Iox #954 use cxx::expected for MemoryManager::getChunk
  CHANGELOG.md
  iceoryx_binding_c/include/iceoryx_binding_c/enums.h
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_notification_info.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/source/mepoo/memory_manager.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_used_chunk_list.cpp
Labels: refactoring

#1006 Iox #841 upgrade gtest gmock to v1.10
  CHANGELOG.md
  CONTRIBUTING.md
  cmake/googletest/0001-remove-werror-from-build-flags.patch
  cmake/googletest/googletest.cmake.in
  doc/website/advanced/best-practice-for-testing.md
  iceoryx_hoofs/test/integrationtests/test_lockfree_queue_stresstest.cpp
  iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_trigger_queue.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  iceoryx_hoofs/test/moduletests/test_index_queue.cpp
  iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp
  iceoryx_hoofs/test/moduletests/test_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_lockfree_queue_buffer.cpp
  iceoryx_hoofs/test/moduletests/test_lockfree_queue_cyclic_index.cpp
  iceoryx_hoofs/test/moduletests/test_logger.cpp
  iceoryx_hoofs/test/moduletests/test_logstream.cpp
  iceoryx_hoofs/test/moduletests/test_posix_signal_handler.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_hoofs/test/moduletests/test_relocatable_ptr.cpp
  iceoryx_hoofs/test/moduletests/test_resizeable_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_semaphore_module.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/mocks/roudi_memory_block_mock.hpp
  iceoryx_posh/test/mocks/roudi_memory_provider_mock.hpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_popo_typed_unique_id.cpp
  iceoryx_posh/test/moduletests/test_roudi_config_toml_file_provider.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_block.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
Labels: refactoring, test, technical debt

#1004 Iox #987 remove the requirement of invalid state from cxx expected
  CHANGELOG.md
  doc/website/advanced/how-optional-and-error-values-are-returned-in-iceoryx.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_typed_mempool.cpp
Labels: refactoring

#1005 Iox #987 remove invalid state value from enums
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_dds/include/iceoryx_dds/dds/data_reader.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/method_callback.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/access_control.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/ipc_channel.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/semaphore.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/timer.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_posh/include/iceoryx_posh/gateway/channel.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_generic.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/toml_gateway_config_parser.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_pointer.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_settings.hpp
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_provider.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_config_file_provider.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
Labels: refactoring

#1019 iox-#1013 Split iceoryx_platform cmake code into own file
  CHANGELOG.md
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/platform/CMakeLists.txt
Labels: bugfix, refactoring

#1022 Add unique test id's to C binding tests
  iceoryx_binding_c/test/moduletests/test_c2cpp_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_chunk.cpp
  iceoryx_binding_c/test/moduletests/test_config.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_service_description_translation.cpp
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_log.cpp
  iceoryx_binding_c/test/moduletests/test_node.cpp
  iceoryx_binding_c/test/moduletests/test_notification_info.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_runtime.cpp
  iceoryx_binding_c/test/moduletests/test_service_description.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_binding_c/test/moduletests/test_types.cpp
  iceoryx_binding_c/test/moduletests/test_user_trigger.cpp
  iceoryx_binding_c/test/moduletests/test_wait_set.cpp
  tools/ci/build-ubuntu-with-latest-clang-gcc.sh
Labels: refactoring

#997 iox-#415 Move discovery-related methods to `ServiceDiscovery` class
  CHANGELOG.md
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
Labels: refactoring

#789 Iox #590 Add component diagram for upcoming iceoryx release
  CONTRIBUTING.md
  README.md
  doc/design/diagrams/iceoryx_components_diagram_nextgen_release.puml
  doc/design/diagrams/iceoryx_components_diagram_nextgen_release.svg
  iceoryx_posh/CMakeLists.txt
  tools/scripts/analyse_blacklisted_namespaces_in_binary.sh
  tools/scripts/print_all_namespace.sh
Labels: documentation

#1000 iox-#999 The posixCall must use the return value of the mutex functio…
  CHANGELOG.md
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
Labels: bugfix

#994 Iox #973 implement wait for termination request
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp
  iceoryx_examples/callbacks/ice_callbacks_publisher.cpp
  iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
  iceoryx_examples/complexdata/iox_publisher_complexdata.cpp
  iceoryx_examples/complexdata/iox_publisher_vector.cpp
  iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp
  iceoryx_examples/complexdata/iox_subscriber_vector.cpp
  iceoryx_examples/ice_access_control/README.md
  iceoryx_examples/ice_access_control/iox_cheeky_app.cpp
  iceoryx_examples/ice_access_control/iox_display_app.cpp
  iceoryx_examples/ice_access_control/iox_radar_app.cpp
  iceoryx_examples/ice_access_control/roudi_main_static_segements.cpp
  iceoryx_examples/icedelivery/iox_publisher.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icehello/README.md
  iceoryx_examples/icehello/iox_publisher_helloworld.cpp
  iceoryx_examples/icehello/iox_subscriber_helloworld.cpp
  iceoryx_examples/icehello/topic_data.hpp
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/iceoptions/iox_publisher_with_options.cpp
  iceoryx_examples/iceoptions/iox_subscriber_with_options.cpp
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/user_header/README.md
  iceoryx_examples/user_header/publisher_cxx_api.cpp
  iceoryx_examples/user_header/publisher_untyped_cxx_api.cpp
  iceoryx_examples/user_header/subscriber_cxx_api.cpp
  iceoryx_examples/user_header/subscriber_untyped_cxx_api.cpp
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_basic.cpp
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_examples/waitset/ice_waitset_timer_driven_execution.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/signal_watcher.hpp
  iceoryx_hoofs/source/posix_wrapper/signal_watcher.cpp
  iceoryx_hoofs/test/moduletests/test_posix_signal_watcher.cpp
  iceoryx_integrationtest/iceoryx_integrationtest/test_singleprocess_example.py
Labels: enhancement

#1025 Iox #415 remove offer from service discovery
  CHANGELOG.md
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
Labels: refactoring

#894 Iox #27 server port implementation preparatory
  doc/design/diagrams/request_response/request_response_header.puml
  doc/design/diagrams/request_response/request_response_header.svg
  doc/design/request_response_communication.md
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/popo/port_queue_policies.hpp
  iceoryx_posh/include/iceoryx_posh/popo/rpc_header.hpp
  iceoryx_posh/include/iceoryx_posh/popo/server_options.hpp
  iceoryx_posh/source/popo/ports/client_port_user.cpp
  iceoryx_posh/source/popo/rpc_header.cpp
  iceoryx_posh/source/popo/server_options.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_rpc_header.cpp
  iceoryx_posh/test/moduletests/test_popo_server_options.cpp
Labels: enhancement, refactoring

#1034 Iox #415 remove application port
  CHANGELOG.md
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/application_port.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/application_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/popo/ports/application_port.cpp
  iceoryx_posh/source/popo/ports/application_port_data.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
Labels: refactoring

#1007 iox-#861 Fix TypedUniqueId error handler usage and refactor to UniquePortId
  CHANGELOG.md
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_meta/CMakeLists.txt
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/typed_unique_id.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/typed_unique_id.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/unique_port_id.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp
  iceoryx_posh/source/mepoo/chunk_header.cpp
  iceoryx_posh/source/popo/building_blocks/typed_unique_id.cpp
  iceoryx_posh/source/popo/building_blocks/unique_port_id.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/mocks/publisher_mock.hpp
  iceoryx_posh/test/mocks/subscriber_mock.hpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_capro_message.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp
  iceoryx_posh/test/moduletests/test_popo_unique_port_id.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/testing/roudi_environment/roudi_environment.cpp
Labels: bugfix, technical debt

#1044 Iox #774 update codecov API and cmake support
  .github/workflows/build-test.yml
  CHANGELOG.md
  cmake/cyclonedds/CMakeLists.txt
  cmake/cyclonedds/cyclonedds-cxx.cmake.in
  cmake/cyclonedds/cyclonedds.cmake.in
  cmake/googletest/CMakeLists.txt
  cmake/googletest/googletest.cmake.in
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  doc/aspice_swe3_4/example/iceoryx_component/CMakeLists.txt
  doc/website/getting-started/installation.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/test/CMakeLists.txt
  iceoryx_dds/CMakeLists.txt
  iceoryx_dds/cmake/cpptoml/CMakeLists.txt
  iceoryx_dds/cmake/cpptoml/cpptoml.cmake.in
  iceoryx_dds/test/CMakeLists.txt
  iceoryx_examples/callbacks/CMakeLists.txt
  iceoryx_examples/callbacks_in_c/CMakeLists.txt
  iceoryx_examples/complexdata/CMakeLists.txt
  iceoryx_examples/ice_access_control/CMakeLists.txt
  iceoryx_examples/icedelivery/CMakeLists.txt
  iceoryx_examples/icedelivery_in_c/CMakeLists.txt
  iceoryx_examples/icehello/CMakeLists.txt
  iceoryx_examples/iceoptions/CMakeLists.txt
  iceoryx_examples/iceperf/CMakeLists.txt
  iceoryx_examples/singleprocess/CMakeLists.txt
  iceoryx_examples/user_header/CMakeLists.txt
  iceoryx_examples/waitset/CMakeLists.txt
  iceoryx_examples/waitset_in_c/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/platform/CMakeLists.txt
  iceoryx_hoofs/test/CMakeLists.txt
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/CMakeLists.txt
  iceoryx_integrationtest/CMakeLists.txt
  iceoryx_meta/CMakeLists.txt
  iceoryx_meta/build_options.cmake
  iceoryx_meta/tests.cmake
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/cpptoml.cmake.in
  iceoryx_posh/test/CMakeLists.txt
  tools/introspection/CMakeLists.txt
Labels: tooling

#1047 Iox #415 remove InvalidIdString and isValid() from ServiceDescription
  CHANGELOG.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/popo/ports/interface_port_data.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: refactoring
