Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-07, with the labels that each got.

#1429 iox-#1394 Mention Axivion syntax in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#1434 iox-#1295 Extend FAQ with more questions
  README.md
  doc/website/FAQ.md
  doc/website/getting-started/overview.md
Labels: documentation

#1437 iox-#1365 implement thread wrapper for windows
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/win/source/pthread.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port.hpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_chunk.cpp
Labels: enhancement, globex

#1445 iox-#1104 Remove null-ability from `cxx::function_ref`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/generic_raii.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scoped_static.inl
  iceoryx_hoofs/source/cxx/adaptive_wait.cpp
  iceoryx_hoofs/source/log/logger.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_and_then.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_or_else.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_generic_raii.cpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
Labels: refactoring

#1448 iox-#1393 Construct `DESTINATION_*` variables from `CMAKE_INSTALL_FULL_*DIR`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/cmake/Config.cmake.in
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
  iceoryx_posh/cmake/Config.cmake.in
Labels: bugfix

#1452 iox-#1196 Fix compiler warnings in binding c tests
  iceoryx_binding_c/test/CMakeLists.txt
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_wait_set.cpp
  iceoryx_binding_c/test/test.hpp
  iceoryx_posh/testing/include/iceoryx_posh/testing/mocks/posh_runtime_mock.hpp
Labels: refactoring

#1457 Iox #1196 fix clang tidy warnings integration branch
  .clang-tidy
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/test/.clang-tidy
  iceoryx_dds/test/.clang-tidy
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/.clang-tidy
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string_internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/source/units/duration.cpp
  iceoryx_hoofs/test/.clang-tidy
  iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_deadline_timer.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  iceoryx_hoofs/test/moduletests/test_unit_duration.cpp
  iceoryx_posh/test/.clang-tidy
Labels: refactoring, technical debt

#1463 iox-#1196 fix forward list warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/forward_list.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/forward_list.inl
  iceoryx_hoofs/test/moduletests/test_cxx_forward_list.cpp
Labels: technical debt

#1462 Iox #1196 fix stack warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
Labels: refactoring, technical debt

#1459 Iox #1196 fix serialization warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/serialization.inl
  iceoryx_hoofs/test/moduletests/test_cxx_serialization.cpp
Labels: refactoring, technical debt

#1467 iox-#1196 Add lint suppressions and fix warnings for PoorMansHeap
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/poor_mans_heap.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/poor_mans_heap.inl
  iceoryx_hoofs/test/moduletests/test_cxx_poor_mans_heap.cpp
Labels: clang-tidy

#1470 iox-#1196 Fix require, scoped_static, type_traits warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scoped_static.inl
  iceoryx_hoofs/source/cxx/requires.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_type_traits.cpp
Labels: clang-tidy

#1464 Iox #1196 fix list warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/list.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/list.inl
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
Labels: clang-tidy

#1477 iox-#1476 Replace single quotation mark with apostrophe
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/source/roudi/process_manager.cpp
Labels: bugfix

#1479 iox-#1196 Fix clang tidy warnings in `cxx::unique_ptr`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
Labels: AUTOSAR, clang-tidy

#1484 iox-#1196 fix periodic task warnings
  .clang-tidy
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_periodic_task.cpp
Labels: clang-tidy

#1487 iox-#1196 fix smart lock warnings
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_smart_lock.cpp
Labels: clang-tidy

#1474 iox-#1196 Fix warnings in FiFo
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_fifo.cpp
Labels: clang-tidy

#1483 iox-#1482 add IpcInterfaceBase::openIpcChannel error info
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
Labels: refactoring

#1496 iox-#1196 fix loffli warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.inl
  iceoryx_hoofs/source/concurrent/loffli.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp
Labels: clang-tidy

#1480 iox-#1196 Fix clang tidy warnings in `cxx::variant`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
Labels: AUTOSAR, clang-tidy

#1494 iox-#1196 Fix clang-tidy warning in storable_function
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl
  iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
Labels: clang-tidy

#1491 iox-#1196 fix taco warnings
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/taco.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/taco.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_taco.cpp
Labels: clang-tidy

#1475 Iox #1196 fix lockfree queue warnings
  .clang-tidy
  iceoryx_hoofs/include/iceoryx_hoofs/concurrent/lockfree_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/concurrent/resizeable_lockfree_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/cyclic_index.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/cyclic_index.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/index_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/index_queue.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/lockfree_queue.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/resizeable_lockfree_queue.inl
  iceoryx_hoofs/test/moduletests/test_index_queue.cpp
  iceoryx_hoofs/test/moduletests/test_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_lockfree_queue_buffer.cpp
  iceoryx_hoofs/test/moduletests/test_lockfree_queue_cyclic_index.cpp
  iceoryx_hoofs/test/moduletests/test_resizeable_lockfree_queue.cpp
Labels: clang-tidy

#1442 Iox #1440 fix file lock leak in release 2.0
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
Labels: bugfix

#1478 iox-#1476 Replace single quotation mark with apostrophe [release_2.0]
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-3.md
  iceoryx_posh/source/roudi/process_manager.cpp
Labels: bugfix

#1507 iox-#1196 fix warnings in named pipe
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_pipe.hpp
  iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp
Labels: clang-tidy

#1500 iox-#1196 Fix warnings in file lock
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/test/moduletests/test_posix_file_lock.cpp
Labels: clang-tidy

#1501 iox-#1196 fix warnings in message queue and ipc channel test
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/message_queue.hpp
  iceoryx_hoofs/source/posix_wrapper/message_queue.cpp
  iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp
Labels: clang-tidy

#1506 iox-#1196 fix warnings in mutex
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
  iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp
Labels: clang-tidy

#1456 iox-#1394 iox-#1196 Address Axivion and clang-tidy findings for `cxx::function_ref`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl
  iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
Labels: AUTOSAR, CERT, clang-tidy

#1511 iox-#1196 Fix warnings in thread and system configuration
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/system_configuration.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
Labels: clang-tidy

#1502 iox-#1196 fix file reader warnings
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/file_reader/file_reader.hpp
  iceoryx_hoofs/source/file_reader/file_reader.cpp
  iceoryx_hoofs/test/moduletests/test_file_reader.cpp
Labels: clang-tidy

#1499 iox-#1196 Fix warnings in access control
  CONTRIBUTING.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/access_control.hpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/test/moduletests/test_access_control.cpp
Labels: clang-tidy

#1473 iox-#1196 Fix clang-tidy and some AUTOSAR warnings in `cxx::vector`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
Labels: AUTOSAR, clang-tidy

#1519 iox-#1196 Fix warnings in types
  iceoryx_hoofs/source/posix_wrapper/types.cpp
  iceoryx_hoofs/test/moduletests/test_posix_types.cpp
Labels: clang-tidy

#1510 iox-#1196 fix warnings in posix call
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/platform_correction.hpp
  iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
Labels: clang-tidy

#1509 iox-#1196 fix warnings in posix access rights
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/access_control.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
  iceoryx_hoofs/test/moduletests/test_access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_rights.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/mepoo/segment_config.hpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
Labels: clang-tidy

#1529 iox-#1528 Fix usage of testing libs in source tree builds
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
  iceoryx_posh/CMakeLists.txt
Labels: bugfix

#1522 iox-#1196 Fix useless cast warnings
  doc/website/advanced/installation-guide-for-contributors.md
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
  iceoryx_hoofs/cmake/IceoryxPlatform.cmake
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/message_queue.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/mman.hpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/source/posix_wrapper/message_queue.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_adaptive_wait.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_rights.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.inl
  iceoryx_posh/source/mepoo/chunk_header.cpp
  iceoryx_posh/source/mepoo/chunk_settings.cpp
  iceoryx_posh/source/mepoo/memory_manager.cpp
  iceoryx_posh/source/popo/listener.cpp
  iceoryx_posh/source/popo/trigger.cpp
  iceoryx_posh/source/popo/trigger_handle.cpp
  iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp
  iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_popo_notification_info.cpp
  iceoryx_posh/test/moduletests/test_popo_rpc_header.cpp
Labels: clang-tidy

#1525 iox-#1196 Fix left-over clang-tidy warnings in `cxx::vector` and remove space in suppressions
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/poor_mans_heap.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_forward_list.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_expect.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
  iceoryx_hoofs/test/moduletests/test_file_reader.cpp
  tools/scripts/clang_tidy_check.sh
Labels: clang-tidy

#1526 iox-#1196 Add cxx to clang-tidy check
  .clang-tidy-diff-scans.txt
  .github/workflows/lint_pull_request.yml
  clang-tidy-files-to-scan.txt
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/helplets.inl
  iceoryx_hoofs/source/cxx/filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_forward_list.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_optional.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_stack.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  tools/scripts/clang_tidy_check.sh
  tools/scripts/ice_env.sh
Labels: clang-tidy

#1497 Iox #1196 fix clang tidy warnings shared memory object
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/allocator.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/allocator.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_allocator.cpp
  iceoryx_hoofs/test/moduletests/test_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_shared_memory_object.cpp
Labels: clang-tidy

#1537 iox-#1196 activate full clang-tidy nightly scan
  .github/actions/install-iceoryx-deps-and-clang/action.yml
  .github/workflows/lint_pull_request.yml
  .github/workflows/nightly.yml
Labels: tooling

#1488 iox-#1196 fix sofi warnings
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/sofi.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/sofi.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_sofi.cpp
  iceoryx_hoofs/test/stresstests/test_stress_sofi.cpp
Labels: clang-tidy

#1534 iox-#1196 Suppress clang-tidy and AUTOSAR warnings in `PointerRepository`
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
Labels: AUTOSAR, clang-tidy

#1538 iox-#1196 activate clang-tidy check on posix wrapper
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/source/posix_wrapper/message_queue.cpp
  iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_allocator.cpp
  iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
Labels: clang-tidy

#1441 iox-#1365 implement thread wrapper for apple
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/mac/source/pthread.cpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
Labels: enhancement, refactoring, globex

#1524 iox-#1196 Fix clang tidy warnings in `RelativePointerData`
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.inl
  iceoryx_hoofs/source/relocatable_pointer/relative_pointer_data.cpp
Labels: clang-tidy

#1548 iox-#1394 Fix AUTOSAR violations in DeadlineTimer
  iceoryx_hoofs/source/cxx/deadline_timer.cpp
Labels: AUTOSAR

#1543 iox-#1542 Support Bazel build system
  .bazelignore
  .bazelrc
  .github/workflows/build-test.yml
  .gitignore
  BUILD.bazel
  CONTRIBUTING.md
  WORKSPACE.bazel
  bazel/BUILD.bazel
  bazel/bazelbuild/BUILD.bazel
  bazel/bazelbuild/repositories.bzl
  bazel/bazelbuild/setup.bzl
  bazel/configure_file.bzl
  bazel/configure_version.bzl
  bazel/cpptoml/BUILD.bazel
  bazel/cpptoml/cpptoml.BUILD
  bazel/cpptoml/repositories.bzl
  bazel/googletest/BUILD.bazel
  bazel/googletest/repositories.bzl
  bazel/load_repositories.bzl
  bazel/setup_repositories.bzl
  doc/website/advanced/installation-guide-for-contributors.md
  doc/website/getting-started/installation.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/BUILD.bazel
  iceoryx_binding_c/test/BUILD.bazel
  iceoryx_examples/callbacks/BUILD.bazel
  iceoryx_examples/callbacks_in_c/BUILD.bazel
  iceoryx_examples/complexdata/BUILD.bazel
  iceoryx_examples/ice_access_control/BUILD.bazel
  iceoryx_examples/icedelivery/BUILD.bazel
  iceoryx_examples/icedelivery_in_c/BUILD.bazel
  iceoryx_examples/icediscovery/BUILD.bazel
  iceoryx_examples/icediscovery_in_c/BUILD.bazel
  iceoryx_examples/icehello/BUILD.bazel
  iceoryx_examples/iceoptions/BUILD.bazel
  iceoryx_examples/iceperf/BUILD.bazel
  iceoryx_examples/request_response/BUILD.bazel
  iceoryx_examples/request_response_in_c/BUILD.bazel
  iceoryx_examples/singleprocess/BUILD.bazel
  iceoryx_examples/user_header/BUILD.bazel
  iceoryx_examples/waitset/BUILD.bazel
  iceoryx_examples/waitset_in_c/BUILD.bazel
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/cyclic_index.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/index_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp
  iceoryx_hoofs/platform/BUILD.bazel
  iceoryx_hoofs/test/BUILD.bazel
  iceoryx_hoofs/test/stresstests/BUILD.bazel
  iceoryx_posh/BUILD.bazel
  iceoryx_posh/test/BUILD.bazel
  tools/introspection/BUILD.bazel
Labels: tooling
