Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-08, with the labels that each got.

#1552 iox-#1551 add inline keyword to inline methods
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.inl
Labels: bugfix

#1550 iox-#1547 Remove GitHub Caching from Bazel build in CI
  .github/workflows/build-test.yml
  tools/ci/build-test-ubuntu-bazel.sh
Labels: bugfix

#1553 Iox 1196 fix LLVM installation in GitHub CI
  .github/actions/install-iceoryx-deps-and-clang/action.yml
  .github/workflows/build-test.yml
  doc/website/concepts/best-practice-for-testing.md
Labels: bugfix

#1520 iox-#1196 Remove conversion operator in `RelativePointer`
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl
  iceoryx_hoofs/source/concurrent/loffli.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/source/mepoo/mem_pool.cpp
  iceoryx_posh/source/mepoo/shared_chunk.cpp
  iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
Labels: clang-tidy

#1557 Iox 1556 remove posix rights struct
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp
  iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
Labels: refactoring, technical debt

#1549 iox-#1394 Address AUTOSAR warnings in `RelativePointerData`
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.inl
  iceoryx_hoofs/source/relocatable_pointer/relative_pointer_data.cpp
  iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
Labels: AUTOSAR

#1539 iox-#1196 activate clang-tidy check on design_pattern
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/creation.hpp
Labels: clang-tidy

#1521 iox-#1196 Fix clang-tidy warnings in `RelativePointer`
  .clang-tidy-diff-scans.txt
  PLANNED_FEATURES.md
  README.md
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl
  iceoryx_hoofs/source/relocatable_pointer/base_relative_pointer.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
Labels: clang-tidy

#1561 iox-#1560 remove rarely used functions from helplets and refactor strlen2
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_hoofs/source/log/logger.cpp
  iceoryx_hoofs/source/log/logmanager.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl
  iceoryx_posh/include/iceoryx_posh/version/version_info.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/roudi/application/roudi_main.cpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
Labels: refactoring, technical debt

#1563 iox-#1196 Fix clang-tidy warnings in relocatable ptr
  .clang-tidy-diff-scans.txt
  iceoryx_dust/include/iceoryx_dust/relocatable_pointer/relocatable_ptr.hpp
  iceoryx_dust/include/iceoryx_dust/relocatable_pointer/relocatable_ptr.inl
  iceoryx_dust/test/moduletests/test_relocatable_ptr.cpp
Labels: clang-tidy

#1567 iox-#1566 Replace QAC++ suppressions with Axivion AUTOSAR suppressions
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
Labels: QAC++, Axivion

#1568 iox-#1394 Fix Axivion warnings for builder.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp
Labels: AUTOSAR, Axivion

#1570 iox-#1394 Fix last Axivion warning in builder
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp
Labels: AUTOSAR, Axivion

#1577 iox-#1576 Use clang-tidy 15
  .github/actions/install-iceoryx-deps-and-clang/action.yml
Labels: clang-tidy

#1578 Iox 590 fix include path iceoryx dust
  iceoryx_dust/CMakeLists.txt
  iceoryx_dust/test/moduletests/test_dust_modules.cpp
Labels: bugfix

#1581 iox-#1308 Set SOVERSION for shared libraries
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
Labels: technical debt

#1572 iox-#1394 fix axivion reported violations for string_internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string_internal.hpp
Labels: AUTOSAR

#1584 iox-#1580 Disable monitoring feature in RouDi by default
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
Labels: refactoring

#1583 iox-#1575 Properly initialize `ServiceRegistry` in shared memory
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/source/roudi/port_manager.cpp
Labels: bugfix

#1573 iox-#1571 Add check for `nullptr` in `unique_ptr::get()`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.inl
  iceoryx_posh/test/moduletests/test_popo_request.cpp
  iceoryx_posh/test/moduletests/test_popo_response.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
Labels: bugfix

#1588 iox-#1196 Restrict clang tidy diff scan to iceoryx_hoofs in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1585 iox-#1450 Rename `GenericRAII` to `ScopeGuard`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/scoped_static.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handler.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scope_guard.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scoped_static.inl
  iceoryx_hoofs/include/iceoryx_hoofs/log/logger.hpp
  iceoryx_hoofs/source/log/logger.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_scope_guard.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/error_handler_mock.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_components.hpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_capro_message.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_unique_port_id.cpp
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
Labels: refactoring

#1592 iox-#1365 set thread name in start routine
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/platform/linux/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/mac/source/pthread.cpp
  iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/unix/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp
  iceoryx_hoofs/platform/win/source/pthread.cpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
Labels: refactoring

#1590 iox-#1394 fix axivion violation for type traits hpp types hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/types.hpp
  iceoryx_hoofs/platform/linux/include/iceoryx_hoofs/platform/platform_settings.hpp
  iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/platform_settings.hpp
  iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/platform_settings.hpp
  iceoryx_hoofs/platform/unix/include/iceoryx_hoofs/platform/platform_settings.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/platform_settings.hpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
Labels: AUTOSAR

#1595 iox-#1594 Pass `CleanupCapacity` to underlying `cxx::function` in `ScopeGuard`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scope_guard.inl
Labels: bugfix
