Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-09, with the labels that each got.

#1598 iox-1394 fix AUTOSAR violations in algorithm files
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl
  iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp
  iceoryx_posh/source/mepoo/chunk_settings.cpp
  iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp
  iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp
Labels: AUTOSAR, refactoring

#1597 iox-#1596 Add check for `nullptr` in `RelativePointer`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
Labels: bugfix

#1606 Iox 1602 Fix CMake warnings and Cleanup
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/cmake/iceoryx_binding_cConfig.cmake
  iceoryx_binding_c/test/CMakeLists.txt
  iceoryx_dust/test/CMakeLists.txt
  iceoryx_hoofs/cmake/iceoryx_hoofsConfig.cmake
  iceoryx_hoofs/cmake/iceoryx_hoofs_testingConfig.cmake
  iceoryx_hoofs/testing/CMakeLists.txt
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/iceoryx_poshConfig.cmake
  iceoryx_posh/cmake/iceoryx_posh_testingConfig.cmake
Labels: bugfix, refactoring

#1451 iox-#1036 handle ipc abstraction in ipc interface base
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_dust/test/moduletests/test_ipc_channel.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_creator.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/source/runtime/ipc_interface_creator.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/test/moduletests/test_runtime_ipc_interface.cpp
Labels: refactoring

#1610 iox-#1609 Add log message before terminating
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/source/popo/building_blocks/locking_policy.cpp
Labels: bugfix

#1605 iox-#1394 Fix AUTOSAR violations in ScopeGuard
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scope_guard.inl
Labels: AUTOSAR

#1604 iox-1394 fix AUTOSAR and CERT violations in stack
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
Labels: AUTOSAR, CERT

#1641 iox-#1624 Fix typo
  doc/design/chunk_header.md
Labels: documentation

#1579 Iox-#1345 Add testing logger [Stacked PR 2]
  iceoryx_binding_c/test/moduletests/main.cpp
  iceoryx_dust/test/moduletests/test_dust_modules.cpp
  iceoryx_hoofs/test/integrationtests/test_hoofs_integration.cpp
  iceoryx_hoofs/test/moduletests/test_hoofs_modules.cpp
  iceoryx_hoofs/testing/CMakeLists.txt
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp
  iceoryx_hoofs/testing/logger.cpp
  iceoryx_posh/test/integrationtests/test_posh_integration.cpp
  iceoryx_posh/test/moduletests/test_posh_modules.cpp
Labels: refactoring, test

#1621 Iox-#1345 Re-enable tests and adjust logger [Stacked PR 3]
  iceoryx_binding_c/source/c_log.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/logstream.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/platform_building_blocks/console_logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/platform_building_blocks/logcommon.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/platform_building_blocks/logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/console_logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/logcommon.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/logger.hpp
  iceoryx_hoofs/source/log/platform_building_blocks/console_logger.cpp
  iceoryx_hoofs/source/log/platform_building_blocks/logger.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/test/moduletests/test_console_logger.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_logger.cpp
  iceoryx_hoofs/test/moduletests/test_logging.cpp
  iceoryx_hoofs/test/moduletests/test_logstream.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/logger_mock.hpp
  iceoryx_hoofs/testing/logger.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_compatibility_check_level.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_monitoringmode_logstream.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
Labels: refactoring

#1644 Iox 1104 remove nullability from unique ptr
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.inl
Labels: refactoring

#1658 iox-#1653 Remove Wgnu-zero-variadic-macro-arguments suppression from TYPED_TEST_SUITE
  iceoryx_dust/test/moduletests/test_relocatable_ptr.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_index_queue.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue_buffer.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue_cyclic_index.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_resizeable_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_types.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
  iceoryx_hoofs/test/moduletests/test_logstream.cpp
  iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
  iceoryx_hoofs/test/moduletests/test_posix_signal_handler.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp
  iceoryx_hoofs/test/stresstests/test_resizeable_lockfree_queue_stresstest.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_base_port.cpp
  iceoryx_posh/test/moduletests/test_popo_base_client.cpp
  iceoryx_posh/test/moduletests/test_popo_base_server.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: technical debt

#1443 iox-#1036 builder pattern for mutex
  .clang-tidy-diff-scans.txt
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/mutex.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/scheduler.hpp
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
  iceoryx_hoofs/source/posix_wrapper/scheduler.cpp
  iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_platform/linux/include/iceoryx_platform/sched.hpp
  iceoryx_platform/mac/include/iceoryx_platform/pthread.hpp
  iceoryx_platform/mac/include/iceoryx_platform/sched.hpp
  iceoryx_platform/mac/source/pthread.cpp
  iceoryx_platform/qnx/include/iceoryx_platform/pthread.hpp
  iceoryx_platform/qnx/include/iceoryx_platform/sched.hpp
  iceoryx_platform/unix/include/iceoryx_platform/sched.hpp
  iceoryx_platform/win/include/iceoryx_platform/pthread.hpp
  iceoryx_platform/win/include/iceoryx_platform/sched.hpp
  iceoryx_platform/win/source/pthread.cpp
  iceoryx_platform/win/source/sched.cpp
  iceoryx_posh/include/iceoryx_posh/error_handling/error_handling.hpp
  iceoryx_posh/source/popo/building_blocks/locking_policy.cpp
  tools/scripts/used-headers.txt
Labels: enhancement

#1634 iox-1469 implement copy and move operations for stack
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
  iceoryx_hoofs/test/moduletests/test_cxx_stack.cpp
Labels: bugfix, globex

#1651 iox-1643 Revert destruction order in copy and move assignment operators of cxx::vector
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
Labels: bugfix, globex

#1665 iox-1662 change vector::erase return type to bool
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
Labels: refactoring, globex

#1645 Iox-#1345 Add doxygen documentation to logger classes [Stacked PR 4]
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/console_logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/logcommon.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/logger.hpp
  iceoryx_hoofs/source/log/platform_building_blocks/logger.cpp
  iceoryx_hoofs/test/moduletests/test_console_logger.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_logging.cpp
  iceoryx_hoofs/test/moduletests/test_logstream.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/logger_mock.hpp
  iceoryx_hoofs/testing/logger.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_compatibility_check_level.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_monitoringmode_logstream.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
Labels: documentation

#1599 iox-#605 Refactor `PointerRepository`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl
  iceoryx_hoofs/source/concurrent/loffli.cpp
  iceoryx_hoofs/source/relocatable_pointer/base_relative_pointer.cpp
  iceoryx_posh/include/iceoryx_posh/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
Labels: refactoring

#1674 iox-#1345 Refactor parameterized tests
  iceoryx_hoofs/test/moduletests/test_logging.cpp
Labels: refactoring

#1675 iox-#1673 Improve usability of cxx::Expects and cxx::Ensures
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/source/cxx/requires.cpp
Labels: refactoring, globex

#1667 iox-#1666 Fix GatewayGeneric running state variable setting
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
Labels: bugfix

#1657 Iox 1104 remove nullability from function
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/include/iceoryx_binding_c/enums.h
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_binding_c/source/cpp2c_subscriber.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery/include/discovery_monitor.hpp
  iceoryx_examples/icediscovery/src/discovery_monitor.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scope_guard.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_scope_guard.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_posh/include/iceoryx_posh/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/trigger.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger_handle.hpp
  iceoryx_posh/source/popo/listener.cpp
  iceoryx_posh/source/popo/trigger.cpp
  iceoryx_posh/source/popo/trigger_handle.cpp
  iceoryx_posh/test/moduletests/test_popo_base_client.cpp
  iceoryx_posh/test/moduletests/test_popo_base_server.cpp
  iceoryx_posh/test/moduletests/test_popo_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
Labels: refactoring

#1603 iox-#605 Merge `BaseRelativePointer` with `RelativePointer`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl
  iceoryx_hoofs/source/relocatable_pointer/base_relative_pointer.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_posh/include/iceoryx_posh/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_pointer.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
Labels: AUTOSAR, refactoring

#1669 iox-#1668 Set chunk header originId always
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
Labels: bugfix

#1681 iox-#1345 Remove deprecated logger macros from hoofs
  iceoryx_dust/source/posix_wrapper/signal_watcher.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/hoofs_logging.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp
  iceoryx_hoofs/source/cxx/functional_interface.cpp
  iceoryx_hoofs/source/error_handling/error_handler.cpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
  iceoryx_hoofs/source/posix_wrapper/named_semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/scheduler.cpp
  iceoryx_hoofs/source/posix_wrapper/semaphore_interface.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/source/posix_wrapper/signal_handler.cpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/source/posix_wrapper/types.cpp
  iceoryx_hoofs/source/posix_wrapper/unnamed_semaphore.cpp
  iceoryx_hoofs/source/units/duration.cpp
  iceoryx_posh/include/iceoryx_posh/internal/log/posh_logging.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/mepoo/memory_manager.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_main.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
Labels: refactoring

#1676 Iox-#1345 Cleanup logger folder structure and add cmake option for minimal log level
  doc/website/advanced/configuration-guide.md
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/cmake/IceoryxHoofsDeployment.cmake
  iceoryx_hoofs/cmake/iceoryx_hoofs_deployment.hpp.in
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/types.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/iceoryx_hoofs_types.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/console_logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logformat.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/console_logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logformat.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/platform/logger.hpp
  iceoryx_hoofs/source/log/building_blocks/console_logger.cpp
  iceoryx_hoofs/source/log/building_blocks/logger.cpp
  iceoryx_hoofs/test/moduletests/test_console_logger.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/logger_mock.hpp
  iceoryx_hoofs/testing/logger.cpp
Labels: enhancement, refactoring
