Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-06, with the labels that each got.

#1388 iox-#1387 Fix link to AVIN AUTOSAR Adaptive Platform
  README.md
Labels: documentation

#1385 iox-#1287 Fix CMake install paths
  iceoryx_dds/CMakeLists.txt
  iceoryx_posh/CMakeLists.txt
Labels: tooling

#1397 iox-#1396 Fix data race in concurrent::FIFO push
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.inl
Labels: bugfix

#1407 iox-#1401 add PRIVATE to target_compile_options on the QNX platform
  iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
Labels: bugfix

#1408 Iox #1394 Fix wrong default case handling
  .github/workflows/build-test.yml
  .github/workflows/lint_pull_request.yml
  iceoryx_hoofs/source/file_reader/file_reader.cpp
  iceoryx_posh/source/popo/ports/client_port_roudi.cpp
Labels: AUTOSAR

#1402 iox-#751: remove old semaphore posix wrapper
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_wait_set.cpp
  iceoryx_dds/source/gateway/main.cpp
  iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp
  iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response/client_cxx_waitset.cpp
  iceoryx_examples/request_response_in_c/README.md
  iceoryx_examples/request_response_in_c/client_c_waitset.c
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/adaptive_wait.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/semaphore_interface.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_pipe.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/semaphore.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/signal_watcher.hpp
  iceoryx_hoofs/platform/linux/include/iceoryx_hoofs/platform/semaphore.hpp
  iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/semaphore.hpp
  iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/semaphore.hpp
  iceoryx_hoofs/platform/unix/include/iceoryx_hoofs/platform/semaphore.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/semaphore.hpp
  iceoryx_hoofs/source/cxx/adaptive_wait.cpp
  iceoryx_hoofs/source/cxx/functional_interface.cpp
  iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp
  iceoryx_hoofs/source/posix_wrapper/semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/signal_watcher.cpp
  iceoryx_hoofs/source/posix_wrapper/unnamed_semaphore.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_smart_lock.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_adaptive_wait.cpp
  iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp
  iceoryx_hoofs/test/moduletests/test_posix_signal_watcher.cpp
  iceoryx_hoofs/test/moduletests/test_semaphore_module.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/watch_dog.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_listener.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_variable_data.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/source/popo/building_blocks/condition_listener.cpp
  iceoryx_posh/source/popo/building_blocks/condition_notifier.cpp
  iceoryx_posh/source/popo/building_blocks/condition_variable_data.cpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/test/integrationtests/test_client_server.cpp
  iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
  iceoryx_posh/test/moduletests/test_mepoo_typed_mempool.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
  iceoryx_posh/test/moduletests/test_popo_listener.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
Labels: refactoring

#1417 iox-#1394 Prevent destruction of FunctionalInterface derived classes …
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp
Labels: AUTOSAR

#1416 iox-#1394 Prevent destruction of NewType derived classes by base class pointer
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/assignment.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/comparable.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/constructor.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/convertable.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/protected_constructor.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/sortable.hpp
Labels: AUTOSAR

#1424 Iox #1125 Add unique test ids into gtest case including TIMING_TEST
  iceoryx_binding_c/test/moduletests/test_request_header.cpp
  iceoryx_binding_c/test/moduletests/test_response_header.cpp
  iceoryx_binding_c/test/moduletests/test_wait_set.cpp
  iceoryx_hoofs/test/mocktests/test_error_handler_mock.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_periodic_task.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_deadline_timer.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
  iceoryx_posh/test/moduletests/test_popo_listener.cpp
  iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp
Labels: test

#1427 iox-#1425 create convenience macro for newtype
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp
Labels: enhancement

#1423 iox-#831 Replace `MethodCallback` with `cxx::function`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/method_callback.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/method_callback.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_periodic_task.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_method_callback.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/notification_attorney.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/trigger.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/include/iceoryx_posh/popo/notification_attorney.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger.hpp
  iceoryx_posh/include/iceoryx_posh/popo/trigger_handle.hpp
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/source/popo/listener.cpp
  iceoryx_posh/source/popo/trigger.cpp
  iceoryx_posh/source/popo/trigger_handle.cpp
  iceoryx_posh/test/mocks/trigger_handle_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_base_client.cpp
  iceoryx_posh/test/moduletests/test_popo_base_server.cpp
  iceoryx_posh/test/moduletests/test_popo_trigger.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
  tools/run_tests.sh
Labels: refactoring

#1433 iox-#1419 runtime name must be valid file name
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_posh/include/iceoryx_posh/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
Labels: bugfix
