Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-02, with the labels that each got.

#1058 Iox #415 add event parameter to find service
  CHANGELOG.md
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: enhancement

#1063 iox-#1062 Implement stream operator for ChunkReceiveResult and AllocationError
  CHANGELOG.md
  iceoryx_hoofs/test/moduletests/test_posix_signal_watcher.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
Labels: enhancement

#1068 iox-#988 Add unique test identifiers to ASPICE example and Cylcone DDS gateway
  doc/aspice_swe3_4/example/iceoryx_component/test/moduletests/test_example_base_class.cpp
  iceoryx_dds/test/moduletests/test_cyclone_data_reader.cpp
  iceoryx_dds/test/moduletests/test_dds_to_iox.cpp
  iceoryx_dds/test/moduletests/test_iox_to_dds.cpp
Labels: refactoring

#1053 Iox #1036 in place creation for shared memory
  CHANGELOG.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_pipe.hpp
  iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_shared_memory_object.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl
  iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
Labels: refactoring

#1085 iox-#1076 Introduce `cxx::invoke_result` to solve the deprecated `std::result_of` problem
  iceoryx_hoofs/include/iceoryx_hoofs/concurrent/resizeable_lockfree_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/timer.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/grp.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pwd.hpp
  iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/win32_errorHandling.hpp
  iceoryx_hoofs/platform/win/source/semaphore.cpp
  iceoryx_hoofs/platform/win/source/win32_errorHandling.cpp
  iceoryx_hoofs/source/posix_wrapper/timer.cpp
  iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp
  iceoryx_hoofs/test/moduletests/test_unit_duration.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
Labels: bugfix

#1093 [Backport release 1.0] Iox #1092 add limits include for gcc 11
  .github/workflows/experimental_build.yml
  CHANGELOG.md
  VERSION
  cmake/googletest/0001-remove-werror-from-build-flags.patch
  cmake/googletest/CMakeLists.txt
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/package.xml
  iceoryx_dds/CMakeLists.txt
  iceoryx_integrationtest/package.xml
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch
  iceoryx_posh/cmake/cpptoml/CMakeLists.txt
  iceoryx_posh/package.xml
  iceoryx_utils/CMakeLists.txt
  iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/pointer_repository.hpp
  iceoryx_utils/package.xml
  iceoryx_utils/test/moduletests/test_posix_timer.cpp
  tools/introspection/CMakeLists.txt
Labels: bugfix

#1075 Iox #27 consolidate port queue policies [stacked PR #1]
  CHANGELOG.md
  iceoryx_binding_c/include/iceoryx_binding_c/enums.h
  iceoryx_binding_c/include/iceoryx_binding_c/internal/c2cpp_enum_translation.hpp
  iceoryx_binding_c/include/iceoryx_binding_c/internal/cpp2c_enum_translation.hpp
  iceoryx_binding_c/include/iceoryx_binding_c/publisher.h
  iceoryx_binding_c/include/iceoryx_binding_c/runtime.h
  iceoryx_binding_c/source/c2cpp_enum_translation.cpp
  iceoryx_binding_c/source/c_publisher.cpp
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_c2cpp_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/iceoptions/iox_publisher_with_options.cpp
  iceoryx_examples/iceoptions/iox_subscriber_with_options.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender_data.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_roudi.hpp
  iceoryx_posh/include/iceoryx_posh/popo/client_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/port_queue_policies.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/server_options.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/popo/client_options.cpp
  iceoryx_posh/source/popo/ports/client_port_data.cpp
  iceoryx_posh/source/popo/ports/client_port_roudi.cpp
  iceoryx_posh/source/popo/ports/server_port_data.cpp
  iceoryx_posh/source/popo/ports/server_port_roudi.cpp
  iceoryx_posh/source/popo/publisher_options.cpp
  iceoryx_posh/source/popo/server_options.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_client_options.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_options.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_options.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_common.hpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_options.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
Labels: technical debt

#1094 Iox #415 additional find service method
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: enhancement

#1090 iox-#1082 Set stack size for singleprocess example
  CHANGELOG.md
  doc/website/FAQ.md
  iceoryx_examples/singleprocess/CMakeLists.txt
  iceoryx_posh/test/CMakeLists.txt
Labels: bugfix

#1111 Iox #299 Clang-Tidy Pull-Request job
  .github/workflows/build-test.yml
  .github/workflows/lint_pull_request.yml
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_discovery.hpp
  tools/scripts/clang_tidy_check.sh
Labels: tooling

#1116 iox-#1108 Fix potential segfault in string
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
Labels: bugfix

#1114 iox-#27 Refactor CaproMessageSubType to be able to use ServerPorts with InterfacePorts [stacked PR #1.5]
  CHANGELOG.md
  iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl
  iceoryx_dds/test/moduletests/test_iox_to_dds.cpp
  iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.hpp
  iceoryx_posh/source/capro/capro_message.cpp
  iceoryx_posh/source/popo/ports/publisher_port_roudi.cpp
  iceoryx_posh/source/popo/ports/server_port_roudi.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/test/moduletests/test_capro_message.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_roudi.cpp
Labels: refactoring

#1132 Iox #1130 replace high resolution clock with system clock and steady clock
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_examples/iceperf/base.cpp
  iceoryx_hoofs/source/log/logstream.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
Labels: bugfix

#1131 iox-#938 check for publisher destruction in does violate communication policy
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.inl
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
Labels: bugfix

#1084 iox-#27 Add client and server port to PortPool and PortManager [stacked PR #2]
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.inl
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/popo/ports/client_port_data.cpp
  iceoryx_posh/source/popo/ports/client_port_roudi.cpp
  iceoryx_posh/source/popo/ports/server_port_data.cpp
  iceoryx_posh/source/popo/ports/server_port_roudi.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_roudi.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_client_server.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
Labels: enhancement

#1105 iox-#415 Add functional find service example
  CONTRIBUTING.md
  doc/website/examples/icediscovery.md
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_examples/README.md
  iceoryx_examples/icediscovery/CMakeLists.txt
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery/iox_find_service.cpp
  iceoryx_examples/icediscovery/iox_offer_service.cpp
  iceoryx_integrationtest/CMakeLists.txt
  iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_example.py
  iceoryx_meta/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
Labels: example

#1087 Iox #27 add client and server port to runtime, roudi and process manager [stacked PR #3]
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/mocks/posh_runtime_mock.hpp
Labels: enhancement

#1091 Iox #27 add untyped client and server api [stacked PR #4]
  doc/design/diagrams/request_response/client_port.puml
  doc/design/diagrams/request_response/server_port.puml
  doc/design/diagrams/request_response/untyped_api.puml
  doc/website/images/client_port.svg
  doc/website/images/server_port.svg
  doc/website/images/untyped_api.svg
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_server_port_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_server_impl.inl
  iceoryx_posh/include/iceoryx_posh/popo/rpc_header.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_client.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_server.hpp
  iceoryx_posh/source/popo/ports/base_port.cpp
  iceoryx_posh/source/popo/ports/client_port_user.cpp
  iceoryx_posh/source/popo/ports/server_port_user.cpp
  iceoryx_posh/source/popo/rpc_header.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
Labels: enhancement

#1146 iox-#1126 Add missing entries to iceoryx 2.0 changelog
  doc/website/release-notes/iceoryx-v1-0-0.md
  doc/website/release-notes/iceoryx-v2-0-0.md
Labels: documentation

#1127 iox-#1074 Define service discovery limits
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_binding_c/include/iceoryx_binding_c/config.h
  iceoryx_binding_c/source/c_config.cpp
  iceoryx_binding_c/test/moduletests/test_config.cpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/CMakeLists.txt
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: refactoring

#1089 Iox #27 add typed client and server api [stacked PR #5]
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/typed_port_api_trait.hpp
  iceoryx_posh/include/iceoryx_posh/popo/client.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp
  iceoryx_posh/include/iceoryx_posh/popo/server.hpp
  iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
Labels: enhancement

#1134 iox-#27 Run `ServiceDiscovery` tests for `popo::UntypedServer`
  iceoryx_examples/icediscovery/iox_find_service.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
Labels: enhancement

#1124 Iox #27 create client c binding
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/include/iceoryx_binding_c/api.h
  iceoryx_binding_c/include/iceoryx_binding_c/client.h
  iceoryx_binding_c/include/iceoryx_binding_c/config.h
  iceoryx_binding_c/include/iceoryx_binding_c/enums.h
  iceoryx_binding_c/include/iceoryx_binding_c/internal/c2cpp_enum_translation.hpp
  iceoryx_binding_c/include/iceoryx_binding_c/internal/cpp2c_enum_translation.hpp
  iceoryx_binding_c/include/iceoryx_binding_c/listener.h
  iceoryx_binding_c/include/iceoryx_binding_c/notification_info.h
  iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h
  iceoryx_binding_c/include/iceoryx_binding_c/types.h
  iceoryx_binding_c/include/iceoryx_binding_c/wait_set.h
  iceoryx_binding_c/source/c2cpp_enum_translation.cpp
  iceoryx_binding_c/source/c_client.cpp
  iceoryx_binding_c/source/c_listener.cpp
  iceoryx_binding_c/source/c_notification_info.cpp
  iceoryx_binding_c/source/c_publisher.cpp
  iceoryx_binding_c/source/c_wait_set.cpp
  iceoryx_binding_c/source/cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/main.cpp
  iceoryx_binding_c/test/moduletests/test_c2cpp_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_client.cpp
  iceoryx_binding_c/test/moduletests/test_config.cpp
  iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_types.cpp
  iceoryx_binding_c/test/moduletests/test_wait_set.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/popo/client_options.hpp
  iceoryx_posh/source/popo/client_options.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/testing/include/iceoryx_posh/testing/mocks/posh_runtime_mock.hpp
Labels: enhancement

#1153 iox-#27 Remove fire and forget from request-response
  doc/design/diagrams/request_response/request_response_header.puml
  doc/design/request_response_communication.md
  doc/website/images/client_and_server_options.svg
  doc/website/images/iceoryx_components_diagram_nextgen_release.svg
  doc/website/images/request_response_header.svg
  iceoryx_posh/include/iceoryx_posh/popo/rpc_header.hpp
  iceoryx_posh/source/popo/rpc_header.cpp
  iceoryx_posh/test/moduletests/test_popo_rpc_header.cpp
Labels: refactoring

#1152 Iox #27 create mocks for client and server port
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_server_port_types.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/test/mocks/base_port_mock.hpp
  iceoryx_posh/test/mocks/client_mock.hpp
  iceoryx_posh/test/mocks/server_mock.hpp
  iceoryx_posh/test/mocks/trigger_handle_mock.hpp
Labels: test

#1138 Iox #27 add untyped client and server api tests [stacked PR #4.1]
  iceoryx_binding_c/include/iceoryx_binding_c/types.h
  iceoryx_binding_c/test/moduletests/main.cpp
  iceoryx_binding_c/test/moduletests/test_chunk.cpp
  iceoryx_binding_c/test/moduletests/test_service_discovery.cpp
  iceoryx_binding_c/test/moduletests/test_types.cpp
  iceoryx_binding_c/test/moduletests/test_types_storage_size.hpp
  iceoryx_binding_c/test/test.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp
  iceoryx_posh/include/iceoryx_posh/mepoo/memory_info.hpp
  iceoryx_posh/include/iceoryx_posh/popo/client_options.hpp
  iceoryx_posh/include/iceoryx_posh/popo/server_options.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/port_config_info.hpp
  iceoryx_posh/source/mepoo/memory_info.cpp
  iceoryx_posh/source/runtime/port_config_info.cpp
  iceoryx_posh/test/mocks/base_port_mock.hpp
  iceoryx_posh/test/mocks/client_mock.hpp
  iceoryx_posh/test/mocks/server_mock.hpp
  iceoryx_posh/test/mocks/trigger_handle_mock.hpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_info.cpp
  iceoryx_posh/test/moduletests/test_popo_base_client.cpp
  iceoryx_posh/test/moduletests/test_popo_base_server.cpp
  iceoryx_posh/test/moduletests/test_popo_client_options.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_rpc_header.cpp
  iceoryx_posh/test/moduletests/test_popo_server_options.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_client.cpp
  iceoryx_posh/test/moduletests/test_popo_untyped_server.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_runtime_port_config_info.cpp
Labels: enhancement

#1162 iox-#1120 Prevent creation of `popo::Publisher`'s with internal `ServiceDescription`
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_hoofs/include/iceoryx_hoofs/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/source/capro/service_description.cpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
Labels: bugfix

#1117 iox-#1103 Add discovery monitoring examples
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_examples/icediscovery/CMakeLists.txt
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery/include/discovery_blocking.hpp
  iceoryx_examples/icediscovery/include/discovery_monitor.hpp
  iceoryx_examples/icediscovery/iox_discovery_monitor.cpp
  iceoryx_examples/icediscovery/iox_offer_service.cpp
  iceoryx_examples/icediscovery/iox_wait_for_service.cpp
  iceoryx_examples/icediscovery/src/discovery_blocking.cpp
  iceoryx_examples/icediscovery/src/discovery_monitor.cpp
  iceoryx_integrationtest/CMakeLists.txt
  iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_monitoring.py
  iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp
  iceoryx_posh/source/roudi/service_registry.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
  tools/iceoryx_build_test.sh
Labels: example

#1139 Iox #27 preparations for typed client and server api tests [stacked PR #4.6]
  iceoryx_posh/include/iceoryx_posh/internal/popo/request.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/response.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.inl
  iceoryx_posh/include/iceoryx_posh/popo/request.hpp
  iceoryx_posh/include/iceoryx_posh/popo/response.hpp
  iceoryx_posh/test/moduletests/test_popo_request.cpp
  iceoryx_posh/test/moduletests/test_popo_response.cpp
  iceoryx_posh/test/moduletests/test_popo_sample.cpp
  iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
  iceoryx_posh/test/moduletests/test_popo_smart_chunk_common.hpp
Labels: test

#1172 iox-#27 integration tests
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/test/integrationtests/test_client_server.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_client_server.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
Labels: test

#1159 iox-#1144 set condition variable parameter and prepare configuration via CMake
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-v2-0-0.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/cmake/iceoryx_binding_cConfig.cmake
  iceoryx_binding_c/cmake/iceoryx_binding_c_deployment.h.in
  iceoryx_binding_c/include/iceoryx_binding_c/types.h
  iceoryx_binding_c/source/c_config.cpp
  iceoryx_binding_c/test/moduletests/main.cpp
  iceoryx_binding_c/test/moduletests/test_config.cpp
  iceoryx_binding_c/test/moduletests/test_types_storage_size.hpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/Config.cmake.in
  iceoryx_posh/cmake/IceoryxPoshDeployment.cmake
  iceoryx_posh/cmake/iceoryx_poshConfig.cmake
  iceoryx_posh/cmake/iceoryx_posh_deployment.hpp.in
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_listener.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_variable_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/include/iceoryx_posh/popo/notification_attorney.hpp
  iceoryx_posh/source/popo/building_blocks/condition_listener.cpp
  iceoryx_posh/source/popo/building_blocks/condition_notifier.cpp
  iceoryx_posh/source/popo/listener.cpp
  iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
  tools/ci/build-test-windows.ps1
Labels: enhancement
