Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-11, with the labels that each got.

#1607 Iox #1394 fix axivion violation for optional hpp inl
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/optional.inl
  iceoryx_hoofs/test/mocktests/test_error_handler_mock.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_optional.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_stack.cpp
Labels: AUTOSAR

#1749 iox-#1614 implement uninitialized array
  .clang-tidy-diff-scans.txt
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/cxx/forward_list.hpp
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/concurrent/lockfree_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/concurrent/resizeable_lockfree_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/list.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/lockfree_queue.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/sofi.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/containers/uninitialized_array.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/containers/uninitialized_array.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue_buffer.cpp
  iceoryx_hoofs/test/moduletests/test_containers_uninitialized_array.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
Labels: enhancement, refactoring, globex

#1774 iox-#1614 Move uninitialized array
  .clang-tidy-diff-scans.txt
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/cxx/forward_list.hpp
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/container/include/iox/detail/uninitialized_array.inl
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/concurrent/lockfree_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/list.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/sofi.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_container_uninitialized_array.cpp
Labels: refactoring, globex

#1358 iox-#1345 Design document for logging
  .clang-tidy-diff-scans.txt
  doc/design/diagrams/logging/logger_compile_time_replacement.puml
  doc/design/diagrams/logging/logger_runtime_replacement.puml
  doc/design/diagrams/logging/logger_testing_classes.puml
  doc/design/diagrams/logging/logger_testing_sequence.puml
  doc/design/diagrams/logging/logging_classes.puml
  doc/design/diagrams/logging/logging_with_logstream.puml
  doc/design/logging.md
  doc/website/images/logger_compile_time_replacement.svg
  doc/website/images/logger_runtime_replacement.svg
  doc/website/images/logger_testing_classes.svg
  doc/website/images/logger_testing_sequence.svg
  doc/website/images/logging_classes.svg
  doc/website/images/logging_with_logstream.svg
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/test/moduletests/main.cpp
  iceoryx_dust/test/moduletests/test_dust_modules.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/console_logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/logstream.inl
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/console_logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp
  iceoryx_hoofs/source/log/building_blocks/console_logger.cpp
  iceoryx_hoofs/test/integrationtests/test_hoofs_integration.cpp
  iceoryx_hoofs/test/moduletests/test_console_logger.cpp
  iceoryx_hoofs/test/moduletests/test_hoofs_modules.cpp
  iceoryx_hoofs/test/moduletests/test_logging.cpp
  iceoryx_hoofs/test/moduletests/test_logstream.cpp
  iceoryx_hoofs/test/stresstests/test_hoofs_stress.cpp
  iceoryx_hoofs/testing/CMakeLists.txt
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/testing_logger.hpp
  iceoryx_hoofs/testing/testing_logger.cpp
  iceoryx_posh/include/iceoryx_posh/internal/log/posh_logging.hpp
  iceoryx_posh/test/integrationtests/test_posh_integration.cpp
  iceoryx_posh/test/moduletests/test_posh_modules.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
Labels: documentation

#1782 iox-#1781 Update CI actions to fix warnings
  .github/workflows/build-test.yml
  .github/workflows/lint_pull_request.yml
  .lycheeignore
Labels: bugfix, tooling

#1582 iox #1394 fix axivion violation for string
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
Labels: AUTOSAR

#1793 iox-#1394 Fix AUTOSAR violations in PointerRepository
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/pointer_repository.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/pointer_repository.inl
Labels: AUTOSAR, globex

#1102 iox #1067 create command line parser abstraction
  doc/design/command-line-parser.md
  doc/design/diagrams/command_line_parser/command_line_parser_class_overview.puml
  doc/design/diagrams/command_line_parser/command_line_parser_macro_usage.puml
  doc/design/diagrams/command_line_parser/command_line_parser_usage.puml
  doc/website/images/command_line_parser_class_overview.svg
  doc/website/images/command_line_parser_macro_usage.svg
  doc/website/images/command_line_parser_usage.svg
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/CMakeLists.txt
  iceoryx_dust/include/iceoryx_dust/cli/command_line_argument_definition.hpp
  iceoryx_dust/include/iceoryx_dust/cli/types.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/arguments.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/arguments.inl
  iceoryx_dust/include/iceoryx_dust/internal/cli/command_line_parser.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option_definition.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option_manager.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option_manager.inl
  iceoryx_dust/source/cli/arguments.cpp
  iceoryx_dust/source/cli/command_line_parser.cpp
  iceoryx_dust/source/cli/option.cpp
  iceoryx_dust/source/cli/option_definition.cpp
  iceoryx_dust/source/cli/option_manager.cpp
  iceoryx_dust/test/moduletests/test_cli_command_line_argument_definition.cpp
  iceoryx_dust/test/moduletests/test_cli_command_line_common.hpp
  iceoryx_dust/test/moduletests/test_cli_command_line_parser.cpp
  iceoryx_dust/test/moduletests/test_cli_option.cpp
  iceoryx_dust/test/moduletests/test_cli_option_definition.cpp
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/source/cxx/type_traits.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_type_traits.cpp
  iceoryx_platform/win/include/iceoryx_platform/platform_correction.hpp
  tools/scripts/check_test_ids.sh
Labels: enhancement

#1799 iox-#1798 Fix float comparision tests for cmd line parser
  iceoryx_dust/test/moduletests/test_cli_command_line_argument_definition.cpp
  iceoryx_dust/test/moduletests/test_cli_command_line_parser.cpp
Labels: refactoring

#1792 iox-#1394 Address re-introduced AUTOSAR warnings
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scoped_static.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/relative_pointer_data.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.inl
Labels: AUTOSAR

#1786 iox-1394 fix autosar violations in variant
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
Labels: AUTOSAR, globex
