Repository eclipse-iceoryx/iceoryx, pull requests merged in 2022-10, with the labels that each got.

#1691 iox-#1345 Update release notes for logger
  doc/website/release-notes/iceoryx-unreleased.md
Labels: documentation

#1677 iox-605 Introduce `memory` namespace
  doc/shared-memory-communication.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/relocatable_pointer/relocatable_ptr.hpp
  iceoryx_dust/include/iceoryx_dust/relocatable_pointer/relocatable_ptr.inl
  iceoryx_dust/test/moduletests/test_relocatable_ptr.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/pointer_repository.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/pointer_repository.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/relative_pointer.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/relative_pointer_data.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/relative_pointer_data.inl
  iceoryx_hoofs/source/relocatable_pointer/relative_pointer_data.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_hoofs/test/moduletests/test_relative_pointer_data.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/chunk_management.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shm_safe_unmanaged_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/source/mepoo/shared_chunk.cpp
  iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_pointer.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
Labels: refactoring

#1697 iox-1394 fix AUTOSAR violations in newtype
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/assignment.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/comparable.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/constructor.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/convertable.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/protected_constructor.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/sortable.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
Labels: AUTOSAR, globex

#1600 iox-#1295 Update component and layer diagram for upcoming release
  doc/design/diagrams/iceoryx_components_diagram_v3_0_0.puml
  doc/design/diagrams/iceoryx_software_layers_v3_0_0.puml
  doc/website/images/iceoryx_components_diagram_v3_0_0.svg
  doc/website/images/iceoryx_software_layers_v3_0_0.svg
  iceoryx_hoofs/README.md
Labels: documentation

#1707 iox-1655 Remove `reset` method from `cxx::unique_ptr`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
  iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber_impl.inl
Labels: bugfix

#1719 iox-#605 Move `RelativePointer` from internal to public include directory
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.inl
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/chunk_management.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/source/mepoo/shared_chunk.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
Labels: refactoring

#1706 iox-1394 fix axivion violation for attributes hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp
Labels: AUTOSAR

#1586 iox-1394 Fix AUTOSAR warnings for `unique_ptr`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
Labels: AUTOSAR, CERT

#1682 iox-#1345 fix axivion warnings in logger files
  .clang-format
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/console_logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logformat.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logger.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/logstream.inl
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/console_logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logformat.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logger.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp
  iceoryx_hoofs/source/log/building_blocks/console_logger.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/logger_mock.hpp
Labels: AUTOSAR, Axivion

#1727 iox-#1635 Use GTEST_SKIP for test which require additional user
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/test_definitions.hpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
Labels: test

#1724 iox-#1394-fix-axivion-violation-for-type_traits_hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
Labels: AUTOSAR, Axivion

#1722 iox-1394 fix axivion warnings for functional interface
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl
  iceoryx_hoofs/source/cxx/functional_interface.cpp
Labels: AUTOSAR

#1737 iox-#1736 use clang format 15 in ci
  .github/actions/install-iceoryx-deps-and-clang/action.yml
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/gateway/channel.inl
  iceoryx_posh/include/iceoryx_posh/popo/enum_trigger_type.hpp
Labels: bugfix

#1739 iox-#1345 do not create logstream object when logging is off
  iceoryx_hoofs/cmake/IceoryxHoofsDeployment.cmake
  iceoryx_hoofs/include/iceoryx_hoofs/internal/log/logstream.inl
  iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.inl
Labels: enhancement

#1738 iox-#1704 Remove explicit includes of `function_ref`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
Labels: refactoring

#1729 iox-1394 fix AUTOSAR violations in vector
  .github/PULL_REQUEST_TEMPLATE.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
Labels: AUTOSAR, globex

#1743 iox-1394 Address last AUTOSAR finding in `unique_ptr`
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
Labels: AUTOSAR

#1744 iox-#1394 Address left-over AUTOSAR findings in `function_ref`
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl
  iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
Labels: AUTOSAR

#1698 Iox 1394 fix axivion violations in cxx function
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl
Labels: AUTOSAR, globex

#1754 iox-1750 Add `Expects` to `cxx::expected::value()` and `get_error()`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
Labels: bugfix

#1688 iox-#1516 Refactor iceoryx_posh testing lib into own CMake file
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/testing/CMakeLists.txt
Labels: refactoring

#1757 iox-1751 Add equality operators for `expected` and `variant`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl
  iceoryx_hoofs/memory/include/iox/unique_ptr.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
Labels: enhancement

#1762 iox-#1391 Fix legacy build when using `unique_ptr`
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/unique_ptr.hpp
Labels: refactoring

#1764 iox-#1547 Add ldl to linkopts for stresstest in Bazel
  iceoryx_hoofs/test/stresstests/BUILD.bazel
Labels: tooling
