Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-02, with the labels that each got.

#1865 iox-1391 move design types to separate module
  .clang-tidy-diff-scans.txt
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/design/include/iox/builder.hpp
  iceoryx_hoofs/design/include/iox/detail/functional_interface.inl
  iceoryx_hoofs/design/include/iox/detail/newtype.inl
  iceoryx_hoofs/design/include/iox/detail/newtype/assignment.hpp
  iceoryx_hoofs/design/include/iox/detail/newtype/comparable.hpp
  iceoryx_hoofs/design/include/iox/detail/newtype/constructor.hpp
  iceoryx_hoofs/design/include/iox/detail/newtype/convertable.hpp
  iceoryx_hoofs/design/include/iox/detail/newtype/internal.hpp
  iceoryx_hoofs/design/include/iox/detail/newtype/protected_constructor.hpp
  iceoryx_hoofs/design/include/iox/detail/newtype/sortable.hpp
  iceoryx_hoofs/design/include/iox/functional_interface.hpp
  iceoryx_hoofs/design/include/iox/newtype.hpp
  iceoryx_hoofs/design/source/functional_interface.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_id.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/mutex.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/memory_map.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_semaphore.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/unnamed_semaphore.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/newtype.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/design_pattern/builder.hpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_and_then.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_common.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_common.hpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_concat_multiple_calls.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_expect.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_or_else.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_types.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_types.hpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_value_or.cpp
  iceoryx_hoofs/test/moduletests/test_design_newtype.cpp
  iceoryx_hoofs/vocabulary/include/iox/expected.hpp
  iceoryx_hoofs/vocabulary/include/iox/optional.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/unique_port_id.hpp
  iceoryx_posh/source/popo/building_blocks/unique_port_id.cpp
Labels: refactoring, globex

#1876 iox-#1871 Fix aggressive loop optimizations error with gcc9.4
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
Labels: bugfix

#1874 Fix warnings in buffer and container modules
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
Labels: AUTOSAR, Axivion

#1873 iox-#1872 Update Framework References in Documentation
  README.md
  doc/website/getting-started/what-is-iceoryx.md
Labels: documentation

#1863 iox-1391 Move time-related classes to `Time` module
  .clang-tidy-diff-scans.txt
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_examples/iceperf/base.hpp
  iceoryx_examples/iceperf/mq.hpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/semaphore_interface.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/deadline_timer.hpp
  iceoryx_hoofs/posix/time/include/iox/deadline_timer.hpp
  iceoryx_hoofs/posix/time/include/iox/detail/adaptive_wait.hpp
  iceoryx_hoofs/posix/time/source/adaptive_wait.cpp
  iceoryx_hoofs/posix/time/source/deadline_timer.cpp
  iceoryx_hoofs/source/units/duration.cpp
  iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp
  iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_hoofs/test/moduletests/test_time_adaptive_wait.cpp
  iceoryx_hoofs/test/moduletests/test_time_deadline_timer.cpp
  iceoryx_hoofs/test/moduletests/test_time_unit_duration.cpp
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/watch_dog.hpp
  iceoryx_hoofs/time/include/iox/detail/duration.inl
  iceoryx_hoofs/time/include/iox/duration.hpp
  iceoryx_platform/unix/include/iceoryx_platform/semaphore.hpp
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_generic.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_popo_user_trigger.cpp
  tools/introspection/source/introspection_app.cpp
  tools/scripts/list_stl_dependencies.sh
  tools/scripts/used-headers.txt
Labels: refactoring, globex

#1880 Iox 1781 rework compilers in ci
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build-test.yml
  .github/workflows/lint_master.yml
  iceoryx_platform/qnx/include/iceoryx_platform/semaphore.hpp
  tools/axivion/trigger_pipeline.py
  tools/axivion/wait_for_pipeline.py
  tools/ci/build-test-ubuntu-with-gcc5.sh
  tools/scripts/used-headers.txt
Labels: tooling

#1882 Fix more warnings in vector.inl & stack.inl
  iceoryx_hoofs/buffer/include/iox/detail/stack.inl
  iceoryx_hoofs/container/include/iox/detail/vector.inl
Labels: AUTOSAR, Axivion

#1887 Fix more warnings in vector.hpp & uninitialized_array.hpp
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/container/include/iox/vector.hpp
Labels: AUTOSAR, Axivion

#1879 iox-1613 replace EXPECT_DEATH with custom mechanism
  doc/design/error-handling.md
  iceoryx_binding_c/source/c_runtime.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_runtime.cpp
  iceoryx_binding_c/test/moduletests/test_service_discovery.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_dust/test/moduletests/test_cxx_forward_list.cpp
  iceoryx_dust/test/moduletests/test_file_reader.cpp
  iceoryx_hoofs/test/mocktests/test_fatal_failure.cpp
  iceoryx_hoofs/test/mocktests/test_hoofs_mock.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_and_then.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_expect.cpp
  iceoryx_hoofs/test/moduletests/test_design_functional_interface_or_else.cpp
  iceoryx_hoofs/test/moduletests/test_vocabulary_expected.cpp
  iceoryx_hoofs/test/moduletests/test_vocabulary_string.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/expect_no_death.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/fatal_failure.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/fatal_failure.inl
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/error_handler_mock.hpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
  iceoryx_posh/test/moduletests/test_mepoo_config.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
Labels: test, technical debt

#1889 iox-1612 make lossy std string conversion more visible
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option_manager.inl
  iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_dust/test/moduletests/test_cli_command_line_parser.cpp
  iceoryx_dust/test/moduletests/test_cxx_string_conversion.cpp
  iceoryx_hoofs/utility/include/iox/detail/into.inl
  iceoryx_hoofs/utility/include/iox/into.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
Labels: refactoring

#1891 iox-1613 fix qnx build
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/README.md
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/fatal_failure.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/fatal_failure.inl
  iceoryx_hoofs/time/source/duration.cpp
Labels: bug, refactoring

#1875 iox-1391 move filesystem files to separate module
  .clang-tidy-diff-scans.txt
  README.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl
  iceoryx_hoofs/filesystem/include/iox/filesystem.hpp
  iceoryx_hoofs/filesystem/source/filesystem.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_semaphore.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/filesystem.hpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/source/posix_wrapper/named_semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_filesystem_filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_posix_file_lock.cpp
  iceoryx_hoofs/test/moduletests/test_posix_named_semaphore.cpp
  iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/runtime/ipc_interface_creator.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
Labels: refactoring, globex

#1895 iox-#1892 Ensure the NonZeroedBuffer does not zero its elements
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/test/moduletests/test_container_uninitialized_array.cpp
Labels: bugfix

#1896 iox-1394 fix axivion warnings for multiple files
  iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl
  iceoryx_hoofs/design/include/iox/detail/functional_interface.inl
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/memory/include/iox/bump_allocator.hpp
  iceoryx_hoofs/memory/include/iox/memory.hpp
  iceoryx_hoofs/memory/source/bump_allocator.cpp
  iceoryx_hoofs/primitives/include/iox/size.hpp
  iceoryx_hoofs/test/moduletests/test_time_unit_duration.cpp
  iceoryx_hoofs/test/moduletests/test_utility_into.cpp
  iceoryx_hoofs/time/include/iox/detail/duration.inl
  iceoryx_hoofs/time/include/iox/duration.hpp
  iceoryx_hoofs/time/source/duration.cpp
  iceoryx_hoofs/utility/include/iox/detail/into.inl
  iceoryx_hoofs/utility/include/iox/into.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.inl
Labels: AUTOSAR, Axivion

#1905 iox-#1904 Restore Binding C API compatibility with v2
  iceoryx_binding_c/include/iceoryx_binding_c/log.h
Labels: bugfix

#1907 Iox 1960 update integrationtests
  .github/workflows/build-test.yml
  CONTRIBUTING.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_integrationtest/CMakeLists.txt
  iceoryx_integrationtest/Readme.md
  iceoryx_integrationtest/package.xml
  tools/ci/run-integration-test.sh
Labels: tooling

#1894 iox-1893 fix memory leak in stack
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/buffer/include/iox/detail/stack.inl
  iceoryx_hoofs/buffer/include/iox/stack.hpp
  iceoryx_hoofs/test/moduletests/test_buffer_stack.cpp
Labels: bugfix

#1866 Iox 1815 add determinism label to selected types
  doc/design/determinism.md
  iceoryx_hoofs/buffer/include/iox/stack.hpp
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/container/include/iox/vector.hpp
Labels: documentation

#1912 iox-1391 move remaining utility and design files
  .clang-tidy-diff-scans.txt
  doc/design/diagrams/request_response/request_response_header.puml
  doc/design/request_response_communication.md
  doc/website/images/request_response_header.svg
  iceoryx_binding_c/test/moduletests/test_client.cpp
  iceoryx_binding_c/test/moduletests/test_request_header.cpp
  iceoryx_binding_c/test/moduletests/test_response_header.cpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/design/include/iox/detail/polymorphic_handler.inl
  iceoryx_hoofs/design/include/iox/detail/static_lifetime_guard.inl
  iceoryx_hoofs/design/include/iox/polymorphic_handler.hpp
  iceoryx_hoofs/design/include/iox/static_lifetime_guard.hpp
  iceoryx_hoofs/test/moduletests/test_design_polymorphic_handler.cpp
  iceoryx_hoofs/test/moduletests/test_design_static_lifetime_guard.cpp
  iceoryx_hoofs/test/moduletests/test_utility_unique_id.cpp
  iceoryx_hoofs/utility/include/iox/detail/unique_id.hpp
  iceoryx_hoofs/utility/source/unique_id.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/popo/rpc_header.hpp
  iceoryx_posh/source/popo/rpc_header.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_rpc_header.cpp
Labels: refactoring, globex

#1915 iox-#1394 Fix Axivion warnings in 'string'
  iceoryx_hoofs/vocabulary/include/iox/detail/string.inl
  iceoryx_hoofs/vocabulary/include/iox/detail/string_internal.hpp
  iceoryx_hoofs/vocabulary/include/iox/string.hpp
Labels: AUTOSAR, Axivion

#1916 iox-1394 fix axivion warnings in filesystem
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/README.md
  iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl
  iceoryx_hoofs/filesystem/include/iox/filesystem.hpp
  iceoryx_hoofs/filesystem/source/filesystem.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_semaphore.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/filesystem.hpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/source/posix_wrapper/named_semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_filesystem_filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_posix_named_semaphore.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
Labels: AUTOSAR, Axivion

#1924 iox-#1906 Update ROS 2 Action to v0.6 for fixing APT issue
  .github/workflows/build-test.yml
Labels: bugfix

#1914 iox-1394 fix axivion warnings for multiple files part 2
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/container/include/iox/vector.hpp
  iceoryx_hoofs/design/include/iox/detail/functional_interface.inl
  iceoryx_hoofs/functional/include/iox/detail/storable_function.hpp
  iceoryx_hoofs/functional/include/iox/detail/storable_function.inl
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/attributes.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/deadline_timer.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/expected.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/function.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/function_ref.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/newtype.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/optional.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/scope_guard.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/scoped_static.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/stack.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/type_traits.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/variant.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp
  iceoryx_hoofs/memory/include/iox/bump_allocator.hpp
  iceoryx_hoofs/memory/include/iox/detail/scoped_static.inl
  iceoryx_hoofs/memory/include/iox/memory.hpp
  iceoryx_hoofs/memory/source/bump_allocator.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_container_uninitialized_array.cpp
  iceoryx_hoofs/time/include/iox/detail/duration.inl
  iceoryx_hoofs/time/include/iox/duration.hpp
  iceoryx_hoofs/time/source/duration.cpp
  iceoryx_hoofs/utility/include/iox/detail/into.inl
  iceoryx_hoofs/utility/include/iox/into.hpp
  iceoryx_hoofs/vocabulary/include/iox/detail/expected.inl
  iceoryx_hoofs/vocabulary/include/iox/detail/optional.inl
  iceoryx_hoofs/vocabulary/include/iox/optional.hpp
Labels: AUTOSAR, Axivion

#1909 Consolidate all 'byte_t' type definitions to 'iox::byte'
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/README.md
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/functional/include/iox/detail/storable_function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp
  iceoryx_hoofs/primitives/include/iox/iceoryx_hoofs_types.hpp
  iceoryx_hoofs/vocabulary/include/iox/detail/variant_internal.hpp
  iceoryx_hoofs/vocabulary/include/iox/optional.hpp
  iceoryx_hoofs/vocabulary/include/iox/variant.hpp
Labels: refactoring

#1917 iox-#1913 Add missing test cases for vector and UninitializedArray
  iceoryx_hoofs/test/moduletests/test_container_uninitialized_array.cpp
  iceoryx_hoofs/test/moduletests/test_container_vector.cpp
Labels: test

#1926 iox-#1394 fix axivion warnings for multiple files part 3
  iceoryx_hoofs/container/include/iox/detail/vector.inl
  iceoryx_hoofs/design/include/iox/detail/functional_interface.inl
  iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl
  iceoryx_hoofs/functional/include/iox/detail/function_ref.inl
  iceoryx_hoofs/functional/include/iox/detail/storable_function.inl
  iceoryx_hoofs/memory/include/iox/detail/relative_pointer.inl
  iceoryx_hoofs/memory/include/iox/detail/scoped_static.inl
  iceoryx_hoofs/primitives/include/iox/type_traits.hpp
  iceoryx_hoofs/vocabulary/include/iox/detail/string.inl
  iceoryx_hoofs/vocabulary/include/iox/string.hpp
Labels: AUTOSAR, Axivion

#1898 Introspection-app Wrap c calls in posixCall
  doc/website/release-notes/iceoryx-unreleased.md
  tools/introspection/include/iceoryx_introspection/introspection_app.hpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#1931 iox-1930 remove backticks and add commit hook and ci check
  .github/workflows/build-test.yml
  iceoryx_binding_c/include/iceoryx_binding_c/client.h
  iceoryx_binding_c/include/iceoryx_binding_c/publisher.h
  iceoryx_binding_c/include/iceoryx_binding_c/server.h
  iceoryx_binding_c/include/iceoryx_binding_c/types.h
  iceoryx_dust/include/iceoryx_dust/cli/command_line_argument_definition.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/arguments.hpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_trigger.cpp
  iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c
  iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_publisher.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_subscriber.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/typed_port_api_trait.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_collection_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_segment_manager_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/port_pool_memory_block.hpp
  iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp
  iceoryx_posh/include/iceoryx_posh/popo/response.hpp
  iceoryx_posh/include/iceoryx_posh/popo/sample.hpp
  iceoryx_posh/source/mepoo/chunk_header.cpp
  iceoryx_posh/source/popo/ports/client_port_roudi.cpp
  iceoryx_posh/test/integrationtests/test_service_discovery.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
  tools/git-hooks/pre-commit
  tools/introspection/source/introspection_app.cpp
  tools/scripts/check_invalid_characters.sh
Labels: tooling, technical debt
