Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-11, with the labels that each got.

#2056 iox-#1361 Use shared memory for process alive detection
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/test/moduletests/test_container_fixed_position_container.cpp
  iceoryx_dust/test/moduletests/test_cxx_forward_list.cpp
  iceoryx_hoofs/test/moduletests/test_container_vector.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/lifetime_and_assignment_tracker.hpp
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/error_handling/error_handling.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/heartbeat.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/heartbeat_pool.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/default_roudi_memory.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/roudi_memory_interface.hpp
  iceoryx_posh/source/roudi/memory/default_roudi_memory.cpp
  iceoryx_posh/source/roudi/memory/iceoryx_roudi_memory_manager.cpp
  iceoryx_posh/source/roudi/process.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/heartbeat.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime_heartbeat.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoyx_roudi_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
Labels: refactoring

#2065 iox-#846 Fix warnings on windows
  doc/website/getting-started/installation.md
  iceoryx_dust/test/CMakeLists.txt
  iceoryx_hoofs/test/CMakeLists.txt
  iceoryx_hoofs/test/stresstests/test_resizeable_lockfree_queue_stresstest.cpp
  iceoryx_meta/CMakeLists.txt
  iceoryx_platform/cmake/IceoryxPackageHelper.cmake
  iceoryx_platform/freertos/IceoryxPlatformSettings.cmake
  iceoryx_platform/linux/IceoryxPlatformSettings.cmake
  iceoryx_platform/mac/IceoryxPlatformSettings.cmake
  iceoryx_platform/qnx/IceoryxPlatformSettings.cmake
  iceoryx_platform/unix/IceoryxPlatformSettings.cmake
  iceoryx_platform/win/IceoryxPlatformSettings.cmake
  iceoryx_posh/test/CMakeLists.txt
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  tools/ci/build-test-windows.ps1
Labels: technical debt

#2071 iox-#2070 Move FreeBSD build to Cirrus CI and add aarch64 and Arch Linux builds
  .cirrus.yaml
  .github/workflows/build-test.yml
  README.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl
  iceoryx_hoofs/test/moduletests/test_cxx_variant_queue.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  tools/ci/docker/archlinux-base-devel
  tools/ci/docker/ubuntu-22.04
  tools/iceoryx_build_test.sh
  tools/scripts/add_test_users.sh
Labels: tooling

#2073 iox-#2072 Include mqueue.h needs sys/stat.h for mode_t (fixes musl compile)
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_platform/linux/include/iceoryx_platform/mqueue.hpp
Labels: bugfix

#2079 Adapt PR template to reduced number of reviewers
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#2069 iox-#2052 Implement move/copy constructor and assignment for `FixedPositionContainer`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/container/include/iox/detail/fixed_position_container.inl
  iceoryx_dust/container/include/iox/detail/fixed_position_container_helper.hpp
  iceoryx_dust/container/include/iox/fixed_position_container.hpp
  iceoryx_dust/test/moduletests/test_container_fixed_position_container.cpp
Labels: enhancement

#2091 iox-#1663 Update to gtest 1.14
  cmake/googletest/0001-remove-werror-from-build-flags.patch
  cmake/googletest/CMakeLists.txt
  cmake/googletest/googletest.cmake.in
  iceoryx_examples/icediscovery/include/discovery_blocking.hpp
  iceoryx_examples/icediscovery/include/discovery_monitor.hpp
  iceoryx_posh/test/mocks/base_port_mock.hpp
  iceoryx_posh/test/mocks/client_mock.hpp
  iceoryx_posh/test/mocks/roudi_memory_block_mock.hpp
  iceoryx_posh/test/mocks/roudi_memory_provider_mock.hpp
  iceoryx_posh/test/mocks/server_mock.hpp
  iceoryx_posh/test/mocks/trigger_handle_mock.hpp
  iceoryx_posh/test/moduletests/test_popo_smart_chunk_common.hpp
  iceoryx_posh/testing/include/iceoryx_posh/testing/mocks/posh_runtime_mock.hpp
Labels: refactoring, tooling

#2085 iox-#2084 Fix qnx build and setup CI for gcc 8.3
  .cirrus.yaml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/container/include/iox/fixed_position_container.hpp
  tools/ci/docker/archlinux-base-devel
Labels: bugfix, tooling

#2096 iox-#2066 Switch to C++17
  .bazelrc
  .clang-tidy
  CONTRIBUTING.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/test/moduletests/test_cli_command_line_common.hpp
  iceoryx_hoofs/README.md
  iceoryx_platform/linux/IceoryxPlatformSettings.cmake
  iceoryx_platform/qnx/IceoryxPlatformSettings.cmake
  iceoryx_posh/test/CMakeLists.txt
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  tools/ci/build-test-windows.ps1
Labels: enhancement

#2088 iox-#2087 Fix allocation for mempools larger than 4gb
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp
  iceoryx_posh/source/mepoo/mem_pool.cpp
  iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp
Labels: bugfix

#2097 iox-#1391 Remove posix from include path and namespace in dust
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/posix/ipc/include/iox/message_queue.hpp
  iceoryx_dust/posix/ipc/include/iox/named_pipe.hpp
  iceoryx_dust/posix/ipc/source/message_queue.cpp
  iceoryx_dust/posix/ipc/source/named_pipe.cpp
  iceoryx_dust/posix/sync/include/iox/signal_watcher.hpp
  iceoryx_dust/posix/sync/source/signal_watcher.cpp
  iceoryx_dust/test/moduletests/test_posix_sync_signal_watcher.cpp
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp
  iceoryx_examples/callbacks/ice_callbacks_publisher.cpp
  iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
  iceoryx_examples/complexdata/iox_publisher_complexdata.cpp
  iceoryx_examples/complexdata/iox_publisher_vector.cpp
  iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp
  iceoryx_examples/complexdata/iox_subscriber_vector.cpp
  iceoryx_examples/ice_access_control/iox_display_app.cpp
  iceoryx_examples/ice_access_control/iox_radar_app.cpp
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery/iox_publisher.cpp
  iceoryx_examples/icedelivery/iox_publisher_untyped.cpp
  iceoryx_examples/icedelivery/iox_subscriber.cpp
  iceoryx_examples/icedelivery/iox_subscriber_untyped.cpp
  iceoryx_examples/icediscovery/iox_discovery_monitor.cpp
  iceoryx_examples/icediscovery/iox_find_service.cpp
  iceoryx_examples/icediscovery/iox_offer_service.cpp
  iceoryx_examples/icediscovery/iox_wait_for_service.cpp
  iceoryx_examples/icehello/README.md
  iceoryx_examples/icehello/iox_publisher_helloworld.cpp
  iceoryx_examples/icehello/iox_subscriber_helloworld.cpp
  iceoryx_examples/iceoptions/iox_publisher_with_options.cpp
  iceoryx_examples/iceoptions/iox_subscriber_with_options.cpp
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response/client_cxx_basic.cpp
  iceoryx_examples/request_response/client_cxx_untyped.cpp
  iceoryx_examples/request_response/client_cxx_waitset.cpp
  iceoryx_examples/request_response/server_cxx_basic.cpp
  iceoryx_examples/request_response/server_cxx_listener.cpp
  iceoryx_examples/request_response/server_cxx_untyped.cpp
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_examples/user_header/README.md
  iceoryx_examples/user_header/publisher_cxx_api.cpp
  iceoryx_examples/user_header/publisher_untyped_cxx_api.cpp
  iceoryx_examples/user_header/subscriber_cxx_api.cpp
  iceoryx_examples/user_header/subscriber_untyped_cxx_api.cpp
  iceoryx_examples/waitset/ice_waitset_publisher.cpp
  iceoryx_hoofs/cmake/IceoryxPlatform.cmake
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/source/roudi/application/iceoryx_roudi_app.cpp
  iceoryx_posh/source/roudi/application/roudi_app.cpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_runtime_ipc_interface.cpp
Labels: refactoring

#2102 iox-#2007 Update developer meetup info
  GOVERNANCE.md
Labels: documentation

#2098 iox-#2060 Fix clang tidy warning from full scan
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/functional/include/iox/detail/function_ref.inl
  iceoryx_hoofs/memory/include/iox/detail/scope_guard.inl
  iceoryx_hoofs/memory/include/iox/scope_guard.hpp
  iceoryx_hoofs/posix/time/include/iox/detail/adaptive_wait.hpp
  iceoryx_hoofs/posix/time/source/adaptive_wait.cpp
  iceoryx_hoofs/test/moduletests/test_container_list.cpp
  iceoryx_hoofs/test/moduletests/test_functional_function_ref.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_listener.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp
  iceoryx_posh/source/popo/building_blocks/condition_listener.cpp
  iceoryx_posh/source/runtime/service_discovery.cpp
  iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
Labels: bugfix

#2090 removed IOX_INTERNAL_MAX_NUMBER_OF_NOTIFIERS made IOX_MAX_NUMBER_OF_N…
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/BUILD.bazel
  iceoryx_posh/cmake/IceoryxPoshDeployment.cmake
  iceoryx_posh/cmake/iceoryx_posh_deployment.hpp.in
Labels: refactoring

#2101 Add introspection to ROS release for `master` branch
  doc/website/release-notes/iceoryx-unreleased.md
  tools/introspection/CMakeLists.txt
  tools/introspection/COLCON_IGNORE
  tools/introspection/package.xml
Labels: tooling

#2105 iox-#2052 Refactor copy_and_move_impl
  iceoryx_dust/container/include/iox/detail/fixed_position_container.inl
  iceoryx_dust/container/include/iox/detail/fixed_position_container_helper.hpp
  iceoryx_dust/container/include/iox/fixed_position_container.hpp
Labels: refactoring

#2109 iox-#2108 Public API to create 'access_rights' from value
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl
  iceoryx_hoofs/filesystem/include/iox/filesystem.hpp
  iceoryx_hoofs/posix/design/include/iox/detail/file_management_interface.inl
  iceoryx_hoofs/test/moduletests/test_filesystem_filesystem.cpp
Labels: enhancement, refactoring

#2116 Forward port changes from release `2.x` to `master`
  tools/introspection/CMakeLists.txt
  tools/introspection/package.xml
Labels: tooling

#2110 iox-#1391 Move 'AccessMode' and 'OpenMode' to 'filesystem.hpp'
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/posix/ipc/source/named_pipe.cpp
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl
  iceoryx_hoofs/filesystem/include/iox/filesystem.hpp
  iceoryx_hoofs/filesystem/source/filesystem.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/types.inl
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_semaphore.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/types.hpp
  iceoryx_hoofs/posix/filesystem/include/iox/file.hpp
  iceoryx_hoofs/posix/filesystem/source/file.cpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/source/posix_wrapper/types.cpp
  iceoryx_hoofs/test/moduletests/test_filesystem_filesystem.cpp
  iceoryx_hoofs/test/moduletests/test_posix_file.cpp
  iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  iceoryx_hoofs/test/moduletests/test_posix_types.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp
  iceoryx_posh/source/roudi/memory/default_roudi_memory.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
Labels: refactoring

#2111 iox-#1391 Rename 'posixCall' to 'IOX_POSIX_CALL' and move header to 'iox/posix_call.hpp'
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/posix/ipc/source/message_queue.cpp
  iceoryx_dust/utility/include/iox/detail/convert.hpp
  iceoryx_dust/utility/include/iox/detail/convert.inl
  iceoryx_examples/iceperf/mq.cpp
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp
  iceoryx_hoofs/posix/design/include/iox/detail/posix_call.inl
  iceoryx_hoofs/posix/design/include/iox/posix_call.hpp
  iceoryx_hoofs/posix/design/source/file_management_interface.cpp
  iceoryx_hoofs/posix/filesystem/source/file.cpp
  iceoryx_hoofs/posix/time/source/deadline_timer.cpp
  iceoryx_hoofs/reporting/source/log/building_blocks/console_logger.cpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
  iceoryx_hoofs/source/posix_wrapper/named_semaphore.cpp
  iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
  iceoryx_hoofs/source/posix_wrapper/scheduler.cpp
  iceoryx_hoofs/source/posix_wrapper/semaphore_interface.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/source/posix_wrapper/signal_handler.cpp
  iceoryx_hoofs/source/posix_wrapper/system_configuration.cpp
  iceoryx_hoofs/source/posix_wrapper/thread.cpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_hoofs/source/posix_wrapper/unnamed_semaphore.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_rights.cpp
  iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_time_unit_duration.cpp
  iceoryx_hoofs/test/moduletests/test_unix_domain_sockets.cpp
  iceoryx_hoofs/time/source/duration.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/runtime/heartbeat.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#2118 Fix ROS 2 RHEL build
  tools/introspection/CMakeLists.txt
Labels: tooling

#2123 iox-#2121 Fix history request is out of limit.
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
Labels: bugfix

#2112 iox-#1391 Move 'PosixGroup' and 'PosixUser' to new location
  .cirrus.yaml
  .github/workflows/build-test.yml
  doc/website/advanced/configuration-guide.md
  iceoryx_examples/iceperf/roudi_main_static_config.cpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/access_control.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp
  iceoryx_hoofs/posix/auth/include/iox/posix_group.hpp
  iceoryx_hoofs/posix/auth/include/iox/posix_user.hpp
  iceoryx_hoofs/posix/auth/source/posix_group.cpp
  iceoryx_hoofs/posix/auth/source/posix_user.cpp
  iceoryx_hoofs/posix/design/source/file_management_interface.cpp
  iceoryx_hoofs/source/posix_wrapper/access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_rights.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  iceoryx_platform/mac/include/iceoryx_platform/acl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/mepoo/segment_config.hpp
  iceoryx_posh/roudi_env/source/minimal_roudi_config.cpp
  iceoryx_posh/source/mepoo/segment_config.cpp
  iceoryx_posh/source/roudi/process.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
  iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
  iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
Labels: refactoring

#2114 iox-#1391 Move 'UnixDomainSocket', 'IpcChannel' and 'AccessController' to new location
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/posix/ipc/include/iox/message_queue.hpp
  iceoryx_dust/posix/ipc/include/iox/named_pipe.hpp
  iceoryx_dust/posix/ipc/source/message_queue.cpp
  iceoryx_dust/posix/ipc/source/named_pipe.cpp
  iceoryx_examples/iceperf/mq.cpp
  iceoryx_examples/iceperf/mq.hpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/cmake/IceoryxPlatform.cmake
  iceoryx_hoofs/posix/filesystem/include/iox/detail/posix_acl.hpp
  iceoryx_hoofs/posix/filesystem/source/posix_acl.cpp
  iceoryx_hoofs/posix/ipc/include/iox/posix_ipc_channel.hpp
  iceoryx_hoofs/posix/ipc/include/iox/unix_domain_socket.hpp
  iceoryx_hoofs/posix/ipc/source/unix_domain_socket.cpp
  iceoryx_hoofs/test/moduletests/test_posix_filesystem_posix_acl.cpp
  iceoryx_hoofs/test/moduletests/test_posix_ipc_unix_domain_sockets.cpp
  iceoryx_posh/cmake/IceoryxPoshDeployment.cmake
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp
  iceoryx_posh/source/runtime/ipc_interface_base.cpp
  iceoryx_posh/source/runtime/ipc_interface_creator.cpp
  iceoryx_posh/source/runtime/ipc_interface_user.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_runtime_ipc_interface.cpp
Labels: refactoring
