Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-10, with the labels that each got.

#2037 iox-#1755 Reintroduce lazy evaluation for the logging
  .github/workflows/lint_pull_request.yml
  doc/design/logging.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/error_reporting/custom/default/error_reporting.inl
  iceoryx_hoofs/include/iceoryx_hoofs/error_reporting/error_logging.hpp
  iceoryx_hoofs/reporting/include/iox/detail/log/logstream.inl
  iceoryx_hoofs/reporting/include/iox/log/logstream.hpp
  iceoryx_hoofs/reporting/include/iox/logging.hpp
  iceoryx_hoofs/test/moduletests/test_reporting_logging.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  tools/scripts/clang_tidy_check.sh
Labels: enhancement

#2042 iox-#2041 Move test class for ctor and assignment operator to hoofs testing
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/test/moduletests/test_cxx_forward_list.cpp
  iceoryx_hoofs/test/moduletests/test_container_vector.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/ctor_and_assignment_operator_test_class.hpp
Labels: refactoring

#2043 iox-#1755 Add log bin and log raw
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/reporting/include/iox/detail/log/building_blocks/console_logger.inl
  iceoryx_hoofs/reporting/include/iox/detail/log/logstream.inl
  iceoryx_hoofs/reporting/include/iox/log/building_blocks/console_logger.hpp
  iceoryx_hoofs/reporting/include/iox/log/logstream.hpp
  iceoryx_hoofs/reporting/source/log/building_blocks/console_logger.cpp
  iceoryx_hoofs/test/moduletests/test_reporting_logstream.cpp
  iceoryx_platform/win/include/iceoryx_platform/unistd.hpp
Labels: enhancement

#2061 [Stacked on #2059] iox-#1391 Move list to container module
  .github/workflows/build-test.yml
  .github/workflows/lint_pull_request.yml
  iceoryx_examples/complexdata/topic_data.hpp
  iceoryx_hoofs/container/include/iox/detail/list.inl
  iceoryx_hoofs/container/include/iox/list.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/list.hpp
  iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp
  iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
Labels: refactoring

#2054 iox-#66 Remove 'ObjectPool'
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/README.md
  iceoryx_dust/include/iceoryx_dust/cxx/objectpool.hpp
  iceoryx_dust/test/moduletests/test_cxx_objectpool.cpp
  iceoryx_posh/include/iceoryx_posh/gateway/channel.hpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/channel.inl
  iceoryx_posh/test/moduletests/test_gw_channel.cpp
Labels: refactoring, technical debt

#2053 iox-#2044 Use new fixed position container
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/fixed_size_container.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_pool_data.inl
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/port_pool.inl
  iceoryx_posh/source/roudi/port_manager.cpp
  iceoryx_posh/source/roudi/port_pool.cpp
  iceoryx_posh/test/moduletests/test_fixed_size_container.cpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
Labels: refactoring, technical debt

#2068 iox-#2067 Support move-only types in the LockFreeQueue
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/lockfree_queue.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/resizeable_lockfree_queue.inl
  iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue.cpp
Labels: bugfix
