Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-04, with the labels that each got.

#1960 iox-#1612 add string convertion with optional
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl
  iceoryx_dust/test/moduletests/test_cxx_string_conversion.cpp
Labels: enhancement, technical debt

#1957 iox-1955 use posix compliant calls to set nonblocking flags
  iceoryx_examples/iceperf/uds.cpp
  iceoryx_platform/linux/include/iceoryx_platform/fcntl.hpp
  iceoryx_platform/linux/source/fnctl.cpp
  iceoryx_platform/mac/include/iceoryx_platform/fcntl.hpp
  iceoryx_platform/mac/source/fnctl.cpp
  iceoryx_platform/qnx/include/iceoryx_platform/fcntl.hpp
  iceoryx_platform/qnx/source/fnctl.cpp
  iceoryx_platform/unix/include/iceoryx_platform/fcntl.hpp
  iceoryx_platform/unix/source/fnctl.cpp
  iceoryx_platform/win/include/iceoryx_platform/fcntl.hpp
  iceoryx_platform/win/source/fnctl.cpp
Labels: bugfix

#1964 iox-#1963 Fix UB in publishCopyOf and publishResultOf
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl
Labels: bugfix

#1831 iox-#1755 flush testing logger on terminate
  iceoryx_hoofs/testing/testing_logger.cpp
Labels: test, tooling

#1970 iox-#1969 rework constructors for expected
  iceoryx_hoofs/test/moduletests/test_vocabulary_expected.cpp
  iceoryx_hoofs/vocabulary/include/iox/detail/expected.inl
  iceoryx_hoofs/vocabulary/include/iox/expected.hpp
Labels: refactoring, technical debt

#1978 iox-#1977 ServiceDescription Interfaces and INTERFACE_NAMES do not match
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
Labels: refactoring
