Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-07, with the labels that each got.

#1995 iox-#1994 Use logger for 'RouDi is ready for clients' message
  .github/workflows/lint_pull_request.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/singleprocess/single_process.cpp
  iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
Labels: technical debt

#1999 iox-#1998 enable bazel build with clang
  .bazelrc
  .github/actions/install-iceoryx-deps-and-clang/action.yml
  .github/workflows/build-test.yml
  doc/website/release-notes/iceoryx-unreleased.md
  tools/ci/build-test-ubuntu-bazel.sh
Labels: tooling

#2001 Additional bazel support sanitizer
  .bazelrc
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/test/BUILD.bazel
Labels: tooling

#2002 iox-#1982 Update release notes for FreeRTOS support
  .github/workflows/lint_pull_request.yml
  doc/website/release-notes/iceoryx-unreleased.md
Labels: documentation
