Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-01, with the labels that each got.

#1839 iox-#1835 fixed spelling error in mutex log error msg
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
Labels: refactoring

#1837 iox-#1835 updated monotonic naming
  iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp
Labels: refactoring

#1836 Fixed typo in unix_domain_socket.cpp error message
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
Labels: refactoring

#1838 iox-#1835 updated mutex log error message
  iceoryx_hoofs/source/posix_wrapper/mutex.cpp
Labels: refactoring

#1841 iox-#1781 Fix CI warnings regarding GCC, changed files and links
  .github/workflows/build-test.yml
  .github/workflows/lint_pull_request.yml
Labels: bugfix, tooling

#1834 iox-#1394 Fix-axivion-violations-for-iceoryx_hoofs_types_hpp
  iceoryx_hoofs/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/iceoryx_hoofs_types.inl
Labels: AUTOSAR

#1846 iox-1394 Fix AUTOSAR violations in functional_interface
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl
Labels: AUTOSAR, globex

#1789 iox-1726 Move some attributes to `iceoryx_platform`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp
  iceoryx_platform/linux/include/iceoryx_platform/attributes.hpp
  iceoryx_platform/mac/include/iceoryx_platform/attributes.hpp
  iceoryx_platform/qnx/include/iceoryx_platform/attributes.hpp
  iceoryx_platform/unix/include/iceoryx_platform/attributes.hpp
  iceoryx_platform/win/include/iceoryx_platform/attributes.hpp
Labels: refactoring

#1844 iox-#1756 Use iceoryx logger in string.inl
  iceoryx_hoofs/vocabulary/include/iox/detail/string.inl
Labels: refactoring

#1833 iox-#1394 Fix axivion warnings in "string_internal.hpp"
  iceoryx_hoofs/vocabulary/include/iox/detail/string_internal.hpp
Labels: AUTOSAR

#1820 iox-1732 implement bump allocator
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/test/moduletests/test_client.cpp
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_notification_info.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_server.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_dust/README.md
  iceoryx_dust/include/iceoryx_dust/internal/cxx/static_storage.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cxx/static_storage.inl
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_dust/test/moduletests/test_static_storage.cpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/ipc_channel.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/allocator.hpp
  iceoryx_hoofs/memory/include/iox/bump_allocator.hpp
  iceoryx_hoofs/memory/source/bump_allocator.cpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp
  iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
  iceoryx_hoofs/test/moduletests/test_memory_bump_allocator.cpp
  iceoryx_hoofs/test/moduletests/test_posix_allocator.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.inl
  iceoryx_posh/source/mepoo/mem_pool.cpp
  iceoryx_posh/source/mepoo/memory_manager.cpp
  iceoryx_posh/source/roudi/memory/memory_provider.cpp
  iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp
  iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp
  iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_chunk.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shared_pointer.cpp
  iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp
  iceoryx_posh/test/moduletests/test_mepoo_typed_mempool.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp
  iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
  iceoryx_posh/test/moduletests/test_popo_client_port.cpp
  iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
  iceoryx_posh/test/moduletests/test_popo_server_port_common.hpp
  iceoryx_posh/test/moduletests/test_popo_subscriber_port.cpp
  iceoryx_posh/test/moduletests/test_popo_used_chunk_list.cpp
Labels: enhancement, refactoring, globex

#1824 Add Thread Sanitizer
  .github/workflows/build-test.yml
  .github/workflows/lint_master.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/cmake/IceoryxPlatform.cmake
  iceoryx_meta/build_options.cmake
  tools/ci/build-test-macos-with-sanitizers.sh
  tools/ci/build-test-ubuntu-with-sanitizers.sh
  tools/iceoryx_build_test.sh
  tools/run_tests.sh
Labels: tooling

#1800 iox-#1794 Move `uniqueMergeSortedContainers` to `WaitSet`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl
  iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
Labels: refactoring

#1804 iox-1803 Expand cmake configuration options
  doc/website/examples/.pages
  doc/website/examples/small_memory.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_examples/README.md
  iceoryx_examples/small_memory/README.md
  iceoryx_examples/small_memory/options.cmake
  iceoryx_examples/small_memory/roudi_config.toml
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/convert.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/convert.inl
  iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp
  iceoryx_posh/BUILD.bazel
  iceoryx_posh/cmake/IceoryxPoshDeployment.cmake
  iceoryx_posh/cmake/iceoryx_posh_deployment.hpp.in
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  tools/iceoryx_build_test.sh
Labels: enhancement

#1852 iox-#1036 move creation pattern to dust
  .github/workflows/lint_master.yml
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/design/creation.hpp
  iceoryx_dust/include/iceoryx_dust/internal/design/creation.inl
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp
  iceoryx_examples/iceperf/mq.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp
  iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_pointer.hpp
Labels: refactoring

#1784 iox-#1612 Move `std::string` conversion methods to `iceoryx_dust`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option_manager.hpp
  iceoryx_dust/include/iceoryx_dust/internal/cli/option_manager.inl
  iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl
  iceoryx_dust/source/posix_wrapper/named_pipe.cpp
  iceoryx_dust/test/moduletests/test_cli_command_line_parser.cpp
  iceoryx_dust/test/moduletests/test_cxx_string_conversion.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/convert.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/helplets.inl
  iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp
  iceoryx_hoofs/test/moduletests/test_posix_access_control.cpp
  iceoryx_hoofs/test/moduletests/test_posix_file_lock.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_hoofs/test/moduletests/test_unix_domain_sockets.cpp
  iceoryx_hoofs/test/moduletests/test_vocabulary_string.cpp
  iceoryx_hoofs/vocabulary/include/iox/detail/string.inl
  iceoryx_hoofs/vocabulary/include/iox/string.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.inl
  iceoryx_posh/include/iceoryx_posh/roudi/introspection_types.hpp
  iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
  iceoryx_posh/source/roudi/process.cpp
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
  iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
  iceoryx_posh/test/moduletests/test_capro_service.cpp
  iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
  iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp
  iceoryx_posh/test/moduletests/test_posh_runtime.cpp
  iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
  iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
  iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
  tools/introspection/source/introspection_app.cpp
Labels: refactoring

#1830 iox-#1394 Fix axivion warnings in duration class
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl
  iceoryx_hoofs/source/units/duration.cpp
  iceoryx_hoofs/test/moduletests/test_unit_duration.cpp
Labels: AUTOSAR

#1856 iox-1855 Return in `WaitSet::wait` if data was send before `WaitSet::attachState`
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
Labels: bugfix

#1857 iox-1391 Minor fixes related to namespace change
  doc/design/command-line-parser.md
  iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/string.hpp
  iceoryx_hoofs/test/.clang-tidy
  iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp
  iceoryx_hoofs/test/moduletests/test_vocabulary_string.cpp
  iceoryx_hoofs/vocabulary/include/iox/detail/string.inl
  iceoryx_hoofs/vocabulary/include/iox/detail/string_internal.hpp
  iceoryx_hoofs/vocabulary/include/iox/detail/string_type_traits.hpp
  iceoryx_hoofs/vocabulary/include/iox/string.hpp
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp
Labels: refactoring

#1505 iox-#1504 Integration branch for iceoryx v2.0.3 release
  .github/workflows/build-test.yml
  VERSION
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  doc/aspice_swe3_4/example/iceoryx_component/CMakeLists.txt
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-3.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/package.xml
  iceoryx_dds/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/package.xml
  iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
  iceoryx_integrationtest/package.xml
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl
  iceoryx_posh/package.xml
  iceoryx_posh/source/roudi/process_manager.cpp
  iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
  iceoryx_posh/test/moduletests/test_popo_waitset.cpp
  tools/ci/build-test-freebsd.sh
  tools/introspection/CMakeLists.txt
Labels: bugfix

#1656 Iox 1640 create polymorphic singleton abstraction
  .clang-tidy-diff-scans.txt
  doc/design/polymorphic_handler.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/polymorphic_handler.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/static_lifetime_guard.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/design_pattern/polymorphic_handler.inl
  iceoryx_hoofs/include/iceoryx_hoofs/internal/design_pattern/static_lifetime_guard.inl
  iceoryx_hoofs/test/moduletests/test_polymorphic_handler.cpp
  iceoryx_hoofs/test/moduletests/test_static_lifetime_guard.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/barrier.hpp
Labels: enhancement, globex

#1822 iox-#1821 improve error message when creating read-only segment
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp
  iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
Labels: bugfix
