Repository eclipse-iceoryx/iceoryx, pull requests merged in 2023-12, with the labels that each got.

#2126 Prepare `v2.0.5` release
  .github/workflows/build-test.yml
  VERSION
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  doc/website/release-notes/.pages
  doc/website/release-notes/iceoryx-v2-0-4.md
  doc/website/release-notes/iceoryx-v2-0-5.md
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/package.xml
  iceoryx_dds/CMakeLists.txt
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/package.xml
  iceoryx_integrationtest/package.xml
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/package.xml
  tools/ci/run-integration-test.sh
  tools/introspection/CMakeLists.txt
  tools/introspection/package.xml
Labels: tooling

#2125 iox-#1815 Remove 'deterministic' tags
  doc/design/determinism.md
  iceoryx_hoofs/buffer/include/iox/stack.hpp
  iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
  iceoryx_hoofs/container/include/iox/vector.hpp
Labels: technical debt

#2115 Move `move_and_copy_helper` to `iceoryx/design`
  CONTRIBUTING.md
  doc/design/move_and_copy_helper.md
  iceoryx_dust/container/include/iox/detail/fixed_position_container.inl
  iceoryx_dust/container/include/iox/detail/fixed_position_container_helper.hpp
  iceoryx_dust/container/include/iox/fixed_position_container.hpp
  iceoryx_hoofs/design/include/iox/detail/move_and_copy_helper.inl
  iceoryx_hoofs/design/include/iox/move_and_copy_helper.hpp
  iceoryx_hoofs/test/moduletests/test_design_move_and_copy_helper.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/lifetime_and_assignment_tracker.hpp
Labels: enhancement

#2120 iox-#1391 Move multiple classes to new module path
  .clang-format
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_dust/posix/ipc/include/iox/named_pipe.hpp
  iceoryx_dust/posix/ipc/source/named_pipe.cpp
  iceoryx_dust/posix/sync/include/iox/signal_watcher.hpp
  iceoryx_dust/posix/sync/source/signal_watcher.cpp
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.inl
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/thread.hpp
  iceoryx_hoofs/posix/filesystem/include/iox/file_lock.hpp
  iceoryx_hoofs/posix/filesystem/source/file_lock.cpp
  iceoryx_hoofs/posix/sync/include/iox/detail/semaphore_interface.hpp
  iceoryx_hoofs/posix/sync/include/iox/mutex.hpp
  iceoryx_hoofs/posix/sync/include/iox/named_semaphore.hpp
  iceoryx_hoofs/posix/sync/include/iox/thread.hpp
  iceoryx_hoofs/posix/sync/include/iox/unnamed_semaphore.hpp
  iceoryx_hoofs/posix/sync/source/mutex.cpp
  iceoryx_hoofs/posix/sync/source/named_semaphore.cpp
  iceoryx_hoofs/posix/sync/source/semaphore_interface.cpp
  iceoryx_hoofs/posix/sync/source/thread.cpp
  iceoryx_hoofs/posix/sync/source/unnamed_semaphore.cpp
  iceoryx_hoofs/posix/utility/include/iox/detail/posix_scheduler.hpp
  iceoryx_hoofs/posix/utility/include/iox/detail/system_configuration.hpp
  iceoryx_hoofs/posix/utility/source/posix_scheduler.cpp
  iceoryx_hoofs/posix/utility/source/system_configuration.cpp
  iceoryx_hoofs/test/moduletests/test_posix_file.cpp
  iceoryx_hoofs/test/moduletests/test_posix_file_lock.cpp
  iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp
  iceoryx_hoofs/test/moduletests/test_posix_named_semaphore.cpp
  iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
  iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
  iceoryx_hoofs/test/moduletests/test_posix_unnamed_semaphore.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/watch_dog.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_variable_data.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/locking_policy.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_creator.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp
  iceoryx_posh/source/popo/building_blocks/condition_listener.cpp
  iceoryx_posh/source/popo/building_blocks/condition_variable_data.cpp
  iceoryx_posh/source/popo/building_blocks/locking_policy.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/ipc_interface_creator.cpp
  iceoryx_posh/source/runtime/posh_runtime.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_popo_listener.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
Labels: refactoring

#2124 iox-#1391 Move shared memory and signal handler header to new location
  .clang-tidy-diff-scans.txt
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_binding_c/test/moduletests/test_listener.cpp
  iceoryx_binding_c/test/moduletests/test_notification_info.cpp
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_binding_c/test/moduletests/test_subscriber.cpp
  iceoryx_dust/posix/ipc/include/iox/named_pipe.hpp
  iceoryx_dust/posix/ipc/source/named_pipe.cpp
  iceoryx_dust/posix/sync/include/iox/signal_watcher.hpp
  iceoryx_dust/posix/sync/source/signal_watcher.cpp
  iceoryx_dust/test/moduletests/test_posix_sync_signal_watcher.cpp
  iceoryx_examples/icediscovery/iox_wait_for_service.cpp
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response/client_cxx_waitset.cpp
  iceoryx_examples/waitset/ice_waitset_basic.cpp
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
  iceoryx_examples/waitset/ice_waitset_grouping.cpp
  iceoryx_examples/waitset/ice_waitset_individual.cpp
  iceoryx_examples/waitset/ice_waitset_timer_driven_execution.cpp
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/signal_handler.hpp
  iceoryx_hoofs/posix/ipc/include/iox/detail/posix_memory_map.hpp
  iceoryx_hoofs/posix/ipc/include/iox/detail/posix_shared_memory.hpp
  iceoryx_hoofs/posix/ipc/include/iox/posix_shared_memory_object.hpp
  iceoryx_hoofs/posix/ipc/source/posix_memory_map.cpp
  iceoryx_hoofs/posix/ipc/source/posix_shared_memory.cpp
  iceoryx_hoofs/posix/ipc/source/posix_shared_memory_object.cpp
  iceoryx_hoofs/posix/sync/include/iox/signal_handler.hpp
  iceoryx_hoofs/posix/sync/include/iox/thread.hpp
  iceoryx_hoofs/posix/sync/source/signal_handler.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory.cpp
  iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp
  iceoryx_hoofs/test/moduletests/test_posix_signal_handler.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp
  iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp
  iceoryx_posh/roudi_env/source/roudi_env.cpp
  iceoryx_posh/source/mepoo/mepoo_segment.cpp
  iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp
  iceoryx_posh/source/runtime/shared_memory_user.cpp
  iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
  iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
  iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
  iceoryx_posh/test/moduletests/test_roudi_process.cpp
  iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
  iceoryx_posh/test/moduletests/test_runtime_ipc_interface.cpp
  iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp
Labels: refactoring

#2104 iox-#2082 faster vector on POD data
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/container/include/iox/detail/vector.inl
Labels: enhancement

#2129 iox-#2023 Fix bad file descriptor error
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/posix/design/include/iox/file_management_interface.hpp
  iceoryx_hoofs/posix/design/source/file_management_interface.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.hpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl
  iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
Labels: bugfix

#2132 iox-#2130 Move 'convert' to 'iceoryx_hoofs'
  iceoryx_binding_c/test/moduletests/test_publisher.cpp
  iceoryx_hoofs/test/moduletests/test_utility_convert.cpp
  iceoryx_hoofs/utility/include/iox/detail/convert.hpp
  iceoryx_hoofs/utility/include/iox/detail/convert.inl
Labels: refactoring

#2139 iox-#2137 Merge 'ListenerImpl' back to 'Listener'
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/include/iceoryx_posh/popo/notification_attorney.hpp
  iceoryx_posh/source/popo/listener.cpp
Labels: refactoring
