Repository eclipse-iceoryx/iceoryx, pull requests merged in 2024-04, with the labels that each got.

#2246 Add doc how to using iceoryx as 3rdparty dependency
  doc/website/FAQ.md
Labels: documentation

#2254 iox-#1616 Handle 'strerror_r' idiosyncrasies in the platform layer
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/posix/design/include/iox/detail/posix_call.inl
  iceoryx_hoofs/posix/design/include/iox/posix_call.hpp
  iceoryx_platform/generic/include/iceoryx_platform/generic/string.hpp
  iceoryx_platform/generic/include/iceoryx_platform/string.hpp
  iceoryx_platform/generic/source/string.cpp
  iceoryx_platform/test/moduletests/test_platform_string.cpp
  iceoryx_platform/win/include/iceoryx_platform/override/string.hpp
  iceoryx_platform/win/include/iceoryx_platform/platform_correction.hpp
  iceoryx_platform/win/source/string.cpp
Labels: refactoring

#2250 iox-#1293 Document workaround for documentation in internal headers
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/website/release-notes/iceoryx-unreleased.md
Labels: documentation

#2252 iox-#2251 Fix 'Listener' examples
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/website/FAQ.md
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp
  iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp
  iceoryx_examples/callbacks_in_c/README.md
  iceoryx_examples/callbacks_in_c/ice_c_callbacks_subscriber.c
  iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c
  iceoryx_examples/ice_access_control/README.md
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset/ice_waitset_gateway.cpp
Labels: documentation, bugfix

#2256 iox-#2011 Rename 'string.cpp' to fix the clang-tidy check
  .github/workflows/build-test.yml
  iceoryx_platform/generic/source/string_.cpp
Labels: clang-tidy

#2257 iox-#2011 Move FreeBSD back to GitHub actions
  .cirrus.yaml
  .github/workflows/build-test.yml
Labels: tooling

#2271 iox-#2270 Update links to default branch
  .cirrus.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-test.yml
  .github/workflows/lint_pull_request.yml
  CONTRIBUTING.md
  NOTICE.md
  QUALITY_DECLARATION.md
  README.md
  doc/aspice_swe3_4/swe_docu_guidelines.md
  doc/website/FAQ.md
  doc/website/overrides/partials/footer.html
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_examples/callbacks/README.md
  iceoryx_examples/callbacks_in_c/README.md
  iceoryx_examples/complexdata/README.md
  iceoryx_examples/ice_access_control/README.md
  iceoryx_examples/icedelivery/README.md
  iceoryx_examples/icedelivery_in_c/README.md
  iceoryx_examples/icediscovery/README.md
  iceoryx_examples/icediscovery_in_c/README.md
  iceoryx_examples/iceensemble/README.md
  iceoryx_examples/icehello/README.md
  iceoryx_examples/iceoptions/README.md
  iceoryx_examples/iceperf/README.md
  iceoryx_examples/request_response/README.md
  iceoryx_examples/request_response_in_c/README.md
  iceoryx_examples/singleprocess/README.md
  iceoryx_examples/user_header/README.md
  iceoryx_examples/waitset/README.md
  iceoryx_examples/waitset_in_c/README.md
  iceoryx_hoofs/README.md
Labels: documentation, tooling

#2273 iox-#2272 Make iceoryx resource prefix a compile time option
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_platform/mac/include/iceoryx_platform/signal.hpp
  iceoryx_posh/BUILD.bazel
  iceoryx_posh/cmake/IceoryxPoshDeployment.cmake
  iceoryx_posh/cmake/iceoryx_posh_deployment.hpp.in
  iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
  iceoryx_posh/source/iceoryx_posh_types.cpp
  iceoryx_posh/source/roudi/roudi.cpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/moduletests/test_posh_types.cpp
Labels: enhancement, refactoring
