Repository eclipse-iceoryx/iceoryx, pull requests merged in 2024-01, with the labels that each got.

#2142 iox-#1391 Move lock free queues to new location
  .clang-tidy-diff-scans.txt
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue/cyclic_index.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue/cyclic_index.inl
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue/mpmc_index_queue.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue/mpmc_index_queue.inl
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue/mpmc_lockfree_queue.inl
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_lockfree_queue/mpmc_resizeable_lockfree_queue.inl
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_loffli.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_loffli.inl
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/mpmc_resizeable_lockfree_queue.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_fifo.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_fifo.inl
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_sofi.hpp
  iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_sofi.inl
  iceoryx_hoofs/concurrent/buffer/source/mpmc_loffli.cpp
  iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant_queue.hpp
  iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/concurrent/lockfree_queue.hpp
  iceoryx_hoofs/legacy/include/iceoryx_hoofs/concurrent/resizeable_lockfree_queue.hpp
  iceoryx_hoofs/posix/ipc/include/iox/named_pipe.hpp
  iceoryx_hoofs/test/CMakeLists.txt
  iceoryx_hoofs/test/moduletests/test_concurrent_mpmc_index_queue.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_mpmc_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_mpmc_lockfree_queue_cyclic_index.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_mpmc_loffli.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_mpmc_resizeable_lockfree_queue.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_spsc_fifo.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_spsc_sofi.cpp
  iceoryx_hoofs/test/stresstests/BUILD.bazel
  iceoryx_hoofs/test/stresstests/sofi/test_stress_spsc_sofi.cpp
  iceoryx_hoofs/test/stresstests/test_mpmc_lockfree_queue_stresstest.cpp
  iceoryx_hoofs/test/stresstests/test_mpmc_resizeable_lockfree_queue_stresstest.cpp
  iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/ports/interface_port_data.hpp
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/source/mepoo/mem_pool.cpp
  iceoryx_posh/test/moduletests/test_mepoo_typed_mempool.cpp
Labels: refactoring, technical debt

#2143 iox-#1391 Move remaining concurrent classes to new location
  .clang-tidy-diff-scans.txt
  iceoryx_hoofs/BUILD.bazel
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/README.md
  iceoryx_hoofs/concurrent/sync/include/iox/detail/periodic_task.hpp
  iceoryx_hoofs/concurrent/sync/include/iox/detail/periodic_task.inl
  iceoryx_hoofs/concurrent/sync/include/iox/detail/smart_lock.inl
  iceoryx_hoofs/concurrent/sync/include/iox/smart_lock.hpp
  iceoryx_hoofs/test/moduletests/test_concurrent_periodic_task.cpp
  iceoryx_hoofs/test/moduletests/test_concurrent_smart_lock.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/testing_logger.hpp
  iceoryx_hoofs/testing/testing_logger.cpp
  iceoryx_posh/include/iceoryx_posh/gateway/gateway_generic.hpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp
  iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl
  iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp
  iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/source/runtime/posh_runtime_impl.cpp
  iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
  iceoryx_posh/test/moduletests/test_popo_listener.cpp
Labels: refactoring, technical debt

#2146 iox-#1032 Refactor 'IOX_REQUIRE'
  doc/design/error_reporting.md
  iceoryx_hoofs/reporting/include/iox/assertions.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/custom/default/error_reporting_impl.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/error_kind.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/errors.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/macros.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/types.hpp
  iceoryx_hoofs/test/moduletests/error_reporting/test_error_reporting_macros.cpp
  iceoryx_hoofs/testing/error_reporting/testing_support.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/error_reporting/testing_support.hpp
Labels: refactoring, technical debt

#2147 iox-#1032 Refine testing with new error reporting
  .cirrus.yaml
  doc/aspice_swe3_4/example/iceoryx_component/test/moduletests/test_component_modules.cpp
  doc/design/error_reporting.md
  iceoryx_binding_c/test/moduletests/main.cpp
  iceoryx_hoofs/reporting/include/iox/assertions.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/configuration.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/custom/default/configuration.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/custom/default/error_handler_interface.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/custom/default/error_reporting_impl.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/error_kind.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/macros.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/types.hpp
  iceoryx_hoofs/reporting/include/iox/error_reporting/violation.hpp
  iceoryx_hoofs/reporting/include/iox/iceoryx_hoofs_errors.hpp
  iceoryx_hoofs/test/integrationtests/test_hoofs_integration.cpp
  iceoryx_hoofs/test/mocktests/test_hoofs_mock.cpp
  iceoryx_hoofs/test/moduletests/error_reporting/module_a/errors.hpp
  iceoryx_hoofs/test/moduletests/error_reporting/module_b/errors.hpp
  iceoryx_hoofs/test/moduletests/error_reporting/test_custom_error_reporting.cpp
  iceoryx_hoofs/test/moduletests/error_reporting/test_error_kind.cpp
  iceoryx_hoofs/test/moduletests/error_reporting/test_error_reporting_macros.cpp
  iceoryx_hoofs/test/moduletests/error_reporting/test_error_reporting_violation.cpp
  iceoryx_hoofs/test/moduletests/error_reporting/test_testing_error_handler.cpp
  iceoryx_hoofs/test/moduletests/test_hoofs_modules.cpp
  iceoryx_hoofs/test/moduletests/test_utility_convert.cpp
  iceoryx_hoofs/testing/error_reporting/testing_error_handler.cpp
  iceoryx_hoofs/testing/error_reporting/testing_support.cpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/error_reporting/testing_error_handler.hpp
  iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/error_reporting/testing_support.hpp
  iceoryx_posh/test/integrationtests/test_posh_integration.cpp
  iceoryx_posh/test/moduletests/test_posh_modules.cpp
Labels: refactoring

#2169 iox-eclipse-iceoryx#1963 support for iox::string in MessageQueue
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/posix/ipc/include/iox/detail/message_queue.inl
  iceoryx_hoofs/posix/ipc/include/iox/message_queue.hpp
  iceoryx_hoofs/posix/ipc/source/message_queue.cpp
Labels: enhancement
