Repository eclipse-iceoryx/iceoryx, pull requests merged in 2025-03, with the labels that each got.

#2422 iox-#2420 Add missing header <chrono>
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_hoofs/platform/win/source/time.cpp
Labels: bugfix

#2428 iox-#1295 Bump version to 2.95.4
  MODULE.bazel
  VERSION
  cmake/package/package.cmake
  doc/aspice_swe3_4/CMakeLists.txt
  iceoryx_binding_c/CMakeLists.txt
  iceoryx_binding_c/cmake/iceoryx_binding_cConfigVersion.cmake
  iceoryx_binding_c/package.xml
  iceoryx_hoofs/CMakeLists.txt
  iceoryx_hoofs/cmake/iceoryx_hoofsConfigVersion.cmake
  iceoryx_hoofs/package.xml
  iceoryx_hoofs/test/moduletests/test_time_unit_duration.cpp
  iceoryx_integrationtest/package.xml
  iceoryx_platform/CMakeLists.txt
  iceoryx_platform/cmake/iceoryx_platformConfigVersion.cmake
  iceoryx_platform/package.xml
  iceoryx_posh/CMakeLists.txt
  iceoryx_posh/cmake/iceoryx_poshConfigVersion.cmake
  iceoryx_posh/package.xml
  tools/introspection/CMakeLists.txt
  tools/introspection/cmake/iceoryx_introspectionConfigVersion.cmake
  tools/introspection/package.xml
Labels: tooling

#2427 iox-#2426 Fix comparison operator in channel.inl
  doc/website/release-notes/iceoryx-unreleased.md
  iceoryx_posh/include/iceoryx_posh/gateway/channel.hpp
  iceoryx_posh/include/iceoryx_posh/internal/gateway/channel.inl
  iceoryx_posh/test/moduletests/test_gw_channel.cpp
Labels: bugfix

#2430 iox-#2011 Update Ubuntu on CI
  .github/workflows/build-test.yml
  .github/workflows/release_build_publish.yml
Labels: tooling

#2425 Iox 2408 multi domain id req rep
  iceoryx_examples/experimental/node/CMakeLists.txt
  iceoryx_examples/experimental/node/iox_cpp_node_client.cpp
  iceoryx_examples/experimental/node/iox_cpp_node_server.cpp
  iceoryx_examples/experimental/node/request_and_response_types.hpp
  iceoryx_integrationtest/CMakeLists.txt
  iceoryx_integrationtest/iceoryx_integrationtest/test_experimental_node_publish_subscribe.py
  iceoryx_integrationtest/iceoryx_integrationtest/test_experimental_node_request_response.py
  iceoryx_posh/experimental/include/iox/posh/experimental/client.hpp
  iceoryx_posh/experimental/include/iox/posh/experimental/detail/client.inl
  iceoryx_posh/experimental/include/iox/posh/experimental/detail/listener.inl
  iceoryx_posh/experimental/include/iox/posh/experimental/detail/server.inl
  iceoryx_posh/experimental/include/iox/posh/experimental/listener.hpp
  iceoryx_posh/experimental/include/iox/posh/experimental/node.hpp
  iceoryx_posh/experimental/include/iox/posh/experimental/server.hpp
  iceoryx_posh/experimental/source/node.cpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_client_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_client_impl.inl
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_server_impl.hpp
  iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_server_impl.inl
  iceoryx_posh/include/iceoryx_posh/popo/client.hpp
  iceoryx_posh/include/iceoryx_posh/popo/listener.hpp
  iceoryx_posh/include/iceoryx_posh/popo/server.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_client.hpp
  iceoryx_posh/include/iceoryx_posh/popo/untyped_server.hpp
  iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp
  iceoryx_posh/test/integrationtests/test_posh_experimental_node.cpp
Labels: enhancement

#2437 iox-#2435: Rename Bzlmod module to `iceoryx`
  MODULE.bazel
Labels: technical debt

#2439 iox-#2438: Update ncurses
  MODULE.bazel
Labels: maintenance
